### ISSUE TITLE
[FEATURE REQUEST] CV TO MIDI

### ISSUE THREAD

**Issue by odahan** [VCVRack/Rack#519] opened 2017-12-13 14:20 UTC
It will be interesting to get CV TO MIDI module in the CORE package.
Lots of hardware semi modular synths are also working with midi and it is far easier than CV/GATE from an audio interface.
Be able to send at least Note and Gate on a given Midi device should be very handy.

**Comment by AndrewBelt** [comment] 2017-12-13 23:10
Duplicate of #81

**Closed by AndrewBelt** 2017-12-13 23:10 UTC
