### ISSUE TITLE
Feature Request. Import and export groups of modules as subpatches

### ISSUE THREAD

**Issue by Strum** [VCVRack/Rack#342] opened 2017-10-30 12:59 UTC
It would be really handy to be able to save a group of modules and their interconnections as a subpatch and then load it into another patch file. 

It would save a lot of work rewiring the same setups in every patch.

**Comment by AndrewBelt** [comment] 2017-10-30 13:03
Duplicate of #129 and #209

**Closed by AndrewBelt** 2017-10-30 13:03 UTC

**Comment by Strum** [comment] 2017-10-30 13:11
Sorry Andrew hadn't seen those.

Thanks, I wasn't after anything complex just select a group of modules by dragging a rectangle and save, then import and drop it at the bottom like you suggested.

Hopefully it won't be too hard to implement.
