### ISSUE TITLE
Binary causes segfault on Linux

### ISSUE THREAD

**Issue by mxa** [VCVRack/Rack#1016] opened 2018-06-18 08:37 UTC
The Linux binary download for 64bit RACK 0.6.1 causes a segmentation fault here
```
./Rack 
Segmentation fault
```
Linux Mint Cinnamon 18.3 64bit, Nvidia drivers

**Comment by AndrewBelt** [comment] 2018-06-18 08:39
Possibly duplicate of #1013. Post a stack trace from gdb there?

**Closed by AndrewBelt** 2018-06-18 08:39 UTC
