### ISSUE TITLE
Random response opening patches

### ISSUE THREAD

**Issue by Jairodallos** [VCVRack/Rack#1429] opened 2019-06-30 02:59 UTC
### Details

Operating system:
Rack version: v1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary
Hello,
 my situation is about opening patches.
you can see in the attached images the way as response the windows file explorer to the open procedure.
Is random the presentation of this menu and random the presentation of the files in explorer: show only folders, or all files in the folder, or if is vcvm selected do not show those file types

Regards
![1](https://user-images.githubusercontent.com/22566357/60391645-f7966780-9ab8-11e9-924e-8d94a9e07364.png)
![2](https://user-images.githubusercontent.com/22566357/60391646-f7966780-9ab8-11e9-959f-613a0647bf2e.png)
![3](https://user-images.githubusercontent.com/22566357/60391647-f7966780-9ab8-11e9-82e7-0e9f7641db40.png)
![4](https://user-images.githubusercontent.com/22566357/60391648-f7966780-9ab8-11e9-88a9-01e2372a55da.png)
![5](https://user-images.githubusercontent.com/22566357/60391649-f7966780-9ab8-11e9-87d9-970dda40acbd.png)
![6](https://user-images.githubusercontent.com/22566357/60391650-f7966780-9ab8-11e9-8503-efa43927983d.png)

### Steps to reproduce
the images was aquired sequentially using DEVICE > PRESET > OPEN, again and again

**Comment by AndrewBelt** [comment] 2019-06-30 03:11
Duplicate of https://github.com/VCVRack/Rack/issues/1407

**Closed by AndrewBelt** 2019-06-30 03:11 UTC
