### ISSUE TITLE
"stay-on" modules browser

### ISSUE THREAD

**Issue by stefanougliano** [VCVRack/Rack#1040] opened 2018-06-28 06:57 UTC
I think it would help the workflow if rather than having to (rightclick > find the author I am looking for > choose the module) for each single piece I could have the browser open on the side > choose all the modules I need > close the browser

**Comment by molluskderek** [comment] 2018-06-28 23:21
That could be cool, as a "pinnable" window.

**Comment by nay-seven** [comment] 2018-06-29 06:07
I agree ! ;-) i often need this too !

**Comment by modlfo** [comment] 2019-06-11 05:13
Closing as duplicate of #1114

**Closed by modlfo** 2019-06-11 05:13 UTC
