### ISSUE TITLE
Feature request : cable color selection

### ISSUE THREAD

**Issue by odahan** [VCVRack/Rack#470] opened 2017-11-29 01:01 UTC
It would be great to be able to select the color of a cables, random colors is nice but does not help much. On my own hardware system I like to use some colored cables for some specific function (modulations, let/right channels, sound vs modulation cables, etc, depending on the path itself).

That must be easy to do, each cable has a color property, it just needs a way to set this value from a dropdown menu for example.

**Comment by milholen** [comment] 2017-11-29 03:34
> That must be easy to do

This is a good feature request that I would also find useful, but nothing is easy:

- Patch cable colors would have to be saved as part of the .vcv file (does not currently happen).
- Design and implement an interface for changing cable colors. A "dropdown menu" might not be ideal (I'm assuming this would allow you to assign a color after each cable is patched, which would be tedious). Maybe you click something in the UI that forces all new patch cables to be a certain color, so you can patch all your triggers with a certain color, then switch colors and patch all your pitch CVs. Or maybe you have to choose a cable color before patching each cable. Users who don't care about cable colors would find this to be a burden, so now it has to be a user preference or people will complain that "_patching in Rack is so slow now._"
- Design and implement an interface for specifying which cable colors you want to use in Rack, which exists as a persistent user setting. Color picker? Manual entry of hex codes?
- Consider whether it's possible to export patch cable color setting and share them between machines, i.e. someone with a studio computer and a laptop for gigs who doesn't want to manually re-enter all their cable colors.
- Determine how to gracefully degrade this new feature when opening older .vcv files created before the feature was implemented. 
- Determine how to handle a situation where one user may want the .vcv file they're uploading to patchstorage.com to be preserved in all its hot pink patch cable glory, but another user wants all cables to be black.

Each of these problems has a solution, but the feature would be more complex to implement than it might seem at first.

**Comment by bontric** [comment] 2017-11-29 09:15
Duplicate of #394

**Comment by AndrewBelt** [comment] 2017-11-29 10:35
@bontric Thanks, I was looking for a duplicate but couldn't find that.

Probably the easiest way to implement, as well as most comfortable UI, is to use a key command while dragging cables. However, two octaves of computer keys are reserved for upcoming the computer MIDI keyboard feature, so we don't have much to choose from.

**Closed by AndrewBelt** 2017-11-29 10:35 UTC

**Comment by odahan** [comment] 2017-11-29 17:34
@milholen 
Well, I'm an IT Pro and what and you say just sounds to me like what a developer would say to a simple user when he doesn't want to do the job :-)
Of course if you split all actions with their details it seems much. That's what developing is.. But, storing a patch color, adding a color selector for new patches with a "random mode" button to simulate current feature, etc, is just the normal job of a developer :-)
(I don't get your cross-platform color problem... there are standard to express colors like in HTML or CSS and that works on all OS and all computers and you get the same color everywhere)
Honestly I don't see here anything "hard" to code in this little feature. 
And I think it will be a little effort for a big result because multicolore spaghetti patches like the ones we are seeing currently do not deserve the excellent work behind the scene. VCV Rack is a beautiful app, it must look beautiful too (users don't read c++ source code, they only see the UI and more : the UX).

**Comment by AndrewBelt** [comment] 2017-11-29 17:39
Send a PR.

Locking.

**Comment by jonheal** [comment] 2017-12-06 16:40
A sub-request of this request: I would be happy if the cable colors were simply remembered between app launches.

**Comment by AndrewBelt** [comment] 2017-12-06 17:11
@jonheal That request is a duplicate of https://github.com/VCVRack/Rack/issues/159
