### ISSUE TITLE
Mac install issue: 'Racks resource directory doesn't exist' + no audio out

### ISSUE THREAD

**Issue by EJGuano** [VCVRack/Rack#1828] opened 2020-08-03 09:26 UTC
### Details

Operating system and version: Mac 10.13.6 and 10.9.5
Rack version 1.1.6 Mac Zip
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): iMac Intel Core i5 + Mac intel core two duo laptop

### Summary
I download zip file to Download folder and unzip, get the error dialogue window (on booting up Rack) 'Racks resource directory doesn't exist'. The Application runs but there is no Audio out. It looks like it's generating audio from cable pulses and oscilloscope wave form. 

### Steps to reproduce
I have tried downloading from Firefox and Safari, direct to desktop rather than DL folder and manually unzipping but does it on both Computers.
![vcv-error](https://user-images.githubusercontent.com/69144196/89167809-c7e74800-d573-11ea-851f-f99f35f2a482.jpeg)

**Comment by AndrewBelt** [comment] 2020-08-03 10:22
Duplicate of https://github.com/VCVRack/Rack/issues/1623

**Closed by AndrewBelt** 2020-08-03 10:22 UTC

**Comment by EJGuano** [comment] 2020-08-03 11:57
Sorry you find my comments so hurtful, you sent me a somewhat curt email, I get it, your busy… but not very customer friendly.
I tried searching for a solution and spent a fair amount of time trying to resolve the issue myself.
Moving forward maybe you could have cut and pasted the solution to Facebook or Github rather than being offended and childish.
Twas just a bit of fun ‘banter’…
