### ISSUE TITLE
inserting a second  audio interface module = silence 

### ISSUE THREAD

**Issue by gentleclockdivider** [VCVRack/Rack#1067] opened 2018-07-18 21:08 UTC
In stand alone version  
Inserting a second audio interface and routing the  signal to the newly inserted audio interface .
Then deleting the first audio interface makes vcv rack unresponsive resulting in a crash 

When in vst mode , inserting a second audio interface module gives no problems , but when deleting ot and re-inserting ..again vcv rack becomes silent

**Comment by AndrewBelt** [comment] 2018-07-18 21:31
Closing because there are virtually no details in your issue to reproduce. Fix this if you'd like the issue reopened.

**Comment by gentleclockdivider** [comment] 2018-07-18 21:45
o.K. here goes .
Win 10 , focusrite audio interface using focusrite asio driver 
Step 1 
Initialize a patch -->signal  routed to  audio interface module ( in my case asio/focusrite ) 
Step 2 : insert a second audio interface module , vcv rack is now silent altough the signal is still routed to the first audio interface .
step 3 : for the first audio interface module select ' NO DEVICE' from the dropdown menu , vcv rack will crash .

When re-launching vcv rack , the patch that has crashed is automatically opened  ( with now 2 audio interfaces )but it  is still unresponsive .
We need to let it crash for a second time , then vcv rack will ask for a new template .

Maybe this is driver related , just trying to help that's all .
Keep up the good work ..it's an amazing piece of software

**Comment by AndrewBelt** [comment] 2018-07-18 21:51
In that case, this is a duplicate of #469

**Closed by AndrewBelt** 2018-07-18 21:51 UTC
