### ISSUE TITLE
Anti-aliasing not enabled on Windows 10

### ISSUE THREAD

**Issue by cunabula27** [VCVRack/Rack#790] opened 2018-03-08 20:52 UTC
OS: Windows 10 / 4k res screen / Nvidia Geforce GTX 1070
Rack: 0.6 master (Pulled 6.22 GMT today)

There appears to be no anti-aliasing on the rendering of the modules on the dev build (see reference image below). Is this by design/something that changes automatically when a production version is released?

Possibly of note: I've not done a fresh pull of the dep folder since Sunday, just in case that would make a difference. 

![2018-03-08](https://user-images.githubusercontent.com/24782488/37175307-0f87f29e-2311-11e8-8162-35163dcaa4d1.png)

**Comment by AndrewBelt** [comment] 2018-03-08 20:54
No idea, and no way for me to test since I don't have your screen.

**Comment by cunabula27** [comment] 2018-03-08 21:11
No problem, just saw the difference so thought I'd mention it on the off chance there was some on/off flag in the rendering code that had changed. If there's no change on other OS/or screen resolutions it's probably something with my set up. Will investigate and report back if I find anything. 

Screenshot above is both the production and dev builds running concurrently with no photoshoppery, I just tried to get the modules looking the same size roughly from within Rack so you could see the difference.

**Comment by AndrewBelt** [comment] 2018-03-08 21:15
Perhaps place
```cpp
		debug("%f %f", gPixelRatio, oversample);
```
before line 60 of `src/FramebufferWidget.cpp`. It should print "3 1" on your screen.

**Comment by cunabula27** [comment] 2018-03-08 21:21
src/widgets/FramebufferWidget.cpp ?

If so yes, gives:

[debug] 3.000000 1.000000

**Comment by AndrewBelt** [comment] 2019-12-03 22:18
Closing as possibly obsolete or unreproducible.

**Closed by AndrewBelt** 2019-12-03 22:18 UTC
