### ISSUE TITLE
Knobs jump to random position on V1. 

### ISSUE THREAD

**Issue by Deniou** [VCVRack/Rack#1385] opened 2019-06-23 05:50 UTC
Sometime, the knobs on any module is "jumping" on a random position by clicking before dragging.

Operating system: Windows 10
Rack version: V1.0
Hardware relevant to your issue: AMD READON, 2012 

I currently don't know how to reproduce it. It just happens sometime.

**Comment by AndrewBelt** [comment] 2019-06-23 14:48
Duplicate of https://github.com/VCVRack/Rack/issues/1367

**Closed by AndrewBelt** 2019-06-23 14:48 UTC
