### ISSUE TITLE
Could not initialize GLFW

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#214] opened 2017-10-11 14:47 UTC
OS (if applicable): Win 10
Version (or "dev" if compiling from source): dev

Just made a "gt pull" and updated ny Rack SOurces.
run "make allplugins"

When running Rack I now get a "Could Not initialize GLFW" error box.

A few hours ago everyhthing went smooth...

**Comment by AndrewBelt** [comment] 2017-10-11 14:57
Duplicate of #213  Pull the latest source

**Closed by AndrewBelt** 2017-10-11 14:57 UTC

**Comment by antoniograzioli** [comment] 2017-10-11 15:59
OK I confirm it's working again.
