### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Drmcallister** [VCVRack/Rack#787] opened 2018-03-08 01:14 UTC
Ability to assign and use tags for controls for use in "live performances..." This would be user-defined keyboard keys.
A keystroke to set the cursor to a particular knob or button, jump-scrolling the screen if necessary.  The ability to set these to display as an option over the display would be nice, but perhaps a cpu hit?

Related, then upon jump, have preset keystrokes for 'increase', 'decrease', 'min', 'max', and maybe definable preset values ('cntl-c = 75%' for example.)

Having watched Nigel's vids, I'm surprised that he hasn't requested this.  LOL

**Comment by Atavic** [comment] 2018-03-08 20:16
MiIDI Learn:https://github.com/VCVRack/Rack/issues/50

**Comment by modlfo** [comment] 2019-06-04 20:37
Duplicate of #50

**Closed by modlfo** 2019-06-04 20:37 UTC
