### ISSUE TITLE
save preset versions within vcv preset save file

### ISSUE THREAD

**Issue by modman2019** [VCVRack/Rack#1756] opened 2020-04-16 12:32 UTC
It would be great if there was a sub preset within a single vcv save file that saves up to 20 presets in a dropdown menu in the file menu. Great for saving different versions of the same patch without saving several vcv files.  selecting these presets would instantly change the sound like pressing random or initializing button does while staying on the beat.  As a bonus would be the ability to assign them to hotkeys on the typing keyboard number pad for quick switching without a mouse.   

This is very useful feature for using sequencers that do not have preset patterns slots built in and also good for changing oscillator sounds for live performance etc.

**Comment by AndrewBelt** [comment] 2020-04-16 14:27
You're using the wrong terminology. "Presets" are for modules. You're talking about "patches".
Duplicate of https://github.com/VCVRack/Rack/issues/316

**Closed by AndrewBelt** 2020-04-16 14:27 UTC

**Comment by modman2019** [comment] 2020-04-16 14:39
yes patches.  my other request is different though

**Comment by AndrewBelt** [comment] 2020-04-16 14:51
Can you describe the difference between #316 and this issue?
