### ISSUE TITLE
[FEATURE REQ] Use computer keyboard as MIDI keyboard (as in Ableton)

### ISSUE THREAD

**Issue by teolaz** [VCVRack/Rack#498] opened 2017-12-07 18:00 UTC
Hi,
just to know if it is developable...
Should be really interesting to have an option where someone can enable or disable the computer keyboard as MIDI keyboard and the program automatically shows in the bottom a keyboard layer where you can map CV/gate for triggered note (and also pitchbending and modwheel?)...
What you think? 
In Ableton, you can see it on top right:

![image](https://user-images.githubusercontent.com/19909323/33730727-2b8a5a4a-db81-11e7-9648-0f5cd79ce951.png)

something like this? 
![image](https://user-images.githubusercontent.com/19909323/33730615-d24dbada-db80-11e7-81fd-17cd274a132b.png)

i know the problem will be handling polyphony, but for now you can treat the midi signal as a LIFO from the keyboard...

**Comment by AndrewBelt** [comment] 2017-12-07 18:14
Duplicate of #109

**Closed by AndrewBelt** 2017-12-07 18:14 UTC
