### ISSUE TITLE
"Could not extract package Fundamental.zip"

### ISSUE THREAD

**Issue by Ajoura** [VCVRack/Rack#1085] opened 2018-08-15 22:31 UTC
I have a user folder in Windows that contains non-Latin symbols.
Whenever I try to load the Rack, it fails to extract the Fundamental.zip package and I cannot do anything.

It works for another user with fully Latin name, but I am not willing to change my user name because of some finicky synthesizer that only understands Latin letters.

Please make it so the Rack would understand other symbols, or if plugin extracting folder would be optional - I cannot work like this. 
Thank you.

**Comment by AndrewBelt** [comment] 2018-08-17 13:53
Duplicate of https://github.com/VCVRack/Rack/issues/436

**Closed by AndrewBelt** 2018-08-17 13:53 UTC

**Comment by coldert** [comment] 2019-03-08 09:00
How is this a duplicate of #436? That issue is about a specific plugin not accepting certain characters. This issue is about VCVRack not evene being able to LOAD any modules because the Windows user has "strange" (in my case "Ä") characters in their name.
