### ISSUE TITLE
Command dragging a wire attached to an input should duplicate the wire.

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [VCVRack/Rack#675] opened 2018-02-02 22:08 UTC
OS (if applicable): Mac
Version (or "dev" if compiling from source): dev

Quartz Composer's wires work like this and I miss it.

**Comment by AndrewBelt** [comment] 2018-02-02 22:29
Duplicate of https://github.com/VCVRack/Rack/issues/306

**Closed by AndrewBelt** 2018-02-02 22:29 UTC
