### ISSUE TITLE
Error during MAke on linux 64

### ISSUE THREAD

**Issue by shreeswifty** [VCVRack/Rack#946] opened 2018-05-09 16:25 UTC
/usr/bin/ld: dep/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libX11.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
compile.mk:52: recipe for target 'Rack' failed
make: *** [Rack] Error 1

**Comment by AndrewBelt** [comment] 2018-05-09 16:33
Please fill out the required OS/version info. https://github.com/VCVRack/Rack/blob/master/.github/ISSUE_TEMPLATE.md#for-bug-reports

**Comment by AndrewBelt** [comment] 2018-05-09 16:34
Never mind, duplicate of https://github.com/VCVRack/Rack/issues/888

**Closed by AndrewBelt** 2018-05-09 16:34 UTC
