### ISSUE TITLE
Module Nesting

### ISSUE THREAD

**Issue by dschiller** [VCVRack/Rack#1027] opened 2018-06-19 16:28 UTC
Make Module Nesting possible. A "Container" can nest any Module. To the Outside a Container can map any Inputs and any Outputs also any Parameter as Rotary. Inputs could be at the top, Rotarys in the middle and Outputs at the bottom. By doubleclicking a Container it will be opened. Special Modules inside the Container will reflect the Inputs, Outputs and Rotarys. The Rotary Mapping is new because one have to Patch a Knob / Fader to one of the Rotarys for the Outside world. Saving Nested Modules would save Building Time.

This is just an Idea I can imagine that this Approach does not follow the "real" Modular World and maybe you ( Andrew ) don't want this kind of behaviour.

Cheers

**Comment by AndrewBelt** [comment] 2018-06-19 17:33
Duplicate of #655

**Closed by AndrewBelt** 2018-06-19 17:33 UTC

**Comment by dschiller** [comment] 2018-06-19 20:52
Hi Andrew, I am sorry for the duplicate!
