### ISSUE TITLE
Scrollable plugins list

### ISSUE THREAD

**Issue by gillesv** [VCVRack/Rack#182] opened 2017-10-05 10:13 UTC
OS (if applicable): Mac 10.12.6
Version (or "dev" if compiling from source): 0.3.2

I installed some plugins and now I can only use the app on my 2560x1440 monitor :/ 
If I install any more the right-click menu just goes off the bottom of the screen and there's no way to scroll inside that. Maybe some sort of hierarchy in the menu (where plugins are grouped together) or just a scrolling list would do the trick. 

Great app otherwise! 

![screen shot 2017-10-05 at 12 13 21](https://user-images.githubusercontent.com/93089/31222197-a1079bf8-a9c6-11e7-9715-97af238e5042.png)

**Comment by rafzael** [comment] 2017-10-05 11:31
In the last dev version modules are classed by plugins series then the list is much shorter. I suppose this feature will be add in the next release too.

**Comment by AndrewBelt** [comment] 2017-10-05 11:41
Duplicate of #68

**Closed by AndrewBelt** 2017-10-05 11:41 UTC
