### ISSUE TITLE
Multiple modules selection/copy/paste

### ISSUE THREAD

**Issue by alfonso73** [VCVRack/Rack#977] opened 2018-05-27 09:00 UTC
Hi all!
When working with polyphony would be great to select multiple modules (and all the connections) so the selection can be copied/pasted.
best!

**Comment by AndrewBelt** [comment] 2018-05-27 09:03
Duplicate of #307

**Closed by AndrewBelt** 2018-05-27 09:03 UTC

**Comment by alfonso73** [comment] 2018-05-27 09:05
oops sorry Andrew.
