### ISSUE TITLE
Look is weird / super tiny

### ISSUE THREAD

**Issue by mxa** [VCVRack/Rack#1019] opened 2018-06-18 17:28 UTC
Sorry, but is it supposed to look like this?

![screenshot from 2018-06-18 19-20-51](https://user-images.githubusercontent.com/1220707/41551875-7550ec9a-732d-11e8-91e1-846796db2b9f.png)

Linux Mint 18.3 Cinnamon 64bit

**Comment by AndrewBelt** [comment] 2018-06-18 17:53
Duplicate of https://github.com/VCVRack/Rack/issues/461

**Closed by AndrewBelt** 2018-06-18 17:53 UTC
