### ISSUE TITLE
No menu appears - graphics are offset from mouse

### ISSUE THREAD

**Issue by dburgan** [VCVRack/Rack#674] opened 2018-02-02 19:34 UTC
OS (if applicable):  Windows 10
Version (or "dev" if compiling from source):  v0.5.1

First thanks for such an amazing project.  It looks cool as can be.

I'm having a problem with what I think is the graphics rendering of VCVRack.  When I start it up, there is no menu bar across the top.  It's like the view port is offset downwards, which cut the menu off at the top.

Further, mouse clicks seem to be offset as well.  If I right click to add a module, I can click on "Core" or "Fundamental", but the mouse has to be below the menu item by about 50 pixels for it to work.

See attached screen shots.  The other clue I can give you is that I've seen this exact same behavior with Second Life, and there are many reported bugs with it.  So it seems to be something with the GL rendering engine under Windows 10.

I'm not sure how I can help you debug this, but I'm definitely willing to try.

Thanks,
Darrell Burgan

![image](https://user-images.githubusercontent.com/25944315/35751345-c0aa9b44-081d-11e8-9fb6-6cca1c165df3.png)

![image](https://user-images.githubusercontent.com/25944315/35751370-d8c16d3e-081d-11e8-85ef-b4f55451b89e.png)

**Comment by AndrewBelt** [comment] 2018-02-02 20:56
Duplicate of https://github.com/VCVRack/Rack/issues/369

**Closed by AndrewBelt** 2018-02-02 20:56 UTC
