### ISSUE TITLE
Module parameters are reset when importing 0.6 patch into 1.0

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1507] opened 2019-07-26 21:07 UTC
When importing a patch created with 0.6 in 1.0, all module parameters in the `data` field seem to be reset. In the new patch everything is reset everything to default values as if the module was just added.

The expected behavior is that values for keys that exist in the `data` field in 0.6 are taken over to the new patch in 1.0.

**Comment by Coirt** [comment] 2019-07-26 21:33
Interesting, probably the reults of new tooltip values can reproduce on fundamental scope.

![paramsOutOfRange1](https://user-images.githubusercontent.com/12150421/61982586-2be83f80-aff5-11e9-99b0-16655c4d6cf2.gif)

**Comment by AndrewBelt** [comment] 2019-07-26 21:38
I can't reproduce this. Post a patch file or more details or something.

**Comment by cschol** [comment] 2019-07-26 21:42
Not sure what @Coirt is referring to there, but I am referring to the parameters that are explicitly stored to `json` in the `toJson` methods. Those don't seem to be preserved.

Can it be a patch with one of my modules (`RadioMusic`)?

**Comment by AndrewBelt** [comment] 2019-07-26 21:48
Nothing is preserved. When loading, JSON is unserialized to C++ data structures, and the `"data`" object is passed to `Module::dataFromJson()`, and when saving, `Module::dataToJson()` is called during JSON serialization.

**Comment by Coirt** [comment] 2019-07-26 21:50
Could be a different issue but it seems related. Tried to reproduce with a 0.6 patch and the scope was the only discrepancy.
[param06_01.zip](https://github.com/VCVRack/Rack/files/3437485/param06_01.zip)

**Comment by cschol** [comment] 2019-07-26 22:05
@AndrewBelt The 0.6 patch file contains values in the `data` object, e.g. a path or a value of a context menu item. Those values are not restored (preserved) when loading the patch file in 1.0. The values are set to default values.

**Comment by AndrewBelt** [comment] 2019-07-26 22:07
@cschol Param objects are in the `.modules[].params` array, not `.modules[].data.params` or anything like that.

**Comment by AndrewBelt** [comment] 2019-07-26 22:09
@Coirt It looks like the time parameter of Fundamental Scope was broken between 0.6 -> 1.0.0. See https://github.com/VCVRack/Fundamental/blob/v0.6/src/Scope.cpp#L326 and https://github.com/VCVRack/Fundamental/blob/v1/src/Scope.cpp#L57. Different issue, but an unfixable one at this point.

**Comment by AndrewBelt** [comment] 2019-07-26 22:12
@cschol `.modules[].data` is passed to `Module::dataFromJson()`. Like I said above, JSON is never "preserved", i.e. the JSON disappears from memory as soon as it is unserialized. It is up to the plugin developer to implement `dataFromJson()` to capture this data and serialize in `dataToJson()`.

**Comment by cschol** [comment] 2019-07-26 22:17
Sorry, I think we are talking about the same thing, but my words are less precise. The persistent value is in `json` on the filesystem. After the patch gets loaded the module's variables (in memory) are not populated with those values (via `dataFromJson()`) when loading the patch in 1.0. The values in memory are the default values.

Let me check into this more. I see this with `Radio Music`. I want to verify that this is not a `Radio Music` issue. I obviously have a `dataFromJson` method, but something else might be wrong.

**Comment by AndrewBelt** [comment] 2019-07-26 22:20
Are you saying that `.modules[].data` is not passed to your `Module::dataFromJson()` method?

**Comment by AndrewBelt** [comment] 2020-04-01 04:03
Closing as unfixable.

**Closed by AndrewBelt** 2020-04-01 04:03 UTC
