### ISSUE TITLE
VCV Rack 1.1.0 won't launch on OS X 10.10.5

### ISSUE THREAD

**Issue by Wetailorsound** [VCVRack/Rack#1409] opened 2019-06-27 11:34 UTC
Hello, I can't launch Rack on my computer.
### Details

Operating system:
Rack version: v1.1.0
Mac Pro 5,1 mid-2010 with 2x2,66 Ghz 6 core Xeon
Running Mac OS 10.10.5

### Summary

When clicking on the app on the dock (or anywhere else, including right click > Open), the app icon keeps bouncing for a few minutes then stops and nothing happens. 

The documents/Rack folder only contains the log file ; 

```
[0.000 info src/main.cpp:112] VCV Rack v1.1.0
[0.000 info src/main.cpp:113] Darwin 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
[0.000 info src/main.cpp:119] Args: /Applications/Rack.app/Contents/MacOS/Rack 
[0.000 info src/main.cpp:122] System directory: /Applications/Rack.app/Contents/Resources
[0.000 info src/main.cpp:123] User directory: /Users/administrateur/Documents/Rack
[0.000 info src/settings.cpp:213] Loading settings /Users/administrateur/Documents/Rack/settings-v1.json
[0.000 info src/main.cpp:145] Initializing environment
```

The log stops here. 

I have another mac pro 5,1 with 4 cores on El capitan that runs Rack fine. 
It seems Rack doesn't write files that should be in "documents/rack", except the log. 
In the log Rack tries to open settings-V1.json but the file doesn't exist in the folder. 

You may also note that I already had the exact same issue with Rack 0.6.x on this computer. 
As I could run the software on my other computer and read that there were issues with 10.10.5, I simply waited for V1, but it didn't solve the issue. 

Has anyone else experienced the same problem ? It may be something wrong with the way mac Os is configured...

Have a nice day everyone, 
Rob'

**Comment by AndrewBelt** [comment] 2019-06-27 14:41
Can't reproduce with the given information.

**Comment by Miserlou** [comment] 2019-06-27 19:31
I have 10.10, Rack 1.1.0 downloaded from the website works fine.

**Comment by spaffinge** [comment] 2019-06-29 08:13
I also have this issue. Haven't been able to run Rack since 0.6.

Mac Mini (Late 2012)
OSX 10.10.5

If I save an empty settings-v1.json, Rack complains, asks if settings should be reset. On OK, Rack 1.1.0 will open, and behave as normal. But trying to open the software after this will not work as above.

Saving a settings-v1.json with any parsable syntax, Rack does not open.

Log on not open (username swapped out for '~'):
[0.000 info src/main.cpp:112] VCV Rack v1.1.0
[0.000 info src/main.cpp:113] Darwin 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64
[0.000 info src/main.cpp:119] Args: /Applications/Rack.app/Contents/MacOS/Rack 
[0.000 info src/main.cpp:122] System directory: /Applications/Rack.app/Contents/Resources
[0.000 info src/main.cpp:123] User directory: /Users/~/Documents/Rack
[0.000 info src/settings.cpp:213] Loading settings /Users/~/Documents/Rack/settings-v1.json
[0.000 info src/main.cpp:145] Initializing environment

Log on open (blank settings-v1.json):
[0.000 info src/main.cpp:112] VCV Rack v1.1.0
[0.000 info src/main.cpp:113] Darwin 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64
[0.000 info src/main.cpp:119] Args: /Applications/Rack.app/Contents/MacOS/Rack 
[0.000 info src/main.cpp:122] System directory: /Applications/Rack.app/Contents/Resources
[0.000 info src/main.cpp:123] User directory: /Users/~/Documents/Rack
[0.000 info src/settings.cpp:213] Loading settings /Users/~/Documents/Rack/settings-v1.json
[5.444 info src/main.cpp:145] Initializing environment
[5.524 info src/plugin.cpp:157] Loaded plugin Core v1.0.0 from 
[5.526 info src/plugin.cpp:157] Loaded plugin Fundamental v1.0.0 from /Users/~/Documents/Rack/plugins-v1/Fundamental
[5.532 info src/main.cpp:160] Initializing app
[5.558 info src/window.cpp:223] Window content scale: 1.000000
[5.627 info src/bridge.cpp:382] Bridge server started
[5.783 info src/window.cpp:263] Renderer: Intel HD Graphics 4000 OpenGL Engine
[5.783 info src/window.cpp:264] OpenGL: 2.1 INTEL-10.6.33
[5.789 info src/window.cpp:33] Loaded font /Applications/Rack.app/Contents/Resources/res/fonts/DejaVuSans.ttf
[5.790 info src/window.cpp:72] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/RackBusboard.svg
[5.790 info src/settings.cpp:196] Saving settings /Users/~/Documents/Rack/settings-v1.json
[5.790 info src/patch.cpp:160] Loading patch /Users/~/Documents/Rack/autosave-v1.vcv
[5.791 info src/window.cpp:72] Loaded SVG /Applications/Rack.app/Contents/Resources/res/Core/AudioInterface.svg
[5.792 info src/window.cpp:72] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/ScrewSilver.svg
[5.792 info src/window.cpp:72] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/PJ301M.svg
[5.792 info src/window.cpp:33] Loaded font /Applications/Rack.app/Contents/Resources/res/fonts/ShareTechMono-Regular.ttf
[5.799 info src/audio.cpp:266] Opening audio RtAudio device 6 with 8 in 8 out
[5.802 info src/audio.cpp:279] Starting RtAudio stream 6
[5.804 info src/window.cpp:72] Loaded SVG /Users/~/Documents/Rack/plugins-v1/Fundamental/res/VCO-1.svg
[5.804 info src/window.cpp:72] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/CKSS_0.svg
[5.804 info src/window.cpp:72] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/CKSS_1.svg
[5.804 info src/window.cpp:72] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/RoundHugeBlackKnob.svg
[5.804 info src/window.cpp:72] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/RoundLargeBlackKnob.svg
[5.806 info src/window.cpp:72] Loaded SVG /Users/~/Documents/Rack/plugins-v1/Fundamental/res/VCA-1.svg
[5.807 info src/window.cpp:72] Loaded SVG /Users/~/Documents/Rack/plugins-v1/Fundamental/res/LFO-2.svg
[5.807 info src/main.cpp:172] Starting engine
[5.807 info src/main.cpp:184] Running window

**Comment by spaffinge** [comment] 2019-06-30 11:50
> (username swapped out for "")

Whoops, looks like a tilde wasn't the best choice. You get the idea

**Comment by rubyglow** [comment] 2019-07-03 10:56
If you have a "template-v1.vcv" file in your documents/Rack directory, try and rename it (to e.g. template-v1.vcv.BKUP) and then try again. This would confirm whether you have modules or stuff in your template that would cause Rack to never open or crash immediately.

**Comment by Wetailorsound** [comment] 2019-07-03 15:55
In my case, this is the first Rack launch, so there is no template file to begin with. As stated in my first post, there is only the log file in documents/Rack.

**Comment by spaffinge** [comment] 2019-07-09 14:59
Just to confirm, this continues in 1.1.1.

**Comment by spaffinge** [comment] 2019-07-16 09:26
> Just to confirm, this continues in 1.1.1.

Only the log file present in Documents>Rack:

[0.000 info src/main.cpp:113] VCV Rack v1.1.1
[0.000 info src/main.cpp:114] Darwin 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64
[0.000 info src/main.cpp:120] Args: /Applications/Rack.app/Contents/MacOS/Rack 
[0.000 info src/main.cpp:123] System directory: /Applications/Rack.app/Contents/Resources
[0.000 info src/main.cpp:124] User directory: /Users/adamstaff/Documents/Rack
[0.000 info src/settings.cpp:213] Loading settings /Users/adamstaff/Documents/Rack/settings-v1.json
[0.000 info src/main.cpp:146] Initializing environment

OSX 10.10.5, Mac Mini (Late 2012), 2.5GHz Intel Core i5, Intel HD Graphics 4000 1024 MB

**Comment by AndrewBelt** [comment] 2020-04-01 03:23
Closing since new releases could have changed this. Comment if issue is still present.

**Closed by AndrewBelt** 2020-04-01 03:23 UTC
