### ISSUE TITLE
VCV does not close when using the close button

### ISSUE THREAD

**Issue by borisv** [VCVRack/Rack#1468] opened 2019-07-09 19:34 UTC
### Details

Operating system: W10 1903 latest update stable
Rack version: v1.1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): audio device(s)

### Summary
VCV does not shut down when using close or x-button (not responding)
### Steps to reproduce
Start VCV -> insert 16 channel beside 8 channel audio module -. close

It closed fine before inserting the 16 channel audio

**Comment by borisv** [comment] 2019-07-16 07:06
Sorry, I didn't have the time to do some follow-up tests. 

So today I tried to start a new patch, but VCV doesn't succeed in clearing the old one -> Not responding.
Tried de-activating VST plugins, clearing cables before creating a new patch or closing VCV -> Not Responding.
Tried opening a saved patch -> Not responding

So for now I am left with the one running patch loaded with no chance to get VCV running anything else(((

**Comment by borisv** [comment] 2019-07-16 08:23
So after starting VCV by doubleclicking another patch I managed open a different patch to reproduce the behaviour:

Load an existing patch with Audio 8 inserted and an audio interface selected - insert an Audio 16 besides Audio 8 - Try deselecting audio interface in Audio 8 -> Not responding.

These two apparently don't like to co-exist, and all further actions, like closing VCV, switching audio interface lead to -> Not responding

**Comment by borisv** [comment] 2019-07-16 09:54
After some more tries it boils down to the following: 

If an additional Audio module is inserted, selecting the same audio interface, making use of the same initial ports as the Audio module already in place -> every action to deselect these ports, select a different audio interface or different ports on that interface -> freezes VCV.

If you make NO attempt to change any parameters of the Audio module inserted in the first place, the two concurring Audio modules using the same interface and ports can co-exist, you can still run the application and audio is more or less reliably working, BUT you can not close the application as such.

**Comment by jeremywen** [comment] 2019-07-22 14:18
https://vcvrack.com/manual/Core.html#audio

> Note: Using multiple Audio modules is experimental and may crash Rack or render unstable audio. Most DAWs avoid this feature entirely by restricting audio to a single input and a single output device for stability reasons, but if using multiple audio devices in Rack works with your configuration, more power to you!

**Comment by AndrewBelt** [comment] 2020-04-01 16:42
Caused by #132, closing.

**Closed by AndrewBelt** 2020-04-01 16:42 UTC
