### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by odahan** [VCVRack/Rack#436] opened 2017-11-23 20:57 UTC
OS (if applicable): W10
Version (or "dev" if compiling from source): 0.5

Notes module does not take into account letters like éàçÏô etc... Worse, it does strange things when such letters are typed (like cursor going backward).

**Comment by Strum** [comment] 2017-11-24 16:26
An unfortunate choice of words for your topic there @odahan 

i'll just leave it at that.

lol

**Comment by odahan** [comment] 2017-12-12 23:47
@Strum I don't get it :-( My english is far from perfect but I'm always pleased to learn something new. It is out of topic here, but if you can explain I'll learn something new thanks to this bug :-)

**Comment by Strum** [comment] 2017-12-13 05:10
@odahan 

https://www.urbandictionary.com/define.php?term=french%20letter

**Comment by odahan** [comment] 2017-12-13 14:14
LOL. What a strange expression :-) Thanks I know something new and useful, I will use "French characters" instead (don't say me it means another strange thing !).

**Comment by Strum** [comment] 2017-12-14 04:31
@odahan , I think you're right with that.

:)

English is a funny language.

**Comment by odahan** [comment] 2017-12-14 11:49
> English is a funny language.
French too... a world of rules but with as many exceptions than regular cases !

**Comment by odahan** [comment] 2018-02-23 13:27
Annoying.

**Comment by AndrewBelt** [comment] 2018-02-23 13:29
Feel free to send a PR. (But first wait a few days because I have some large changes that would make merges difficult.) I don't have time to fix it for 0.6, maybe 1.0.

**Comment by odahan** [comment] 2018-02-23 13:33
I know until 1.0 there are more important things to do and fix.
I was not suspecting a modern app like VCV was using libraries not having native unicode support, that's why I was reporting this as a bug.

**Comment by AndrewBelt** [comment] 2018-02-23 13:35
Simply using modern libraries does not automatically give you UTF-8 support.
The relevant code is in https://github.com/VCVRack/Rack/blob/master/src/ui/TextField.cpp

**Comment by HSBallina** [comment] 2019-04-08 21:09
Wouldn't it be possible to point the Rack-folders somewhere else than having it pointing to the documents folder? For me, as for many other users (I presume), this is kind of a showstopper. Or am I missing something obvious here?

**Comment by AndrewBelt** [comment] 2019-06-02 23:05
@HSBallina Yes, see https://vcvrack.com/manual/Installing.html#command-line-usage

**Comment by nesdnuma** [comment] 2019-08-16 14:19
The issue is still present on Rack 1.1.3/Windows 10.

**Comment by mestretheo** [comment] 2020-12-23 21:28
We're finishing 2020 without UTF-8 in VCV. As a portuguese speaker, I may say it would be really useful to write with those UTF-8 characters. I'm a teacher and would be wonderful to write comments within the patches using modules like the many TD-xxx from Submarine. Hope this won't take too long.

**Comment by AndrewBelt** [comment] 2020-12-23 22:33
This issue is obsolete, closing. There are other more specific issues about UTF-8 on Windows.

**Closed by AndrewBelt** 2020-12-23 22:33 UTC
Labels: bug
