### ISSUE TITLE
Instantly crashes when loading certain Modules.

### ISSUE THREAD

**Issue by MadMike408** [VCVRack/Rack#72] opened 2017-09-14 03:30 UTC
I can't load certain Modules without Rack instantly crashing when I try to load them. Specifically the Macro Oscillator, the Texture Synthesizer, The Meta Modulator and the Spring Reverb all cause Rack to Crash. I'm using Windows 7 64 bit.

Here's the Crash Report when I try to load the Macro Oscillator.

Problem Event Name:	APPCRASH
  Application Name:	Rack.exe
  Application Version:	0.0.0.0
  Application Timestamp:	59b94010
  Fault Module Name:	plugin.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	59b8e516
  Exception Code:	c000001d
  Exception Offset:	0000000000017c4c
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	e914
  Additional Information 2:	e914fe82c6bf8ffa7a7209b9ba4424cf
  Additional Information 3:	29bf
  Additional Information 4:	29bf413592713bdc00a9d10003ee39ed

**Comment by AndrewBelt** [comment] 2017-09-14 10:23
Can't reproduce on my systems and not enough information in the crash text. Are you using v0.3.1?

**Comment by SurrealFunfair** [comment] 2017-09-14 12:58
same issue here running version 0.3.0 on WIN7.

**Comment by k2z3k0** [comment] 2017-09-14 14:16
hi there
my VCV crash with audible plugs MAcro Oscilator also Spring reverb

Problem signature:
 Problem Event Name: APPCRASH
 Application Name: Rack.exe
 Application Version: 0.0.0.0
 Application Timestamp: 59b54df4
 Fault Module Name: plugin.dll
 Fault Module Version: 0.0.0.0
 Fault Module Timestamp: 59b51558
 Exception Code: c000001d
 Exception Offset: 0000000000017b4c
 OS Version: 6.1.7601.2.1.0.256.1
 Locale ID: 1033
 Additional Information 1: e914
 Additional Information 2: e914fe82c6bf8ffa7a7209b9ba4424cf
 Additional Information 3: b055
 Additional Information 4: b0555685cf158c41fe197e642d620ff9

bests

**Comment by MadMike408** [comment] 2017-09-14 14:31
Yes I'm using version 0.3.1 but it crashes regardless if it's 0.3.0 or 0.3.1.

**Comment by MadMike408** [comment] 2017-09-14 19:53
I loaded VCV Rack on my Windows 10 computer and all the modules work fine. It only doesn't work on my Windows 7 computer.

**Comment by k2z3k0** [comment] 2017-09-14 20:19
Possibly lack of some library?

**Comment by k2z3k0** [comment] 2017-09-14 20:19
I've noticed on fresh install win 7 doesnt work at all,it crashes at start

**Comment by Taikakim** [comment] 2017-09-17 20:46
64bit version on Windows 7, AMD Phenom II X6 1055T, 8GB, also get instant crash on loading macro oscillator:

Problem Event Name:	APPCRASH
  Application Name:	Rack.exe
  Application Version:	0.0.0.0
  Application Timestamp:	59b94010
  Fault Module Name:	plugin.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	59b8e516
  Exception Code:	c000001d
  Exception Offset:	0000000000017c4c
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1035
  Additional Information 1:	e914
  Additional Information 2:	e914fe82c6bf8ffa7a7209b9ba4424cf
  Additional Information 3:	e5d8
  Additional Information 4:	e5d8b6a939ee9e3ec07e70462400c4b9

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by AndrewBelt** [comment] 2017-09-17 21:01
Could someone with this issue run Rack inside gdb (on MSYS2 for example)?

**Comment by l33chy** [comment] 2017-09-27 12:52
I have the same issue on a Windows 7 x64 on an AMD Phenom II X6...
As you suggested I ran Rack.exe from gdb and got this when trying to add the "Macro Oscillator" or Braids:

`Thread 42 received signal SIGILL, Illegal instruction.
[Switching to Thread 5464.0x978]
0x0000000067e965dd in braids::MacroOscillator::RenderCSaw (this=0x92879f0, sync=<optimized out>, buffer=<optimized out>, size=<optimized out>) at eurorack/braids/macro_oscillator.cc:62
62      eurorack/braids/macro_oscillator.cc: No such file or directory.
(gdb)`

Same happens for warps:

`Thread 1 received signal SIGILL, Illegal instruction.
0x0000000067ec8e04 in warps::QuadratureTransform::AllPassFilter::Init (coefficient=<optimized out>, this=<optimized out>) at ./eurorack/warps/dsp/quadrature_transform.h:78
78      ./eurorack/warps/dsp/quadrature_transform.h: No such file or directory.
(gdb)
`
I have the Rack folder on the root level of my harddisk...

Let me know if you need more info.

Thanks!

**Comment by AndrewBelt** [comment] 2017-09-27 12:55
@l33chy Rack version? You're not mixing different plugin versions, are you?

**Comment by l33chy** [comment] 2017-09-27 12:56
No, all I did was downloading the zip from the homepage, registered an account and then added the plugins via the page...

**Comment by l33chy** [comment] 2017-09-27 13:00
no same issue. I deleted the Rack folder, downloaded it from the page, entered my credentials and hit "Refresh Plugins". It downloaded them and when adding braids it crashes with the same exception.

**Comment by AndrewBelt** [comment] 2017-09-27 13:08
Are those the only two modules that crash Rack? Is there any randomness in the crashes?

**Comment by l33chy** [comment] 2017-09-27 13:17
No, it's crashing consistently for me everytime when trying to add:

- Macro Oscillator:
`Thread 17 received signal SIGILL, Illegal instruction.
[Switching to Thread 6588.0x1cf4]
0x0000000067e965dd in braids::MacroOscillator::RenderCSaw (this=0x951ced0,
    sync=<optimized out>, buffer=<optimized out>, size=<optimized out>)
    at eurorack/braids/macro_oscillator.cc:62
62      eurorack/braids/macro_oscillator.cc: No such file or directory.`
- Texture Synthesizer:
`Thread 17 received signal SIGILL, Illegal instruction.
[Switching to Thread 7632.0xbe4]
0x0000000067e8164b in Clouds::step (this=0x1425e70) at src/Clouds.cpp:103
103     src/Clouds.cpp: No such file or directory.`
- Meta Modulator:
`Thread 1 received signal SIGILL, Illegal instruction.
0x0000000067ec8e04 in warps::QuadratureTransform::AllPassFilter::Init (
    coefficient=<optimized out>, this=<optimized out>)
    at ./eurorack/warps/dsp/quadrature_transform.h:78
78      ./eurorack/warps/dsp/quadrature_transform.h: No such file or directory.`
- Spring Reverb:
`Thread 17 received signal SIGILL, Illegal instruction.
[Switching to Thread 7296.0x1edc]
pffft_zconvolve_accumulate (s=<optimized out>, a=0xe8f0084, b=0xeb02084,
    ab=0xb600294, scaling=scaling@entry=1) at pffft/pffft.c:1867
1867    pffft/pffft.c: No such file or directory.`

That's it, the other modules work just fine and load successfully.

**Comment by AndrewBelt** [comment] 2017-09-27 13:27
Thanks, this is definitely a problem with my use of `-march=core2`. I'll have to come up with a set of optimization flags from this list https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html that offer the most compatibility with CPUs up to 7 years old without reducing performance too much.

**Comment by l33chy** [comment] 2017-09-27 13:35
Yeah that makes sense. The AMD Phenom II CPUs don't support SSSE3, just SSE2 and SSE3.

**Comment by AndrewBelt** [comment] 2017-09-27 13:41
Cool, I will fix this for the next release.

**Comment by Taikakim** [comment] 2017-09-27 14:33
Great, many people use still older computers. Or maybe offer two different
executables for older and latest generation CPUs?

27.9.2017 4.41 ip. "Andrew Belt" <notifications@github.com> kirjoitti:

**Comment by SurrealFunfair** [comment] 2017-09-27 18:50
this is awesome news, Andrew. Thanks so much for taking care about that.

**Comment by AndrewBelt** [comment] 2017-09-27 20:36
Is `-march=nocona` the best middle ground?

**Comment by AndrewBelt** [comment] 2017-09-27 20:48
Fixed with 37926df

**Closed by AndrewBelt** 2017-09-27 20:48 UTC

**Comment by SurrealFunfair** [comment] 2017-09-27 22:30
d/l the latest update (3.2) and still same issues with the same modules.

**Comment by AndrewBelt** [comment] 2017-09-27 22:32
@SurrealFunfair There is a ~2 week delay before this master branch hits the release on the website. It should be fixed if you compile it from source though.

**Comment by SurrealFunfair** [comment] 2017-09-27 22:47
ah.. OK. I would, if I had the skills. Don't even know how to edit/manipulate a prog. 
I'll wait a couple weeks then. Thanks again for fixing this.
