### ISSUE TITLE
Fundamental modules not visible

### ISSUE THREAD

**Issue by saldea88** [VCVRack/Rack#647] opened 2018-01-25 19:56 UTC
OS (if applicable): Windows 7 x86
Version (or "dev" if compiling from source): VCV Rack v0.5.1

I can open the 'Core modules' (all of them), but **not the 'Fundamental modules'** (none of them). This last modules aren't visible, except the lights and plugs of the modules. So they are running, but I'm unable to see what I'm doing. 

![vcv rack modulos invisibles](https://user-images.githubusercontent.com/35814514/35408251-3682b34c-01ed-11e8-8fb5-2c1171b3c229.PNG)

**Comment by AndrewBelt** [comment] 2018-01-25 19:59
Haven't seen this before. What's your graphics card? Have you tried installing the latest drivers?

**Comment by saldea88** [comment] 2018-01-25 20:06
Hi, thanks for the quick answer.

My graphic card is NVIDIA GeForce 7025 / NVIDIA nForce 630a
I haven't tried new drives, thanks for the advice. I'll get back to you
when I've done that.

**Comment by frankframe** [comment] 2018-03-11 14:36
Hi - I downloaded v0.5.1 today and have exactly the same problem : no rails on the GUI and only partial (if any) graphics when loading a module. If I click around in the dark after loading a module, I can pull out cables, but otherwise it looks as described above. 

I'm running Windows7 64bit.

I do have an older graphics card (nvidia GT9600M) -  but I run lots of programs and never experience any  graphics issues - ie Ableton Live, Reaper, Photoshop, Illustrator, After Effects, Blender, Autodesk Fusion, as well as many recent 3rd party DAW plugins.

I tried uninstalling VCV Rack, and then downloaded it again and installed it to a different location (on another drive), but the problem persists.

I checked and apparently have the latest drivers for my graphics card, and like I said I have no graphics failures or unexpected issues otherwise.

Any suggestions appreciated, and thanks for all the hard work that's gone into VCV Rack!

**Comment by AndrewBelt** [comment] 2018-03-11 20:50
By the way, the cause of this is almost surely that your graphics card is not creating framebuffer objects correctly, so if anyone wants to debug, the issue must be between these lines. https://github.com/VCVRack/Rack/blob/master/src/widgets/FramebufferWidget.cpp#L70-L90

**Comment by scrubbingmonkey** [comment] 2018-12-30 11:00
Same issue here 

VCV 0.62
Win 7
nvidia 9550

**Comment by AndrewBelt** [comment] 2020-04-01 04:09
This issue is old and likely obsolete. Comment if issue is still present. Closing.

**Closed by AndrewBelt** 2020-04-01 04:09 UTC
Labels: cause unknown
