### ISSUE TITLE
CC-MIDI and 1-MIDI on the same MIDI device

### ISSUE THREAD

**Issue by phd0** [VCVRack/Rack#996] opened 2018-06-09 20:55 UTC
Operating system(s): Win7
Version of Rack : 0.6.0
All hardware relevant to your issue : Windows midi external keyboard (Maschine MK3 on MIDI mode)

if use the same windows MIDI device on a CC-MIDI and 1-MIDI in the same project : VCVRack crash ...

**Comment by AndrewBelt** [comment] 2018-06-09 20:58
Duplicate of #39, fixed for Rack 0.6.1.

**Closed by AndrewBelt** 2018-06-09 20:58 UTC
