### ISSUE TITLE
Menu improvement: by manufacturer and by modules type

### ISSUE THREAD

**Issue by aasgit** [VCVRack/Rack#353] opened 2017-11-04 20:24 UTC
OS: all
Version: 1.0

First things first: I've just started using VCVRack (today) and it's amazing. Kudos and thank you!

Now, I would like to suggest a menu improvement which I think many would like. Make it possible (behaviour user selectable in preferences) to have the menu as either/both browsable by manufacturers (as is now) and/or by module type (pretty much like Pro Tools does, possibly others too?). The menu could be fashioned something like:

```
------------------------
Arable Instruments
Audible instruments
Autodafe
Befaco
...and so on...
------------------------
EQs
Sequencers
Oscillators
...and so on...
------------------------

```
Perhaps this would only need an extra tag in the module creation to obtain? I don't know, I'm not a coder.

Please and thank you

**Comment by AndrewBelt** [comment] 2017-11-04 20:26
Duplicate of #298

**Closed by AndrewBelt** 2017-11-04 20:26 UTC

**Comment by aasgit** [comment] 2017-11-04 21:25
@AndrewBelt apologies for the duplicate. I probably didn't search enough.
