### ISSUE TITLE
RtApiAlsa error & grainy sound

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#427] opened 2017-11-22 12:57 UTC
Ubuntu 16.04 running KDE

RtApiAlsa::callbackEvent: audio write error, underrun.

When hooking a VCO to the sound module plugin the sound is really grainy, not proper at all.
Should I do a rtaudio_test?

**Comment by AndrewBelt** [comment] 2017-11-22 13:00
Sure, go for it. If you find out anything, post here. Otherwise, I'm closing since this is not reproducable or description enough to solve the problem.

**Closed by AndrewBelt** 2017-11-22 13:00 UTC

**Comment by Cordoha** [comment] 2017-11-22 13:45
Pretty sure I was getting a similar error as #420 

`` RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy. ``

But I think resolved the issues I was having by enabling JACK. I've always used the lowlatency kernel since I work with Ardour. So I have that type of configuration. Restarted Ubuntu, enabled JACK and tried Rack again and the sound is no longer grainy, and I'm not getting `` RtApiAlsa::callbackEvent: audio write error, underrun. `` errors. My scrollback was just getting filled with them.

Now I'm just getting these errors:

`` RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy. ``

`` RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy. ``

`` RtApiAlsa::probeDeviceOpen: unable to synchronize input and output devices. ``

I have a similar spec'd computer as per mentioned in #420. i5, GeForce 950, Steinberg UR22 interface, etc..

**Comment by bontric** [comment] 2017-11-22 14:59
> RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
RtApiAlsa::probeDeviceOpen: unable to synchronize input and output devices.

This is because RtAudio was not compiled with Jack support. You need to manually compile RtAudio with jack support, see #423

**Comment by Cordoha** [comment] 2017-11-22 16:02
> EDIT: Never mind. The new-built librtaudio.so wasn't copied to dep/lib. A quick couple of links and I have ALSA, Jack, and Pulse available in the Audio Driver menu.

librtaudio.so is in dep/lib. How would I compile rtaudio.so with jack support? I need to figure that out.

**Comment by bontric** [comment] 2017-11-22 16:11
I'll write a guide later tonight and add it to the wiki

**Comment by Cordoha** [comment] 2017-11-22 16:12
@bontric Here are some test results from rtaudio_test:
https://github.com/AndrewBelt/rtaudio_test/issues/2

Does compiling still apply?

**Comment by bontric** [comment] 2017-11-22 16:20
Thanks, but this is not necessary. As I said:

> RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.

Indicates that your Audio device is busy. Why? Because Jack is running which means that Alsa can't access it anymore. This is because Rack v0.5 dropped support for Jack (See #82) and RtAudio is compiled without Jack support. This is why you can "add" support  by compiling `RtAudio` manually :wink:

**Comment by Cordoha** [comment] 2017-11-22 16:20
Thank you.

**Comment by bontric** [comment] 2017-11-22 16:37
Hope this helps: https://github.com/VCVRack/Rack/wiki/Add-Support-for-Jack-on-Linux-(dev)

**Comment by Cordoha** [comment] 2017-11-22 16:38
https://github.com/thestk/rtaudio/blob/master/install.txt -- Suggests how to compile rtaudio with JACK support I think.
