### ISSUE TITLE
Feature request: write on top of modules.

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#879] opened 2018-04-03 09:47 UTC
It would be useful to be able to annotate modules for yourself in a patch. Imagine taking a marker and writing on top of the module.

**Comment by AndrewBelt** [comment] 2018-04-03 09:50
Duplicate of #558.

I don't see a use of this with my own patching. Maybe I patch differently than others. But I understand why you might need *expanded* descriptions of things with multiple lines of text. That's why I designed Core Notes. https://vcvrack.com/manual/Core.html

**Closed** 2018-04-03 09:51 UTC

**Comment by Euphorbium** [comment] 2018-04-03 11:52
Not really a duplicate. That one is asking for labels. I am asking for
ability to write wherever. And why is it usefull? It would allow marking
interesting positions of various knobs for example.

**Comment by AndrewBelt** [comment] 2018-04-03 12:00
Like a Grease Pencil in 3D CAD/modeling programs? It makes a bit of sense because whatever you're drawing/writing actually goes into your designs, but for Rack, I'll pass.
