### ISSUE TITLE
v0.5 - Removing module leads to Abort Trap 6 / Segmentation Fault 11

### ISSUE THREAD

**Issue by 2johjoh2** [VCVRack/Rack#475] opened 2017-11-30 13:56 UTC
OS (if applicable): MacOS Sierra 10.12.6
Version (or "dev" if compiling from source): compiled from v0.5

Deleting module (ie : RJ Buttons) by means of backspace leads to program exit with error messages 
First time : Abort Trap 6
Second time : Segmentation Fault 11

**Comment by AndrewBelt** [comment] 2017-11-30 14:23
Duplicate of https://github.com/VCVRack/Rack/issues/378

**Closed by AndrewBelt** 2017-11-30 14:23 UTC
