### ISSUE TITLE
Engine Pause causes CPU 110% (from 20% idle unpaused)

### ISSUE THREAD

**Issue by diimdeep** [VCVRack/Rack#1558] opened 2019-09-21 21:06 UTC
### Details

Operating system: macOS 10.14.4
Rack version: v1.1.4
macbook pro retina 2013, 2 cores
frameRateLimit 30

### Summary
Default patch utilizes 20% CPU, when pressing Engine Pause, CPU utilization spikes to 110%, also same thing happens when audio device not selected (No device)
Large patch for example with 190% CPU utilization, same result, to fixed 110% CPU.

### Expected behaviour
User expect pause feature to reduce CPU usage to idle.

### Steps to reproduce
Launch Rack with default patch.
Press `Engine - Sample rate - Pause` in menu, observe high CPU utilization

**Comment by AndrewBelt** [comment] 2019-09-21 22:09
I can't reproduce this. I get about 8% CPU when the engine is paused.
Do you experience this with the default template patch, or just with custom patches?

**Comment by diimdeep** [comment] 2019-09-21 22:15
Yes, default patch.

**Comment by AndrewBelt** [comment] 2019-09-21 22:20
If you're a developer with Xcode, can you run the Time Profiler in the Instruments app and investigate what the hotspot is?

**Comment by diimdeep** [comment] 2019-09-21 22:23
I'll try.  
Also when audio device not selected (No device) 110% (Rack 1.0.0 same)
Also enabling `CPU meter` adds 60% to CPU. (Rack 1.0.0 not reproduce)

**Comment by diimdeep** [comment] 2019-09-22 07:11
You have to enable to use >= 2 cores to observe this (pause and device not selected)  
Here is 2 cores used
![Screenshot 2019-09-22 at 10 03 36](https://user-images.githubusercontent.com/485713/65383636-f758e180-dd20-11e9-89d8-0921f337a478.png)

Here is 3 cores used
![Screenshot 2019-09-22 at 10 03 12](https://user-images.githubusercontent.com/485713/65383660-35560580-dd21-11e9-804b-a47df6e214bc.png)

That just default patch while paused.


[Rack.trace.zip](https://github.com/VCVRack/Rack/files/3639453/Rack.trace.zip)

**Comment by AndrewBelt** [comment] 2019-09-22 21:17
Fixed in 618454e

**Closed by AndrewBelt** 2019-09-22 21:17 UTC
