### ISSUE TITLE
Problems scrolling to reach entire list of modules

### ISSUE THREAD

**Issue by mwiegand77** [VCVRack/Rack#217] opened 2017-10-12 02:37 UTC
OS (if applicable): OS X El Capitan 10.11.6
Version (or "dev" if compiling from source): 0.3.2

Potentially dumb question: 

When I have all the plugins installed, it won't let me scroll down to reach the Fundamentals.

Is there a keyboard shortcut or another menu I'm missing?

<img width="1392" alt="screen shot 2017-10-11 at 7 29 59 pm" src="https://user-images.githubusercontent.com/32724609/31476485-711b00ca-aebb-11e7-8bd9-fa7582b886f7.png">

**Comment by sbcook0** [comment] 2017-10-12 02:41
This changes with 0.4.0.  The modules are in submenus organized by manufacturer.

**Comment by mwiegand77** [comment] 2017-10-12 02:42
Excellent! Thanks for the quick response.

**Comment by Strum** [comment] 2017-10-12 09:12
beat me to it sbcook0

mwiegand77, it works in the current source code from git, try cloning the repo and compiling it yourself.

the readme file has simple clear instructions on how to do it, it's easy.

some 3rd party module code doesn't work with the latest codebase yet though.

**Comment by AndrewBelt** [comment] 2017-10-12 12:03
Duplicate of #68

**Closed by AndrewBelt** 2017-10-12 12:03 UTC
