### ISSUE TITLE
OS X Menu & Scrollbar behavior inconsistent with platform standards

### ISSUE THREAD

**Issue by Chaircrusher** [VCVRack/Rack#1378] opened 2019-06-21 14:04 UTC
OSX MENU & SCROLLBAR MENU INCONSISTENT WITH PLATFORM STANDARDS

### Summary
Logging this as a feature request rather than as a bug, because it's a nonstandard behavior for OS X, not a program failure.

1. The menu works the same on OS X as it does on Windows & Linux -- you have to click the menu title to drop down the menu. OS X has a standard menu behavior, where once you drop down one menu, horizontal mouse movement over other titles on the menu bar should drop down those menus.

2. OS X has an inverse scroll bar behavior than other platforms.  As reported by commenter 'Nikolozi' on the Create Digital Music blog: "It's is awesome that it's cross platform and open source. And I'm keen to play with it. But one thing though, when I open it on a Mac and the scrollbars are moving in wrong direction and there's no inertia I get so frustrated. Not to mention menu bar is not native at all." 

### Proposed design
Implement platform standard menus and scrollbars.

**Comment by AndrewBelt** [comment] 2019-06-21 14:46
(1) is extremely low priority.

I can't reproduce (2). The scroll direction matches the direction specified by System Preferences > Trackpad > Scroll & Zoom > Scroll direction, and inertia works.

**Comment by AndrewBelt** [comment] 2019-06-30 07:39
Closing since I don't imagine that native menus will ever be implemented. Would require lots of platform-dependent work and modifications to GLFW, so not worth it.

**Closed by AndrewBelt** 2019-06-30 07:39 UTC
