### ISSUE TITLE
Osx unexpected error restarting whilst using Rack 0.5?

### ISSUE THREAD

**Issue by mattfourmat** [VCVRack/Rack#458] opened 2017-11-25 22:17 UTC
is there a fix for this as at the moment my mac crashes because of an unexpected error whilst using vcv.

**Comment by AndrewBelt** [comment] 2017-11-26 05:02
Closing because the issue is not descriptive enough to reproduce.

If you get get a "Send Error Report" box, click "show details" and post and re-open.

**Closed by AndrewBelt** 2017-11-26 05:02 UTC
