### ISSUE TITLE
Cannot scroll module list

### ISSUE THREAD

**Issue by Kinetikai** [VCVRack/Rack#190] opened 2017-10-06 01:59 UTC
OS (if applicable): Mac OS 10.12.6
Version (or "dev" if compiling from source): 0.3.2

I installed Autodafe's module packs and now when right-clicking to add a module the list extends below the screen and there is no way to scroll down, so no way to insert or access the modules that have been cut off.

![screen shot 2017-10-05 at 9 57 20 pm](https://user-images.githubusercontent.com/31858429/31259897-58617f70-aa18-11e7-90ae-c26eaae57f39.png)

**Comment by AndrewBelt** [comment] 2017-10-06 02:01
Duplicate of #68

**Closed by AndrewBelt** 2017-10-06 02:01 UTC
