### ISSUE TITLE
odd division by zero crash

### ISSUE THREAD

**Issue by alto777** [VCVRack/Rack#954] opened 2018-05-13 03:25 UTC
Sifting through the debris of a Rack crash led me to look for division by zero. My module, my thread, my step function. I had no division! I finally figured out that '%' might could be it, and yes, commenting out that line relieved the crashing on module addition.

Guarding that line allows the addition and perfect use of the module. This is the knob, nothing special, it should only give 1.0 to 16.0:

		addParam(ParamWidget::create<Davies1900hBlackKnob>(Vec(58, 187), module, NameMe::RING_SIZE_PARAM, 1.0, 16.0, 7.0));	/* number in ring */

In my step I get its value, which seemed to be (in the modulo expression) causing division by zero. In desperation I tacked on an info call to see:

	ringSize = roundf(params[RING_SIZE_PARAM].value);
	if (ringSize == 0) info("WTF - ringSize _is_ zero!");

The log is littered with "ringSize_is_zero" messages for 6 milliseconds around the time my module is added to the rack.

Imma going to sleep on this but ATM it looks like the step function is called when the param objects are not yet operating. If so, this would have implications beyond the show-stopper I ran into. If not, I do not understand.

**Comment by pronvit** [comment] 2018-05-13 10:44
Yes, the problem is that a module is added to rack and its step() starts being called before its widgets are fully instantiated and have a chance to set parameters to default values.

**Comment by alto777** [comment] 2018-05-13 15:04
Thank you, I see. I think other problems might not be, that is I hope any draw() overriden calls, for example, are done when the widgets are all done. Creating.

So what is the solution? It may be naive, but it seems odd to be calling the step function before use of params[..].value is valid. As I see it this could make for all kindsa interesting behaviour on module instantiation.

On the other hand, it also seems odd to guard uses of params[..].value with fixes to the possibilty that out-of-expected range numbers are retrieved.

On the other hand (I know, third hand) it seems like one could just cut out of the step function at its top for the first, what, 20 milliseconds? Or is there a better way to ensure that all the construction dust has settled, so to speak? I don't see anyone doing anything like this, but I cannot believe that I am the first to be distracted by this timing/startup issue.

a7

**Comment by AndrewBelt** [comment] 2018-05-13 15:45
Use `clamp(x, min, max)` from `math.hpp`.

The Module is added to the rack after the ModuleWidget's ParamWidgets take over, but the last knob on the module may be smoothed by the param smoother. I suppose this could be considered a bug, but it's not a high priority.

**Comment by alto777** [comment] 2018-05-14 13:20
I am not sure you meant to imply that the behaviour only manifests on the last knob. One can "see" knobs come on line, so to speak, over a number of milliseconds in order from first to last. Eight knobs takes 12 milliseconds, after which time all params[...].values become meaningful.

I have not yet found how smoothig enters into it at all. Investigating will motivate some deepr examination of the code, always good to have a reason. I'm not optimistic - I am reading way over grade level, but I usually learn something.

It seems a shame to litter the code and waste even a little time with clampf, since it is only necessary briefly at instantiation. But it certainly fixes things right up!

a7

**Comment by pronvit** [comment] 2018-05-15 11:04
> The Module is added to the rack after the ModuleWidget's ParamWidgets take over, but the last knob on the module may be smoothed by the param smoother. I suppose this could be considered a bug, but it's not a high priority.

No. Module is added to the rack in ModuleWidget::ModuleWidget() but knobs are created and default values are applied in WhateverModuleWidget::WhateverModuleWidget() which is obviously called after the base class constructor.

**Comment by AndrewBelt** [comment] 2018-05-21 20:38
Closing as duplicate of https://github.com/VCVRack/Rack/issues/650 (he discovered it first)

**Closed by AndrewBelt** 2018-05-21 20:38 UTC
