### ISSUE TITLE
graphical interface issue on osx 10.8.5

### ISSUE THREAD

**Issue by mihozu** [VCVRack/Rack#121] opened 2017-09-21 08:50 UTC
I can only see the background of modules, no knobs and no i/o jack or cables...
Do I miss a library?

OS (if applicable): 10.8.5
Version (or "dev" if compiling from source): 0.0

**Comment by AndrewBelt** [comment] 2017-09-21 08:55
Duplicate of #17

**Closed by AndrewBelt** 2017-09-21 08:55 UTC
