### ISSUE TITLE
Crash and unable to start new

### ISSUE THREAD

**Issue by jjdeprisco** [VCVRack/Rack#1467] opened 2019-07-08 21:20 UTC
Noticing lately that after device updates, I often can not return to my old patch without a crash. Right now having difficulty getting back in to VCV to start over.

Macbook specs and logs attached.
[log.txt](https://github.com/VCVRack/Rack/files/3370278/log.txt)
[crash.txt](https://github.com/VCVRack/Rack/files/3370272/crash.txt)
[JD Mac Specs.txt](https://github.com/VCVRack/Rack/files/3370273/JD.Mac.Specs.txt)

**Comment by AndrewBelt** [comment] 2020-04-01 16:35
Issue template was not filled out, closing. If the issue is still present, open an issue and correctly fill out the template.

**Closed by AndrewBelt** 2020-04-01 16:35 UTC
