### ISSUE TITLE
Messy display

### ISSUE THREAD

**Issue by Djack13** [VCVRack/Rack#1038] opened 2018-06-27 14:55 UTC
Linux Mint 18.3:
Version of Rack branch 0.6 compiled from source
and also with Binary 0.6.1 linux 64 bit
Graphic card GeForce GTX 550 Ti using NVIDIA 384.90 driver with openGL 4.5.0

Hello,
An old problem i have since version 0.5. (my issue 1 dec 2017)

When i open a file.vcv, the Rack graphic is ok but all modules graphics are messy.
So i close Rack and re-open it, all modules graphics become ok.
(The autosave file opens without any problem)

![capture du 2018-06-27 16-48-05](https://user-images.githubusercontent.com/34156050/41981975-8eef7c9e-7a2a-11e8-8f4f-d0d164d1b858.png)

Best,

**Comment by AndrewBelt** [comment] 2018-06-27 22:54
Duplicate of #461

**Closed by AndrewBelt** 2018-06-27 22:54 UTC
