### ISSUE TITLE
selecting multiple modules at once by mouse

### ISSUE THREAD

**Issue by the1andonlydrno** [VCVRack/Rack#1808] opened 2020-06-30 10:06 UTC
In most of the programs I use it is possible to "draw" with the mouse an imaginary rectangle while holding the shift key to select all parts inside this rectangle at once. The selected "group" can now be really grouped, moved, copied, deleted and so on. It would be great to have this workflow in VCV Rack.

**Comment by AndrewBelt** [comment] 2020-06-30 10:21
This is a duplicate of at least one issue.

**Closed by AndrewBelt** 2020-06-30 10:21 UTC

**Comment by the1andonlydrno** [comment] 2020-06-30 10:23
I searched but haven't found any, sorry

**Comment by AndrewBelt** [comment] 2020-06-30 10:45
There are *several* duplicates and related issues.
https://github.com/VCVRack/Rack/issues/307
https://github.com/VCVRack/Rack/issues/977
https://github.com/VCVRack/Rack/issues/1225
https://github.com/VCVRack/Rack/issues/1472
