### ISSUE TITLE
can't click on "website", "manual", "browse directory" items.

### ISSUE THREAD

**Issue by phdsg** [VCVRack/Rack#476] opened 2017-11-30 21:26 UTC
OS (if applicable): Win-7 64
Version (or "dev" if compiling from source): dev

the right menu box part (with the tags and links) hides on leaving the middle part,
so you can't actually click the links.

**Comment by AndrewBelt** [comment] 2017-11-30 21:30
Duplicate of https://github.com/VCVRack/Rack/issues/421

**Closed by AndrewBelt** 2017-11-30 21:30 UTC
