### ISSUE TITLE
multichannel audio interfaces with more than 8 channels

### ISSUE THREAD

**Issue by srizzi88** [VCVRack/Rack#364] opened 2017-11-08 00:53 UTC
OS (if applicable):
Version (or "dev" if compiling from source):

I have a question/request. My audio interface has 20 output channels, 8 of them ADAT that I use to communicate with expert sleepers hardware. My ADAT channels are numbered 13 to 20. I want to route signals from Rack to my eurorack devices, but could not find a way to access channels 13 to 20 from the Rack audio device.

Is there a way to do that? If not, I would like to request that feature, which I think will be valuable for a lot of future users.

Thanks.

**Comment by AndrewBelt** [comment] 2017-11-08 00:57
Duplicate of #82

**Closed by AndrewBelt** 2017-11-08 00:57 UTC
