### ISSUE TITLE
Query re: multiprocessing

### ISSUE THREAD

**Issue by Lugia909** [VCVRack/Rack#823] opened 2018-03-20 05:13 UTC
Running Win10 x64 on an HP Z620, dual Xeon E5-2660s @ 2.2 GHz w/ 32 MB RAM. Audio via RealAudio, internal audio (stereo) out in use.

While working on a patch with a large amount (ie: upward of 40) of modules, I'm noticing a lot of weird timing hiccups and glitches w/ 0.5.1. Rack's buffer is set to 4096, 44.1 kHz sample rate. The glitchy behavior seems to be severe after adding some sample-based drum modules (Autodafe) to the rack.

After clearing out the issue once, it started to reoccur once the sample-based modules were added to the rack again. This time, I had the Rack window resized in such a way so that I could watch my CPU metering across all 16 cores, and noted that while one core was totally maxed out during the glitchy behavior, the rest seemed to only jump into activity as per usual operation for the OS, etc. Since I do some rather processor-intensive work in Live 10, I'm pretty aware of this machine's capabilities when it's running something multiprocessor-aware, but it looks to me like Rack 0.5.1 doesn't seem to know about the other 15 cores at its disposal. Is multiprocessing not enabled for Rack, or is this something not enabled in 0.5.1 but slated for later? Or is something not properly set in my build of 0.5.1? Either way, I'm quite sure I'm nowhere near this machine's performance ceiling when this is going on.

**Comment by AndrewBelt** [comment] 2018-03-20 05:20
Duplicate of #195

**Closed by AndrewBelt** 2018-03-20 05:20 UTC

**Comment by AndrewBelt** [comment] 2018-03-20 05:24
The layman description is: You can't just slap "multithreading" on a program and call it a day. It's easy in multitrack editors because you can process each track's large buffer as an isolated task. Rack "knows" about the other 15 cores, but there's no easy way to use them for a modular synthesizer algorithm. There's no magic switch I can turn to "enable" other threads.
