### ISSUE TITLE
Probleme visibility files in the VCV explorer (open)

### ISSUE THREAD

**Issue by Dom2Dom99** [VCVRack/Rack#1425] opened 2019-06-29 09:18 UTC
### Details
nothing appears in the explorer selection box, despite patchs are in folder.

Operating system: windows 10
Rack version: v1.1.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary
if i write *.* in the name file box, all patch re-appears, and i can select to load.

**Comment by mastazi** [comment] 2019-06-29 11:05
I have the same issue whenever I try to open a patch, but in my case, writing . in the filename field does not solve the problem. Also, trying to use the filetype dropdown, besides the first line (which is the default vcv filetype) all the other lines are seemingly random UTF-8 characters as you can see [here](https://imgur.com/a/lTM0Bac)

**Comment by MaZe6K** [comment] 2019-06-29 13:21
Same here on Windows 7

**Comment by AndrewBelt** [comment] 2019-06-29 17:10
Duplicate of many issues

**Closed by AndrewBelt** 2019-06-29 17:10 UTC
