### ISSUE TITLE
New modules placed at the random spot after creation.

### ISSUE THREAD

**Issue by nnbveh** [VCVRack/Rack#1806] opened 2020-06-30 06:39 UTC
So i can click with the right button at some empty spot, find the module and press on it, but instead of being place were i've clicked it might appear at the very top of all my modules, or on the right side, or anywhere it wants really...if i repeat, and place another instance of the same module or any other module, the place changes randomly again...this just don't make much sense to me, i have to scroll around every time and then place the new modules where i want them to be.

Happened on every version of Rack i've used and still does. I'm on Mac OS 10.5.5 currently, macbook pro 16.

### Details

Operating system and version:
Rack version (vX.Y.Z):
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

**Comment by AndrewBelt** [comment] 2020-06-30 06:43
Sort of duplicate of https://github.com/VCVRack/Rack/issues/1415.
In the future, you need to fill out the issue form or your issue will be closed.

**Closed by AndrewBelt** 2020-06-30 06:43 UTC
