### ISSUE TITLE
isConnected switches between true and false per frame

### ISSUE THREAD

**Issue by NicolasNeubauer** [VCVRack/Rack#1338] opened 2019-06-15 23:12 UTC
### Details

Operating system: Windows 10
Rack version: v1 latest

```
void Baseliner<NUM_COLUMNS>::process(const ProcessArgs &args) {
  ...
  INFO("entering loop");
  for (int i = 0; i < NUM_COLUMNS; i++) {
	if (i==0)
		INFO("checking gate %d, status %d", i, inputs[GATE1_INPUT + i].isConnected() ? 1 : 0);
```
full context here: https://github.com/NicolasNeubauer/noobhour_modules/commit/852eb6ab1087ed7c5d012affdfc74b4f83e7ae06 

### Expected behavior
(input is connected)
```
[11.080 info src/Baseliner.cpp:117] entering loop
[11.080 info src/Baseliner.cpp:124] checking gate 0, status 1
[11.080 info src/Baseliner.cpp:117] entering loop
[11.080 info src/Baseliner.cpp:124] checking gate 0, status 1
[11.080 info src/Baseliner.cpp:117] entering loop
[11.080 info src/Baseliner.cpp:124] checking gate 0, status 1
[11.080 info src/Baseliner.cpp:117] entering loop
[11.080 info src/Baseliner.cpp:124] checking gate 0, status 1
```

### Actual behavior
(input is also connected)
```
[11.080 info src/Baseliner.cpp:117] entering loop
[11.080 info src/Baseliner.cpp:124] checking gate 0, status 0
[11.080 info src/Baseliner.cpp:117] entering loop
[11.080 info src/Baseliner.cpp:124] checking gate 0, status 1
[11.080 info src/Baseliner.cpp:117] entering loop
[11.080 info src/Baseliner.cpp:124] checking gate 0, status 0
[11.080 info src/Baseliner.cpp:117] entering loop
[11.080 info src/Baseliner.cpp:124] checking gate 0, status 1
```
getVoltage also drops to 0 along with isConnected. Connecting from a different module doesn't change things (started with Fundamental LFO-1, but get same behaviour with VCO-1, SEQ-3, ...)

**Comment by NicolasNeubauer** [comment] 2019-06-15 23:17
full context here https://github.com/NicolasNeubauer/noobhour_modules/commit/852eb6ab1087ed7c5d012affdfc74b4f83e7ae06

**Comment by AndrewBelt** [comment] 2019-06-16 09:13
I can't reproduce this. I get nothing but
```
[4.979 info src/Baseliner.cpp:117] entering loop
[4.979 info src/Baseliner.cpp:124] checking gate 0, status 1
[4.979 info src/Baseliner.cpp:149] checking gate signal 4.000000
[4.979 info src/Baseliner.cpp:187] using signal
[4.979 info src/Baseliner.cpp:206] channels: 0
[4.979 info src/Baseliner.cpp:117] entering loop
[4.979 info src/Baseliner.cpp:124] checking gate 0, status 1
[4.979 info src/Baseliner.cpp:149] checking gate signal 4.000000
[4.979 info src/Baseliner.cpp:187] using signal
[4.979 info src/Baseliner.cpp:206] channels: 0
[4.979 info src/Baseliner.cpp:117] entering loop
[4.979 info src/Baseliner.cpp:124] checking gate 0, status 1
[4.979 info src/Baseliner.cpp:149] checking gate signal 4.000000
[4.979 info src/Baseliner.cpp:187] using signal
[4.979 info src/Baseliner.cpp:206] channels: 0
```
etc. when the first gate input is patched.

**Comment by AndrewBelt** [comment] 2019-12-03 22:14
Closing as unreproducable.

**Closed by AndrewBelt** 2019-12-03 22:14 UTC
