### ISSUE TITLE
Midi Learn (Feature Request) 

### ISSUE THREAD

**Issue by Dultzo** [VCVRack/Rack#504] opened 2017-12-09 07:27 UTC
OS (if applicable):
Version (or "dev" if compiling from source):
Wondering if this is planned for future? Would love to be able to quickly assign params to physical knobs and had my eye on Bastl '60 knobs' which seems like it could be pretty great partnered with VCV..

**Comment by Flowstoner** [comment] 2017-12-09 08:11
duplicate of #50

**Closed** 2017-12-09 12:12 UTC
