### ISSUE TITLE
auto scroll for modules menu

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#155] opened 2017-09-30 12:37 UTC
OS (if applicable): Yosemite and High Sierra
Version : 0.3.2

i 'm testing new modules ( around 20 new modules) from  [autodafe](https://www.autodafe.net/virtual-instruments/vcv-rack-modules.html) but the modules menu is too big for my screen now ;-) so i can access to all modules

**Comment by AndrewBelt** [comment] 2017-09-30 12:41
Duplicate of #68

**Closed** 2017-09-30 12:41 UTC

**Comment by nay-seven** [comment] 2017-09-30 12:50
ok, sorry
