### ISSUE TITLE
Localization Problem

### ISSUE THREAD

**Issue by odahan** [VCVRack/Rack#703] opened 2018-02-11 14:03 UTC
OS (if applicable): W10
Version (or "dev" if compiling from source): 0.5x (latest)

There is a global bug about localization and non-English character set support. At least for French.
This problem can be seen in many places in the application :

- File names with French character are not displayed correctly (little exotic symbols appear instead of regular letters such as ç à é è and so on)
- Module maker names, module names are not sorted correctly, lowercase letters are put after the list of uppercase letters, sorting in French is not case sensitive (it can be in some other languages). 
- Notepad does not manage correctly non-English characters
- ...

It seems obvious VCV is not taking into account what is called "culture information" in Windows (and equivalent concept in other OS).
Therefore it is more a global bug impacting all the application than a feature request (Notepad problem has been classified as a feature request for example but is belonging to this global problem).
VCV is a fabulous app used in many countries, good culture support is an important point.

**Comment by AndrewBelt** [comment] 2018-02-11 14:17
Actually, none of these bullet points are localization issues but Unicode handling issues with my `std::string` handling and the Blendish dependency. The ordering is done in ASCII but will be fixed when the Unicode issues are fixed.

As far as I know, the only localization needed in Rack is translated languages (of course) which I can't afford to support, and decimal points in the future tooltip displays: "1.000" vs "1,000". No dates are used, and nothing else to my knowledge is needed.

**Comment by AndrewBelt** [comment] 2018-02-23 11:59
Going to mark as duplicate of #436

**Closed by AndrewBelt** 2018-02-23 11:59 UTC

**Comment by odahan** [comment] 2018-02-23 13:37
#436 is very old and have never been solved and was marked as closed.  Not solved problems should stay opened hence my own confusion.

**Comment by AndrewBelt** [comment] 2018-02-23 13:38
It was marked as closed? Now I'm even more confused.
