### ISSUE TITLE
Build broken for MacOS

### ISSUE THREAD

**Issue by seclorum** [VCVRack/Rack#512] opened 2017-12-10 17:14 UTC
````
 master 6787867 clarified comment about sizes (#510)
seclorum@devbox:~/Documents/Research/synth/Rack
$ make
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/gui.cpp.o src/gui.cpp
src/gui.cpp:450:3: error: use of undeclared identifier 'glfwGetWindowContentScale'
                glfwGetWindowContentScale(gWindow, &pixelRatio, NULL);
                ^
1 error generated.
make: *** [build/src/gui.cpp.o] Error 1

````

**Comment by cschol** [comment] 2017-12-10 18:34
Duplicate of #494 . Please see that issue for how to resolve it.

**Closed** 2017-12-10 19:27 UTC
