### ISSUE TITLE
Detect bad autosave file

### ISSUE THREAD

**Issue by djpeterso23662** [VCVRack/Rack#467] opened 2017-11-28 12:21 UTC
OS (if applicable): all
Version (or "dev" if compiling from source): dev

Could Rack detect if the previous Rack run lead to a crash, and ask the user if he or she would like to start with an empty autosave.vcv instead?

**Comment by antoniotuzzi** [comment] 2017-11-28 12:45
duplicate of https://github.com/VCVRack/Rack/issues/426

**Comment by AndrewBelt** [comment] 2017-11-28 13:16
Actually that issue deals with crashing during unserialization, but there are other reasons it may crash after loading an autosave.vcv file, such as a bad audio driver.

It is unclear to me how to determine whether an autosave file crashed Rack, other than maybe the following algorithm.
- Load settings.json
- write settings.json with a key  `"autosave_failure": true`
- load autosave.vcv
- all further writes to settings.json will not include that key.

- In the first step, if autosave_failure is true from the loaded settings.json file, ask to delete autosave.vcv in a dialog box.

**Comment by naclander** [comment] 2017-11-29 22:51
I would recommend moving autosave.vcv to autosave.vcv.bad or something similar. In case the user wants to manually restore the save file by hand.

**Comment by AndrewBelt** [comment] 2017-11-30 01:04
Maybe that would be more straightforward than the `"autosave_failure"` key. The algorithm would save `autosave-tmp.vcv`, delete `autosave.vcv`, wait 15 seconds (the normal autosave interval), save `autosave.vcv`, and delete `autosave-tmp.vcv`. I think that does it.

**Comment by cschol** [comment] 2018-01-07 15:58
Can the same algorithm be applied to the `settings.json` file? I had a couple of instances now where crashes let to a corrupt `settings.json` file. The effect is a totally messed up GUI with what looks like ultra-low resolution. I had to delete the `settings.json` file to get it to work again.

**Comment by AndrewBelt** [comment] 2018-01-15 05:02
Fixed with 575e4df

**Closed by AndrewBelt** 2018-01-15 05:02 UTC
