### ISSUE TITLE
Please fix the file name rewrite after crash bug!

### ISSUE THREAD

**Issue by LollyWater** [VCVRack/Rack#1932] opened 2021-08-18 03:51 UTC
This is such a frustrating bug!!! I have lost much time and many patches!

The bug:

Open a patch. Save the patch. Open a new or different patch. Rack crashes before you have a chance to save the latter. Rack opens with the current, unsaved patch, yet retains the former patches file name. Go to save your patch, and you have now written over the former patch.

Being aware of this bug sometimes helps negate a force of habit, however, saving documents frequently should not be punished.

To a non-software dev seems like an easy fix: Rename the file after a crash, or correctly remember an unsaved patches file name.

**Comment by jpnielsen** [comment] 2021-08-18 07:31
https://github.com/VCVRack/Rack/issues/1702

**Comment by AndrewBelt** [comment] 2021-08-18 12:48
Duplicate of https://github.com/VCVRack/Rack/issues/1559

**Closed by AndrewBelt** 2021-08-18 12:48 UTC
