### ISSUE TITLE
1.1.6 Crash OSX 10.15.7

### ISSUE THREAD

**Issue by zmixnyc** [VCVRack/Rack#1895] opened 2021-02-26 14:22 UTC
![Screen Shot 2021-02-26 at 09 03 03](https://user-images.githubusercontent.com/48537231/109311253-938af000-7813-11eb-9c5b-9ce9223e55cd.jpg)

### Details

Operating system and version: OSX 10.15.7
Rack version (vX.Y.Z):1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Radeon Sapphire Pulse RX 580 8GB

### Summary

Downloaded and unzipped Rack 1.1.6, launched it and it crashed.

LOG ATTACHED

**Comment by zmixnyc** [comment] 2021-02-26 16:24
Apparently was permissions based, the popup asking for permission to access the keyboard  did not appear until 4th attempt to launch.

**Comment by AndrewBelt** [comment] 2021-02-26 23:47
Duplicate of #1623

**Closed by AndrewBelt** 2021-02-26 23:47 UTC
