### ISSUE TITLE
kernel_task requests 200% CPU when I use the VCV Rack

### ISSUE THREAD

**Issue by Johnnatannobre** [VCVRack/Rack#1272] opened 2019-05-10 13:58 UTC
kernel_task requests 200% CPU when I use the VCV Rack even with the active low-resolution mode.

Operating system(s):
RACK 0.6.2c
OS 10.14.4 (18E226)
MacBook Pro (Retina, 13-inch, Late 2013)
2,4 GHz Intel Core i5
8 GB 1600 MHz DDR3
Intel Iris 1536 MB

**Comment by AndrewBelt** [comment] 2019-05-10 14:14
Duplicate of many previous issues. Not a concrete bug report.

**Closed by AndrewBelt** 2019-05-10 14:14 UTC
