### ISSUE TITLE
Crashes + wrong title in auto opened patch on relaunch

### ISSUE THREAD

**Issue by Marvellus** [VCVRack/Rack#1559] opened 2019-09-22 09:46 UTC
Hi,

Awesome work on the VCV Rack software, thank you so much for creating it!

I have some issues with crashing and filenames from autosaves though.

For example, I start working by opening a patch file named 'patch a', do a "save as" as 'patch b', work some more on it until 'patch b' crashes. When I reopen the app, I do get my autosaved patch B, which is awesome. However, its name is 'patch a'! So when i do a save, it overwrites the wrong patch file.

Hope you can solve this, thanks!

### Details

Operating system:
Rack version: vX.X.X
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

**Comment by Marvellus** [comment] 2019-10-01 19:47
Just wondering, as a GitHub n00b, will this be picked up somehow?

**Comment by ROGAVKA** [comment] 2019-10-29 19:06
Same issue on Windows 10 here. Happens very often. 
In my case, I'm working on patch X then open patch Y which crashes immediately. I launch Rack again and get patch Y opened, but filename is X (and if I save it overwrites X) 
I suppose VCV crashes for me are related to the usage of Bridge, but I'm not sure if "wrong filename" problem is due to Bridge also or due to a crash itself.

**Comment by ROGAVKA** [comment] 2019-12-21 15:35
I can confirm now that this bug is unrelated to Bridge (i abandoned Bridge and still find myself at risk of overwriting paches). Must be something with crash handling.

**Comment by AndrewBelt** [comment] 2021-01-24 23:45
Identified source and fixed in Rack v2 branch (currently private) about 2 weeks ago. Will be included in the 2.0 release.

**Closed by AndrewBelt** 2021-01-24 23:45 UTC
