### ISSUE TITLE
File|Open and Preset|Open not reliably displaying existing files

### ISSUE THREAD

**Issue by technochitlin** [VCVRack/Rack#1435] opened 2019-06-30 20:19 UTC
### Details

Operating system: Windows 10Pro 1903
Rack version: v1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
MSI Radeon RX480 8Gb
Focusrite Scarlett 6i6
### Summary
When I try to open a file or load a preset, no files are displayed in the dialog box even though files exist in the folder.
### Steps to reproduce
I cannot reliably reproduce this. Sometimes available files are displayed, sometimes they are not. Sometimes if I use File|New or reload the program, files are displayed and available. I can always load a patch by clicking on it in the folder, but many times if I go to open another patch using the File|Open menu
[log.txt](https://github.com/VCVRack/Rack/files/3343299/log.txt)
![vcv1](https://user-images.githubusercontent.com/737753/60401640-4a6c2f80-9b4a-11e9-82b4-111bdbf7960c.png)
![vcv2](https://user-images.githubusercontent.com/737753/60401642-4cce8980-9b4a-11e9-91ad-a6cacd254233.png)
![vcv3](https://user-images.githubusercontent.com/737753/60401645-50faa700-9b4a-11e9-9c65-1ee0de195139.png)

, no files are displayed.

**Comment by AndrewBelt** [comment] 2019-06-30 20:22
Duplicate of https://github.com/VCVRack/Rack/issues/1407, we already have 7 issues about this.

**Closed by AndrewBelt** 2019-06-30 20:22 UTC
