### ISSUE TITLE
Don't unnecessarily limit MIDI message length and prohibit sysex sends

### ISSUE THREAD

**Issue by wipu** [VCVRack/Rack#1703] opened 2020-02-07 19:11 UTC
### Summary

Currently midi messages are limited to 3 bytes.

`include/midi.hpp` contains `assert(size <= 3);`

`src/rtmidi.cpp` has the following comment:

`// Users have reported that some MIDI devices can send messages >3 bytes. I don't know how this is possible, so just reject the message.`

Most messages are indeed 1-3 bytes long, but for example sysex messages can be indefinitely long. Please see [a midi.org summary](https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message) of the message syntax.

_So, the lenght limit is against MIDI specifications and completely unnecessary._

### Motivation

I'm writing a plugin that drives an external synthesizer (Commodore 64) and will send its control commands as sysex messages. The length of those messages is some tens of bytes and they will be sent 50 times per second (a typical refresh rate in a SID engine). The only way to achieve this bandwidth is to use sysex messages. Other message types would waste too much bandwidth.

The underlying rtmidi library doesn't limit (as it shouldn't) the length of midi messages so there is no reason for Rack to do it either.

### Proposed design

Just stop limiting the length. If there is code that relies on the length being <=3, please remove the assumption and ask the message instead for its actual length.

**Comment by wipu** [comment] 2020-02-07 19:19
I'm ok with keeping the current Message struct as is and adding another alongside, for example RawMessage. As long as it's possible to send longer messages.

**Comment by AndrewBelt** [comment] 2020-02-07 22:41
Duplicate of https://github.com/VCVRack/Rack/issues/1433

**Closed by AndrewBelt** 2020-02-07 22:41 UTC
