### ISSUE TITLE
Black rack and invisible modules, how to fix?

### ISSUE THREAD

**Issue by aphexboi** [VCVRack/Rack#916] opened 2018-04-13 13:52 UTC
Looks like this:
http://prntscr.com/j4r7nq

I tried reinstalling, I tried deleting and changing the name of temp folder and reinstalling, but nothing seem to work. How do I fix this?

OS Windows vista and the newest version from the site.

**Comment by AndrewBelt** [comment] 2018-04-13 16:47
Duplicate of #323

**Closed by AndrewBelt** 2018-04-13 16:47 UTC
