### ISSUE TITLE
Two very small issues with the new submenu system

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#165] opened 2017-10-02 15:06 UTC
Version (or "dev" if compiling from source):dev

1) I have released some modules in forms of different "Packs". The result is they generate 3 different rows in the menu system. I think it would be simpler to "group" every "pack" under the same dev (so, as an example, I would only have one row called "Autodafe", then subgroups/submenus for my three packs, each one with its modules.

2) If a folder containing incompatible plugins is found (in the example I have a 0.3.2 module), a blank row is generated with a submenu structure (with a "Browse Directory" inside and nothing else)

see below:

![module-menu-40](https://user-images.githubusercontent.com/16060683/31084078-c36e4d52-a793-11e7-8bd3-0a14604eccb6.png)

**Comment by AndrewBelt** [comment] 2017-10-02 15:12
(1) is too tedious for the user, just use the two-level hierarchy.
(2) is probably a serious bug where plugins are being half-way initialized, thanks!

**Comment by antoniograzioli** [comment] 2017-10-02 15:26
1) ok up tp you to decide, I simply don't want to hijack the whle menu with my "packs" :-)
2) good!

**Comment by AndrewBelt** [comment] 2017-10-02 15:28
I think three or even 10 plugins would be reasonable! Especially with scroll support. As long as they're useful with a few modules in each one, people will be happy with lots of plugins.

**Comment by antoniograzioli** [comment] 2017-10-02 19:37
regarding question n.1) again: maybe if I just use the same plugin "slug" and "name" in the code two of my release could just appear as "merged" into one? 
as an example, I released my "Blank Panel" as a separate download (with separate dll and dynlib), there's no actual need to keep it separate from my other modules...

**Comment by AndrewBelt** [comment] 2017-10-03 01:18
The slugs are meant to define a clear one-to-one relationship between folders and how users will access them in the Add Module menu. Imagine if your filesystem supported tricks like this. Then everyone would be confused by mysterious special cases when they navigate the folder structure. If there is a different item in the Add Module dropdown, people will expect it to have its own folder, and vise versa. Using the same slug on two different plugins is undefined behavior and should fail to load all but one in future versions of Rack.

**Comment by AndrewBelt** [comment] 2017-10-03 01:21
If it becomes a need in the future, I could make a 1-to-1 relationship between the folder hierarchy in the plugins/ folder and the Add Module menu, but this becomes messy (e.g. Kontakt sample sets) and requires Rack to search for slugs across a folder structure when a patch file demands a particular slug. Would break a lot of compatibility with sharing patches.

**Comment by zutra** [comment] 2017-10-05 22:44
Hi, Im new here and I'm using RACK for a few days. Today I installed the new version 0.3.2 (mac) and also installed new plugins, now I can't see a whole list.
Can someone help me?

![screen shot 2017-10-05 at 18 54 20](https://user-images.githubusercontent.com/32556173/31255852-71da2b04-aa05-11e7-8b0d-5cd60b741cdf.png)

**Comment by AndrewBelt** [comment] 2017-10-05 22:46
@zutra Duplicate of #68. Fixed and will be included in Rack v0.4.0

**Comment by zutra** [comment] 2017-10-05 23:03
I'm not a programmer so I think it's best to wait for the new version. :)
Thanks for the quick reply and thanks for the Rack, sounds really great.

**Comment by AndrewBelt** [comment] 2017-11-09 20:16
Closing since this is irrelevant after the recent changes.

**Closed by AndrewBelt** 2017-11-09 20:16 UTC
Labels: bug
