### ISSUE TITLE
Change existing cable color

### ISSUE THREAD

**Issue by mkruselj** [VCVRack/Rack#569] opened 2017-12-30 09:38 UTC
OS (if applicable): any
Version (or "dev" if compiling from source): any

Simple feature request as stated in the title!

Plus, having more cable colors would be nice to have, too!

**Comment by LKHSogpit** [comment] 2018-01-03 22:31
Only recently discovered cables are ordered sequentially when you select a new one. now my OCD is telling me to use different colours for the functions. 

It might have to be a button combo such as ALT and mousewheel I feel as normal scrolling would be stopped if you went past a cable on the way down/across. This would be very useful. 

How about a config file for the colours though also if you connect to a gate/trig one colour or v/oct another. Having this set already and not worrying about the most used colours would be a quicker way if you like things to look a certain way.

**Comment by mkruselj** [comment] 2018-01-03 22:59
Actually I'd satisfy with just right-clicking on the cable. I'd personally like to steer away from config files.

**Comment by LKHSogpit** [comment] 2018-01-04 00:02
But if it was a selectable option in a menu would you select it? Text editor and number input!

**Comment by mkruselj** [comment] 2018-01-04 07:34
I'd select it, yeah.

But I don't understand why would I need to find a space with no cable? My request is to change the color of EXISTING cable, once it's been created, without removing it then recreating it.

**Comment by LKHSogpit** [comment] 2018-01-04 11:56
Because what would be under the mouse? A cable, Right click functions for the context menu, Scrolling functions to scroll up/down and left/right when you shift. If you are scrolling and the mouse goes passed a cable the scrolling is going to stop dead and scroll trough the colours instead. If you right click on what you think is an empty spot and it so happens to be a cable there particularly a black one and you just happen to use a lower opacity you're not opening the context menu you're changing the colour of the cable.

That's why I'm expanding on your idea for there to be another key combo (Alt) to select the colour. Same thing with the Default reset for knobs that should really be a key combo too. I've not reset anything mistakenly but I could see myself doing it at some point.

**Comment by mkruselj** [comment] 2018-01-04 12:03
Gotcha, so basically you're saying it should be BOTH mousewheel AND right-click context menu? Sounds good to me.

Also, regarding knob reset, I think that's fine to be on double-click... one hand on MIDI controller and the other on mouse, forcing the user to remove the hand from MIDI controller just to reset the knob is not good UX IMHO (even thought Ctrl+click to reset knobs seems to be very often used, I'm not a fan of it)...

**Comment by LKHSogpit** [comment] 2018-01-04 12:34
NO not saying that at all. One or the other in conjunction with another key is what i'm saying. Not a fan of double click ctrl click always makes sense (ctrl left click!.) Most mice after long term use/near the end of their life will double click automatically, on a single click get senile like that.

Full midi with a Nektar map! I wish...

**Comment by mkruselj** [comment] 2018-01-04 12:36
Again, please read above use case. When I have one hand on MIDI controller, I don't want to be bugged to remove my hand just to hold Ctrl in order  to reset a control. So with that in mind, either left click double-click, or the current right-click are a much better solution. Ctrl+click makes only sense if you're constantly at your keyboard and don't ever use MIDI controllers (which many people do)!

**Comment by LKHSogpit** [comment] 2018-01-04 13:11
I'm constantly at my screen keyboard and midi controllers. Some are out of reach of each other but the main ones when programming are all in touching distance of each other if I need to bring the keyboard/mouse I do its wireless. There is a program for Windows X-Mouse Button Control if you have extra buttons on your mouse it remaps them!

**Comment by mkruselj** [comment] 2018-01-04 13:12
That's additional pain in the ass to set up, why not just use what the mouse already has and is default :D

**Comment by LKHSogpit** [comment] 2018-01-04 13:30
I sense you're being somewhat lazy. So everyone else should suffer right....

**Comment by mkruselj** [comment] 2018-01-04 13:33
Not lazy, it's a matter of workflow being slowed down. Hence, options are good. I'm fine with the current right-click to default, it could also be a left double-click, also fine by me. It could also be Ctrl+click, but only if one of previous two are still present and available for other people to use.

**Comment by LKHSogpit** [comment] 2018-01-04 14:55
Yeah scripts and customisation like Reaper might be the way to go alright. 

But just have to point out your midi keyboard is like 12cm's away from your ctrl key!! You won't install and use an easy to set up program to emulate keyboard strokes from your mouse out of the hassle, Very lazy mate... It would have taken less time you took to reply to this and the last post to have that functionality.

**Comment by mkruselj** [comment] 2018-01-04 16:08
-_-

Again, it's about _speed of workflow_, not laziness. When you're playing the keyboard, you don't need distractions.

So yeah I don't need to go for Ctrl, because VCV right now uses right-click to reset, that's fine by me. I would be bummed if that were removed and went to ctrl+click instead, though.

**Comment by LKHSogpit** [comment] 2018-01-04 16:12
I'm all for workflow but it will take all of 1 second your move your hand less if you're quick.

**Comment by n6smith** [comment] 2018-01-15 05:19
Just an additional note to add to this. Due to a number of Dark GUIs being used in plugins, the Grey colored cables are often very hard to see even at full opacity. Alternative colors would be most welcome.  :)

**Comment by ndrspcfd** [comment] 2018-01-15 17:39
I thinkk the commit from a few hours ago ( https://github.com/VCVRack/Rack/commit/b51e380e3684076229725c83d70e93f25bad16c8 ) offers a splendid way of improving cable visibility - hats off! It improves over the initial suggestion here in that you can set your cables quite transparent but still be able to find the other end easily, with the added advantage that highly transparent cables don't get in the way of seeing the modules either. Brilliant!

**Comment by mkruselj** [comment] 2018-01-15 17:45
This request wasn't much about visibility, but organization. By strictly deciding which cables you want in which colors, you can organize the rack more easily... IMHO at least.

**Comment by ndrspcfd** [comment] 2018-01-15 17:55
Oh, I see! Mouse*wheel* over ... to permanently change it.. I read it as "mouse over cable changes its color" probably because I often get problems seeing where I put the other end of the cable, when I've forgotten what I did with it. Oh well, it solves *my* problem anyway! ;-)

**Comment by n6smith** [comment] 2018-01-15 18:44
"This request wasn't much about visibility, but organization." Oh absolutely. I just 'tacked' my idea on as it would be basically related to the whole suggested change... and didn't intend it to be a hijack of any sorts. :)

**Comment by LKHSogpit** [comment] 2018-01-15 20:06
Often remove a cable to see the routing of it might be handy having a key that could show connected modules of that cable all the way through the chain. Press keyboard key and mouse over. 

There must be a way to change the cable colours yourself.

**Comment by AndrewBelt** [comment] 2019-12-03 22:38
I'm renaming this issue because I disagree with the proposed UI action but not the functionality itself.
- Mouse wheel is taken. It scrolls the rack.
- Right click is taken. It disconnects the cable.

Perhaps while dragging a cable, an action can be done which cycles the color.

**Comment by mkruselj** [comment] 2019-12-03 23:02
That would help, but we should also be able to easily change the color after the connection has been made.

Ctrl+right click would've been good for this, that PR should've been merged IMHO :)

**Comment by AndrewBelt** [comment] 2019-12-04 15:23
Closing as duplicate of https://github.com/VCVRack/Rack/issues/394

**Closed by AndrewBelt** 2019-12-04 15:23 UTC
