### ISSUE TITLE
1.1.0 in Windows can't open .vcv files (first launch only)

### ISSUE THREAD

**Issue by midiguru** [VCVRack/Rack#1416] opened 2019-06-28 03:57 UTC
### Details

I've just downloaded 1.1.0 for Windows. The File Open dialog shows no files, even though there are .vcv files in the folder. However, when I close Rack and open it again, the dialog box shows the files, and loading a patch works properly.

Operating system: Windows 7 64-bit
Rack version: v1.1.0

**Comment by FunkybotsEvilTwin** [comment] 2019-06-28 04:08
Happening frequently, but seemingly randomly here. I've got a VCV Rack subfolder under My Documents on Windows 10x64, and when I click Open, it's showing up as empty half the time. 

Possibly relevant: the File Type dialog box shows .vcv (as expected), but if you click on that to see the other options in the menu, the other options are written in Asian characters. Never saw that before.

**Comment by AndrewBelt** [comment] 2019-06-28 04:26
Duplicate of https://github.com/VCVRack/Rack/issues/1407

**Closed by AndrewBelt** 2019-06-28 04:26 UTC
