### ISSUE TITLE
make install + debug + launch Rack won't unzip the dist

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1237] opened 2019-03-27 10:31 UTC
Operating system(s):
Windows 10 Professional, 64bit, MinGW (gcc + gdb) and VSCode.
Rack-SDK, 0.6.2c

I run a task which does `make install`, attach gdb debugger and than open Rack.exe, in the end.
Once Rack opens (as discussed [here](https://community.vcvrack.com/t/debug-in-vscode-with-rack-sdk/2372), its not able to unzip the file and replace the current folder.

So, debugging, I'm not able to automate the process.
The only way I did is to edit the Make files and directly copy the build into the folder, instead of dist zip->copy and let Rack to unzip automatically.

**Comment by AndrewBelt** [comment] 2019-03-27 10:39
How is Rack invoked? What command is run?
Are you sure Rack is launched after the `make install` command is finished instead of in parallel?

**Comment by Nowhk** [comment] 2019-03-27 10:45
> How is Rack invoked? What command is run?
I'm calling it this way:

`
"configurations": [
{
	"name": "(gdb) Launch",
	"type": "cppdbg",
	"request": "launch",
	"program": "C:\\Program Files\\VCV\\Rack\\Rack.exe",
	"args": [],
	"stopAtEntry": true,
	"cwd": "C:\\Program Files\\VCV\\Rack\\",
	"environment": [{ "name" : "PATH", "value" : "${workspaceFolder}/../../dep/bin;C:/msys64/mingw64/bin;${env.PATH}" }],
	"externalConsole": false,
	"MIMode": "gdb",
	"miDebuggerPath": "C:/msys64/mingw64/bin/gdb.exe",
	"setupCommands": [
		{
			"description": "Enable pretty-printing for gdb",
			"text": "-enable-pretty-printing",
			"ignoreFailures": true
		}                
	],
	"logging": {
		//"trace": true,
		//"traceResponse": true
		"engineLogging": true

	},
	"preLaunchTask": "build vcv rack plugin"
}
`
> Are you sure Rack is launched after the `make install` command is finished instead of in parallel?
Yes, I've `"stopAtEntry": true`. It stops when gdb starts. Rack.exe its not launched at that point, and the new .zip has already been created.

So I would say Rack.exe start later.

**Comment by AndrewBelt** [comment] 2019-03-27 11:20
If a .zip file is in the `plugins/` directory, Rack will attempt to unzip it. Either way, something will be reported to log.txt. If nothing's in there, the problem is on your end.

**Comment by Nowhk** [comment] 2019-03-27 15:52
I don't see any problems on logs (simple: it doesn't run the unzip function).

Could it be that gdb launch Rack.exe in some fancy "dev" mode handle differently that won't process the unzip function?

**Comment by AndrewBelt** [comment] 2019-03-27 16:21
If the log reports nothing, the zip function is not being called at all. This is likely because the file does not exist at the time of launch.

**Comment by Nowhk** [comment] 2019-03-27 16:54
Yes mate, the zip exist before Rack.exe is executed.
As I've already said...

I place a breakpoint: once it stops, the zip file is generated (I check manually the folder) and the Rack isn't loaded yet.
Once I step on, the Rack.exe load, but unzip doesn't occurs.

**Comment by AndrewBelt** [comment] 2019-12-04 15:59
Closing, as this is likely an issue with your VSCode configuration. Comment if you can reproduce this issue without using VSCode (e.g. on the command line or a script).

**Closed by AndrewBelt** 2019-12-04 15:59 UTC
