### ISSUE TITLE
Nothing works 

### ISSUE THREAD

**Issue by Eltanoloko** [VCVRack/Rack#83] opened 2017-09-14 21:46 UTC
When loading modules, they have no knobs, no functions. the audible ones actually appear completel blank. any solution?

**Comment by AndrewBelt** [comment] 2017-09-14 21:52
You haven't stated your OS, but I will guess this is a duplicate of #17.

**Closed by AndrewBelt** 2017-09-14 21:52 UTC

**Comment by Eltanoloko** [comment] 2017-09-14 21:54
Hi Andrew 

sorry, the os is Yosemite 10.10.5

**Comment by Eltanoloko** [comment] 2017-09-14 21:55
And yet, it happens to me something very similar to issue 17
