### ISSUE TITLE
Cannot make 0.6 on ubuntu 64

### ISSUE THREAD

**Issue by shreeswifty** [VCVRack/Rack#970] opened 2018-05-23 17:35 UTC
```
/usr/bin/ld: dep/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libX11.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
compile.mk:52: recipe for target 'Rack' faile
```

**Comment by AndrewBelt** [comment] 2018-05-23 17:45
Please mention your Ubuntu version and Rack branch in your issue. Did you install all the dependencies? https://github.com/VCVRack/Rack#linux

**Comment by shreeswifty** [comment] 2018-05-23 20:22
Hello 
Yes all Deps built, the error is afterwards @ make

ubuntu 16 LTS
Intel® Xeon(R) CPU E5-1603 v3 @ 2.80GHz × 4 
Quadro K4200/PCIe/SSE2
4.4.0-116-lowlatency #140-Ubuntu SMP PREEMPT Mon Feb 12 22:41:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Taikakim** [comment] 2018-05-26 21:52
I have the same error on Ubuntu 18.04. Deps compiled fine, got that exact same error message than you.

**Comment by diegodorado** [comment] 2018-05-27 21:06
Smae for me. Deps installed ok after installing `libpulse-dev`
make throws the following error:

```
/usr/bin/ld: dep/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libX11.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
compile.mk:52: recipe for target 'Rack' failed
make: *** [Rack] Error 1
```

`uname -a`

Linux inspirion 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AndrewBelt** [comment] 2018-05-28 08:56
Duplicate of #888

**Closed by AndrewBelt** 2018-05-28 08:56 UTC
