### ISSUE TITLE
Rack hangs at start when you have a "soundflower" audio input active

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#299] opened 2017-10-22 21:45 UTC
OS (if applicable): OSX
Version (or "dev" if compiling from source): 0.4.0

this is happening a lot to me

if I have a Core Audio Interface and is set to "SoundFlower 2 chan"
and there is on the system, someone that is sending audio to that stream

Rack hangs on startup (loading the Autosave.vcv)

there is a deadllock in the OSX audio subsystem

here a capure of the stack from the debugger:
![screen shot 2017-10-22 at 23 43 54](https://user-images.githubusercontent.com/62518/31866638-f223eaf4-b782-11e7-91c4-bf0f5ba1ae1e.png)

**Comment by AndrewBelt** [comment] 2017-10-22 21:49
The issue is upstream with Portaudio. I'll close this in hopes of #82 fixing it. If Rack v0.5.0 still crashes, re-open this issue, since the problem will be for a different reason.

**Closed by AndrewBelt** 2017-10-22 21:49 UTC
