### ISSUE TITLE
Toggle Zoom to Fit All Hotkey

### ISSUE THREAD

**Issue by mountcurve** [VCVRack/Rack#1819] opened 2020-07-15 10:43 UTC
### Summary

I often want to fit all the modules in screen to see what's going on with the whole patch. Zooming out then zooming back in manually to work on things is clunky.

### Proposed design

A simple binding of an unused hotkey would suffice.

This could fail if the patch is too large to be seen with full max zoom, in which case it would have to default to max zoom out and align with top leftmost module, or the user's GPU cannot handle rendering that many objects.

#1793 describes a similar request for zoom to fit module. Perhaps a zoom state toggle would be more appropriate as a way of managing these simultaneously?

**Comment by stoermelder** [comment] 2020-08-24 18:15
You try this recently released module for that:
https://library.vcvrack.com/Stoermelder-P1/Stroke

**Comment by AndrewBelt** [comment] 2020-08-24 18:32
Duplicate of #1793

**Closed by AndrewBelt** 2020-08-24 18:32 UTC
