### ISSUE TITLE
Random function - Question/Request

### ISSUE THREAD

**Issue by LKHSogpit** [VCVRack/Rack#621] opened 2018-01-16 22:17 UTC
OS (if applicable): All
Version (or "dev" if compiling from source): 0.5.1

Is there a way to exclude parameters from the random function? Either by the way a module is coded? Requesting: by right clicking and marking for exclusion.

The Random function is great but lets say you have a key for a vco and don't want to change the key but would like to quickly find settings marking a parameter to exclude would be great. I know some sequencers allow you to randomise certain parameters only gate etc but if you could mark specific gates on the sequence to exclude that could be cool!

The likes of effects that would have a bypass/enable you right click that and exclude from random even down to levels on the effects and the wet/dry. The likes of NYSTHI reverb which has many parameters would benefit from a random exclusion just a thought.

**Comment by AndrewBelt** [comment] 2018-01-17 03:16
Duplicate of #205

**Closed by AndrewBelt** 2018-01-17 03:16 UTC
