### ISSUE TITLE
Multiple VCV Audio modules crashes Rack

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#132] opened 2017-09-24 07:14 UTC
OS: Mac OS
Version: v0.3.1 

If you add more audio interfaces (and try to set them to the same output) than there actually is on the system, this causes unrecoverable crash. The only way to recover is to reinstall the application. This should not be possible.

**Comment by AndrewBelt** [comment] 2017-09-24 07:16
Does deleting autosave.vcv solve it?

**Comment by Euphorbium** [comment] 2017-09-24 07:54
Where is it stored?

**Comment by AndrewBelt** [comment] 2017-09-24 08:11
In the same directory as Rack which you double clicked on. If it solves it then I have a potential idea.

**Comment by Euphorbium** [comment] 2017-09-24 08:13
There is only autosave.json Deleting it solves the problem. Also, I have noticed that sometimes it crashes even without going over the output limit, just by trying to set a second interface to same output. But sometimes it works.

**Comment by AndrewBelt** [comment] 2017-09-24 08:15
Oh right, I renamed it to autosave.vcv after v0.3.1.

These audio interface problems in general are really hard to solve because I essentially have nothing to go on, and the problem is usually upstream in portaudio rather than in Rack.

**Comment by Euphorbium** [comment] 2017-09-24 10:47
Would it be possible to check how many interface panels pointing to the same output exist on the rack, and then sum up all the signals going to the same output port on different panels, before sending the signal upstream? I guess the sample rate and the block size should be greyed out on all but the first of the audio interface panels.

**Comment by AndrewBelt** [comment] 2017-09-24 11:05
I see what you mean. PortAudio crashes Rack on MacOS when you duplicate an active Audio Interface, while on Linux it silently sets the audio device in the second Audio Interface to none.

**Comment by AndrewBelt** [comment] 2019-12-05 22:57
Fixed in Rack v2 by adding support for multiple audio interfaces.

**Closed by AndrewBelt** 2019-12-05 22:57 UTC
Labels: build system
