### ISSUE TITLE
VCV Rack freezes when opening finder

### ISSUE THREAD

**Issue by yugi-muto** [VCVRack/Rack#837] opened 2018-03-23 09:48 UTC
I'm using a mac, OS X version 10.9.5, and any time VCV rack opens the finder to save as or load anything the rack freezes. I can still fiddle with the knobs but everything I see on window is frozen from then on and I also can't save. 

This is a major problem for me because I'm trying to use the Simple recorder module which requires me to designate a save folder, which freezes the rack. Simple Modules are the only 3rd party modules I am using.

**Comment by AndrewBelt** [comment] 2018-03-23 10:00
Duplicate of https://github.com/VCVRack/Rack/issues/154

**Closed by AndrewBelt** 2018-03-23 10:00 UTC
