### ISSUE TITLE
Device Picker that Stays Open

### ISSUE THREAD

**Issue by jonheal** [VCVRack/Rack#1077] opened 2018-08-01 18:44 UTC
Perhaps by holding down a particular key, like maybe SHIFT, while invoking the devices menu causes it to stay open after a device is selected so that one can easily select more devices without having to completely re-invoke the menu. And maybe it would also need a close button at that point or verbiage "ESC to Close."

**Comment by darloth** [comment] 2018-10-04 21:37
I would also like this.  It used to... but then I'd sometimes want it to close as well, so, as recommended, a modifier key would be great.  Shift makes sense to me!

**Comment by modlfo** [comment] 2019-06-11 05:13
Closing as duplicate of #1114

**Closed by modlfo** 2019-06-11 05:13 UTC
