### ISSUE TITLE
No Knobs or Jacks on PC running Win 7 Ult SP 1

### ISSUE THREAD

**Issue by SKYNET23** [VCVRack/Rack#127] opened 2017-09-23 05:29 UTC
OS (if applicable):WIN 7 ULT SP 1
Version (or "dev" if compiling from source):0.3.1
No Knobs, buttons, or jacks visible, program works, but cannot adjust values very well like this...

**Comment by SKYNET23** [comment] 2017-09-23 05:30
![rack 1](https://user-images.githubusercontent.com/32086246/30770427-c4e8cc4e-9ffe-11e7-95c7-731c5302624c.jpg)

**Comment by AndrewBelt** [comment] 2017-09-23 06:03
Duplicate of #17 except you happen to have Windows. Should be fixed in the Dev version, will include in v0.3.2 release.

**Closed by AndrewBelt** 2017-09-23 06:03 UTC

**Comment by SKYNET23** [comment] 2017-09-23 06:31
ok, thanks!
