### ISSUE TITLE
Version 0.6.0 has been a disaster for me. Nothing loads properly anymore.

### ISSUE THREAD

**Issue by vogelscheiss** [VCVRack/Rack#901] opened 2018-04-09 17:42 UTC
Huge problem. Just installed Rack 0.6.0 and Mac 10.10.5.

Typical message when loading an old patch:
Could not find module "Clock Divider" of plugin "Autodafe"
Could not find module "Drums - Kick" of plugin "Autodafe-DrumKit"
Could not find module "Drums - Snare" of plugin "Autodafe-DrumKit"
Could not find module "Drums - Closed Hats" of plugin "Autodafe-DrumKit"
Could not find module "Drums - Open Hats" of plugin "Autodafe-DrumKit"
Could not find module "Reverb" of plugin "Autodafe"
Could not find module "LPFilter24dB" of plugin "Lindenberg Research"
Could not find module "LPFilter24dB" of plugin "Lindenberg Research"
Could not find module "Trummor" of plugin "VultModules"
Could not find module "Drums - Rim/Claves" of plugin "Autodafe-DrumKit"
Could not find module "DualFeedbackEcho" of plugin "NYSTHI"
Could not find module "LPFilter24dB" of plugin "Lindenberg Research"
Could not find module "Drums - Ride" of plugin "Autodafe-DrumKit"
Could not find module "Trummor2" of plugin "VultModules"
Could not find module "Debriatus" of plugin "VultModules"
Could not find module "Clock Divider" of plugin "Autodafe"
Could not find module "LPFilter24dB" of plugin "Lindenberg Research"
Could not find module "TwistedMVerb" of plugin "NYSTHI"
Could not find module "Drums - Claps" of plugin "Autodafe-DrumKit"
Could not find module "LPFilter24dB" of plugin "Lindenberg Research"
Could not find module "Lateralus" of plugin "VultModules"
Could not find module "IO-ClockDivider" of plugin "IO-Simple"

Or:

Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/__MACOSX
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Alikins
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Autinn
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Autodafe
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Autodafe-DrumKit
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Bidoo
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/build
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/CastleRocktronics
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/DrumKit
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/FrozenWasteland
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/karatesnoopy
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Lindenberg Research
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/MSM
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Nohmad
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/NonLinearInstruments 2
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/NYSTHI
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Ohmer
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Qwelk
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/res
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Southpole
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/src
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/Stellare-Modular
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/StellareModular-Link
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/SynthKit
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/trowaSoft
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/ValleyRackFree
Could not load plugin /Users/name_imac5k/Documents/Rack/plugins/ValleyRackFree 2
Could not find module "DualFeedbackEcho" of plugin "NYSTHI"
Could not find module "Clock Divider" of plugin "Autodafe"
Could not find module "Retri" of plugin "Autinn"

Also happening if I try to use the previous version (0.5.1):
Could not find plugin "AS" for module "BPMClock"
Could not find plugin "VCV-Console" for module "Console8_3"
Could not find plugin "Grayscale" for module "Algorhythm"
Could not find plugin "Grayscale" for module "Binary2"
Could not find plugin "Grayscale" for module "Algorhythm"
Could not find plugin "Grayscale" for module "Binary"
Could not find plugin "Grayscale" for module "Algorhythm"
Could not find plugin "Grayscale" for module "Binary2"
Could not find plugin "Grayscale" for module "Algorhythm"
Could not find plugin "Grayscale" for module "Algorhythm"

Which is weird because I do have a 
/Rack/plugins/Grayscale 
folder, containing
-LICENSE.txt
-plugin.dll
-plugin.dylib
plugin.so

and

/res
-Algorhythm.svg
-Binary.svg
-Binary2.svg

but the application is claiming what it needs is missing.

So now I have no access to my work. 

Clearly everything is higglety-pigglety. Can someone explain what's gone wrong and how to fix it?

Thanks.
<img width="425" alt="screen shot 2018-04-09 at 1 46 42 pm" src="https://user-images.githubusercontent.com/38222883/38513529-7e86600a-3bfc-11e8-8584-2c69ed2e4c70.png">

**Comment by vogelscheiss** [comment] 2018-04-09 19:56
It's a bug, actually, and god, I hope not normal. And renaming one's modules is a mistake. Moreover finding out new names and editing .vcv files is time-consuming and unnecessary. But mostly I'm just keen to fix my install.

It's helpful to know that you can edit the .vcv files, which I'd have never thought of. Nor have I found a reference to it before.

Re DLLs, this is a Mac install. Not sure what the Mac equivalent would be – plugin.dylib? How would one "suppress" it? 

I may be in for a nightmarish time recovering from all the problems generated by this update.

**Comment by AndrewBelt** [comment] 2018-04-09 23:25
If you are upgrading from Rack 0.5 to Rack 0.6, you need to remove (or backup) all old plugins and replace them with 0.6 plugins.

`VultModules` still exists but is commercial now at https://vcvrack.com/plugins.html#vult

**Comment by vogelscheiss** [comment] 2018-04-10 15:18
Thanks for your replies.
Could I just suggest that your manual be updated to indicate that users' extant plugins folder needs to be emptied so that 
![image](https://user-images.githubusercontent.com/38222883/38565977-a296f8ce-3cb0-11e8-9714-b02967c076e8.png)
can download the new versions?

Also, Andrew, could 
![image](https://user-images.githubusercontent.com/38222883/38566026-bab47b16-3cb0-11e8-85cb-30fdc029aed7.png)
point to https://vcvrack.com/plugins.html instead of https://vcvrack.com/ as it does currently?

Thanks.

**Comment by odahan** [comment] 2018-04-10 15:29
Never forget the product is still in beta since we don't have reached the 1.0 version. So things can still change and make old releases not compatible. This is not a bug, or a bad management of the project it is just a beta :-) (a good beta that is usable but not a 1.0 official release).
For package names I agree this is not a good idea, but this is the responsibility of each module maker, VCV and Andrew can't do anything about this...

**Comment by sollymil** [comment] 2019-01-09 03:47
The VCR website says glibly:
After adding a plugin to your VCV account, log into the toolbar of Rack itself and click Update plugins to automatically download new and updated plugins. Free plugins are added to your account immediately upon clicking the “Free” button.
I can't find anyway to 'Update Plugins' in the Rack itself.  Can somebody wise me up please?

**Comment by sollymil** [comment] 2019-01-09 03:51
I'm using 0,6.2c.  I notice the login doesn't seem to work.  I enter my email (tab does not work to password field), enter my password and press enter and nothing happens.  I've tried pressing register (which doesn't sound right) It seems to process something, but again nothing happens !!!  Help !

**Comment by digitalohm** [comment] 2019-01-16 16:09
@sollymil when you enter your username and password you have to click login.  I tried to do it by pressing enter on my windows 10 machine and same result.

**Comment by AndrewBelt** [comment] 2019-01-16 21:52
Closing since this since loading 0.5 plugins with Rack 0.6 doesn't work by design.

**Closed by AndrewBelt** 2019-01-16 21:52 UTC
