### ISSUE TITLE
Feature Request:  Customizable Module labels

### ISSUE THREAD

**Issue by JeffGreenlee42** [VCVRack/Rack#874] opened 2018-04-01 22:24 UTC
I have searched through feature requests and discussions, and I am so far unable to locate a mention of this topic,  So I am attempting to at least put forth this suggestion:  

I have noticed that no developer modules utilize the ability to define and save a line of text which might help identify the use of a module.  The one notable exception is the "Triggers" modules, which have a dropdown list of text values like "bass"  or "mix" or "modulation".. etc.. which is getting close, but it still is a finite list of values to choose from.   Upon use, one immediately wishes they had the ability to enter in their own value for a given trigger, but It appears this is probably not possible in this software environment , because, so far at least,   no one has attempted to develop that feature. 

My assumption is that this has something to do with the available memory space for modules in Rack and that there is simply is not a global memory space available to save text values.   In discussions about this I have heard arguments that this is done deliberately to "preserve the look and feel"   of hardware modules......   But I would argue that among the advantages provided by the software implementation of Modular software synthesis, (like the ability to save patches, and duplicate modules as far as CPU power will allow)  would be the ability to LABEL certain modules to help logically organize and identify key components in large patch system.  The obvious choices, besides event triggers,  would be Mixing consoles and even multiple rows of sequences as a visual aid to making logical sense out of seeming chaos.  

I am not a developer,  but I know enough to understand that a "saved" text value is among the LEAST complicated and (arguably least expensive!) states of a given object to preserve, compared to all of the other DSP values that must be saved in a developed module.  There are visual restrictions, I understand!  Most developers try to pack the most functionality into the smallest euror-rack style module and labels take up space.. (I sometimes think this is regrettable - some modules  are just TOO dense to navigate with a mouse!)    but for some uses of this capability, in limited character lengths,  I would think that invaluable in certain applications!    

So there you have it!  Make it possible for developers to utilize customizable labels in their modules!!!

**Comment by AndrewBelt** [comment] 2018-04-01 23:42
After reading this novel, I'm still not sure what you're suggesting. Basically this? #558

**Comment by Coirt** [comment] 2018-04-02 13:26
@AndrewBelt - https://www.keeping.com/customer-service/

**Comment by JeffGreenlee42** [comment] 2018-04-03 01:55
Andrew, 

No!  I am not suggesting a solution that is an ugly solution as the one you suggest.   My understanding is that individual Module developers do not have the ability in Rack to save and display Textual information within their modules.  Is this not correct?   The closest I have seen are modules that have a large drop down list of preset values that a user can choose from. It's obvious why this is awkward for a real hardware module - but text entry on a computer is trivial.  
  
I would like to see modules that present the option of a changeable text value (such as the AS Triggers modules)  where the clear purpose of the module is there to help identify function of the module within a patch system.     I had an online discussion where I asked the question:  "Why does a user not have the ability to define their OWN values?"   I was told that this is prevented because it violates some arcane "look and feel"  design rule. .. which seems silly and contrived to me.    
My "Novella"  was a very short one really.  I spent a couple of paragraphs trying to justify my request, in hopes that I would clarify why I think it is a legitimate request. 

Also,  I need to ask:   Is this NOT the appropriate place to submit feature requests?   I have received negative feedback when I have attempted to bring something like this in the Facebook page.   I was told I need to do it here.

Maybe I should ask a more pointed question.   Do you WELCOME  ... or WANT feature requests? Are regular end users (rather than developers - or veteran eurorack users)  not welcome to put forth feature requests?      I have reviewed my original post,  I don't see that I am offering any criticism,  or any demand. This is simply a Feature Request.   Take it or leave it.  Tell me why a feature like this does not fit your vision.   
 In your description on the NEW ISSUE page.. you put forth the statement:   " please consider that the `time saved by the user` must be much greater than the `time to develop the feature`, otherwise it will be closed."...  So I attempted to explain why I felt that the "user"  might benefit from this. Nothing more.  It would only apply to a restrictive limitation.. only on specific modules.

**Comment by AndrewBelt** [comment] 2018-04-03 03:57
So you want a text box like Core Notes? You can definitely do that with `TextField` (for the Blendish UI version) and `LedDisplayTextField` (for the Core-stylized version). I'm still a bit confused what you're asking at all, because after reading this line in your first post, I don't think a simple text field is what you're after.

>I have noticed that no developer modules utilize the ability to define and save a line of text which might help identify the use of a module.

By "identify" the use of a module, you're suggesting some user-defined identification on the panel of the module, right? This is more than just a TextField I mentioned above. Yet, it's not #558? So maybe you're not suggesting something on the panel at all. Maybe module alias names? I don't know what the "Triggers" module is because you didn't state its author, but it apparently has a choice button and dropdown list with a set of choices. You said you wanted to "enter in their own value for a given trigger". Value of what? Trigger type? Is this a number or a word like "bass", "mix" etc? What do these words mean in this "Triggers" module? But then you mention

>but text entry on a computer is trivial

in your second post, it makes me go back to thinking that you just want a text field. But I'm sure you haven't missed Core Notes or the login fields in the toolbar, Core MIDI-CC, or Core MIDI-Trig, so I'm thinking you must be talking about something else. 

---

Yes, this is the official forum for feature requests, as you probably read in the "New Issue" template.
Firstly, I apologize that I'm using this issue as an example because it's an extreme case of a verbose feature request that creates more questions than it answers, but many people do this every week over email and GitHub, and if I tried to start replying to them, I'd never be able to even *read* all of them, much less implement them all. 

If I ever give a negative reaction, I apologize because I don't mean it personally at all, but it's likely because of a couple reasons: 1) the feature request is a duplicate or very-near duplicate of another issue which creates redundant work for both of us, or 2) it doesn't get to the point (i.e. not concrete, or confusing). A butchered version of Einstein's famous quote is that if you can't describe your feature request in 1-2 sentences, the suggestion is likely not very well defined.

I love feature requests, but I'm sure you can understand that if after reading, I still have no idea what you're talking about, it's a bit frustrating, right? I suppose I could figure out what you want after 5-10 back-and-forth questions, but why not just state it clearly in the first place? Here's an example of a good feature request, which I would be glad to address if it was in this form:

>Add a text field UI element so users can type text into it which persists in the Rack patch. It is to be used for entering chord names like "Asus2" or numerical voltages like "5.5V". When focused, it shows a blinking cursor and when clicked off to the side, it loses focus and no longer accepts text.

At that point, I'd likely be on the same page, and we can discuss the issue further.

**Comment by JeffGreenlee42** [comment] 2018-04-03 05:34
Andrew,  

I'm not sure I'm advocating for an independant text field so much, (though I can see the uses for one).  I even like the idea you showed me of the "tape" items one could put anywhere, only because I would love to see utilities that help alleviate the visual confusion of large patches.   

But I think the specific thing I am hoping to address is POSSIBLE element that might be missing in Developer's available toolboxes.  I'm afraid that given the amazing usefulness of triggers, I made the assumption that seasoned veterans like yourself would understand what I was  referring to.   So I would request that you examine "Triggers MKI"  and "Triggers MKII" .. available in the AS collection of modules.   I think it might be more clear what I am requesting:  
  In their default states, the moduels display one or two empty "LED" text fields. I may have mis-lead you a bit. They are NOT drop down controls.  Instead there is a "Label" knob.  Turn that knob and you can scroll through the preset values ranging from "MUTE"  to common instruments to "SEQ".  The idea being that With a click of a button one can start or stop events in other modules.   Nigel Nixsmith  in his excellent Video series "Talking Rackheads" (The BEST tutorials in my opnion)  ... utilizes triggers quite often in his patches. I have not had the opportunity to use Rack in a Live performance,  but I can see how incredibly useful triggers would be.  If they are used in Quantity though they  DO really need to be very clearly labeled though.    It was his fourth video where I  asked the question:    "You can choose a value,  Why is it not possible to define your own value?"  The discussion is located here:      https://www.youtube.com/watch?v=eOHCjlCbyBU&t=26s.    

Nigel immediately understood what I was referring to and mentioned he has often  wondered the same thing... then he explained that he didn't think it were possible because of this effort to "preserve the look and  feel"  of hardware modules.   In a real digital hardware module,  text entry would be a kludgy and VERY ugly and laborious interface experience indeed.  
I also see another use for customizable labels:      in Larger Mix controls.  No one, to my knowledge uses it yet,  but I can image a module a scenario where one might be able to at least use a 3 letter identifier to identify each channel.

**Comment by AndrewBelt** [comment] 2018-04-03 05:51
So you want a text box with a LED-style font?

**Comment by JeffGreenlee42** [comment] 2018-04-03 08:32
That would be up to the Module developer, wouldn't it?

**Comment by AndrewBelt** [comment] 2018-04-03 09:01
Sorry @JeffGreenlee42, I'm going to have to close this. I just really don't have time for the game of "guess the vague feature request" that I feared this would turn into from the beginning.

**Closed by AndrewBelt** 2018-04-03 09:01 UTC

**Comment by modman2019** [comment] 2019-09-17 13:15
I would like module labels as well. This way I can mark things - sort of like a moveable sticky note on a module or parameter.
