### ISSUE TITLE
n_0_1905105/res

### ISSUE THREAD

**Issue by najiramusic** [VCVRack/Rack#1726] opened 2020-03-18 11:38 UTC
Hey everyone,

A colleague of mine has tried to install VCVrack numerous times on his Macbook Pro, running Mojave and while trying to install, the following issue pops up:

_Rack's resource directory "n_0_1905105/res" does not exist. Make sure Rack is correctly installed and launched_

Has anyone got an idea of what might cause this and how to fix it?
Kind regards,

Arjan

### Details

Operating system:
Rack version: vX.X.X
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

**Comment by AndrewBelt** [comment] 2020-03-18 17:00
Duplicate of https://github.com/VCVRack/Rack/issues/1623

**Closed by AndrewBelt** 2020-03-18 17:00 UTC
