### ISSUE TITLE
Module selection Menu needs scrollbar or some scroll option.

### ISSUE THREAD

**Issue by JoeSleaze** [VCVRack/Rack#158] opened 2017-10-01 18:23 UTC
WIN 7 Sp1 64 
VCV 0.3.2

I have acquired more free modules from the internet. 
As a result, the list of modules extends beyond window-range, yet there is no way to scroll down to the modules at the bottom of the list. They are not visible.

Thank you in advance!

**Comment by AndrewBelt** [comment] 2017-10-01 19:47
Duplicate of #68

**Closed by AndrewBelt** 2017-10-01 19:47 UTC
