### ISSUE TITLE
[feature] Option to sync / show CC value changes on UI element (encoder) directly ?

### ISSUE THREAD

**Issue by alectron** [VCVRack/Rack#1043] opened 2018-06-30 05:29 UTC
Heya, 
playing with this some more, and this might be just my personal preference - when sending cc value changes (via usb/midi controller or DAW automation/modulation) it would be rather nice to see the incoming value change on the UI element directly - i.e. let's say I have a filters' cutoff mapped to a hardware button, when I turn the hardware encoder, I would love to see the connected encoder in VCV turn in sync to the values to indicate the value/position/modulation range, and so one is able to grasp the value the encoder is actually in at a quick glance.
Whereas ss is, the virtual encoders seem to just stay in their last known virtual  location (unrelated to the incoming midi/cv values), and the only indicator that the value might be different than what the UI element communicates, is the plugs'/cables' (red<) ->green colour change, which is very hard to interprete/read, especially if one is dealing with small value changes. 
Also, I often find myself double checking, as the poti/encoder position is conflicting with what I am sending as it is not showing true information anymore in this case.

So, even though this is not possible with hardware, I would love to have an option (which I would leave on constantly... :D) to see the VCV modules' buttons/encoders/etc, if it has an in port that is fed with a signal, to move in sync with the incoming values to be able to see values and automation more easily.
Hope this makes sense.
Cheers.
c.

**Comment by AndrewBelt** [comment] 2018-06-30 05:38
Duplicate of #50 for knobs turned with MIDI CC messages

**Closed by AndrewBelt** 2018-06-30 05:38 UTC

**Comment by alectron** [comment] 2018-06-30 05:46
Oh, sorry, I thought #50 would be for a unified UI "midi" learn for any UI element (or so my hope - i.e. that you could control a UI element of any module even if it might not have a corresponding in-port for a given value - of which there are a few ), whereas this was aimed at only elements where an in-port and a corresponding encoder do exist...?
But yea, midi learn is very high on my list of hopes for VCV :D

**Comment by AndrewBelt** [comment] 2018-06-30 05:50
Correct, that's what #50 is about. 

As for your actual request, modulating the pitch of an oscillator at audio-rate frequencies and watching the knob move up and down at 1000 Hz would not only be an utterly useless visual, it would prevent the knob from being turned (or its visual feedback would be unreadable), so I'm closing that as won't-fix.

**Comment by alectron** [comment] 2018-06-30 06:07
Heh, didn't think about that... this would be indeed useless for audio signals (which is the more likely connection within VCV context...). 
But midi cc is 0-127 afaik, and usually we aren't capable to turn a knob 1000 times a second... or create midi automation that 'hectic'...  
So even though this is closed - one idea could be a 'cable' that is allowed to drive the receiver UI (or a UI button/encoder relative setting, so a right click on the UI element could set the UI element to 'listen') where a user consciously decides to have a UI element be driven by the incoming signal (where this would give useful visual feedback).
Either or, all good, just throwing ideas about...
Thanks for the feedback!

**Comment by AndrewBelt** [comment] 2018-06-30 06:13
Unnecessary complexity. Some module developers may decide to display some visualization of the sum of `knob + CV` signals, but it should be up to them, not Rack.
