### ISSUE TITLE
Buidling fails on mac with latest pull from sources

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#496] opened 2017-12-06 22:24 UTC
OS (if applicable):dev
Version (or "dev" if compiling from source):mac

just made a "git pull" of VCV rack.

results:

```
iMacdiAGrazioli:rack antonio_grazioli$ make run
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/gui.cpp.o src/gui.cpp
src/gui.cpp:444:3: error: use of undeclared identifier
      'glfwGetWindowContentScale'
                glfwGetWindowContentScale(gWindow, &pixelRatio, NULL);
                ^
1 error generated.
make: *** [build/src/gui.cpp.o] Error 1
```

**Comment by AndrewBelt** [comment] 2017-12-06 22:25
Duplicate of https://github.com/VCVRack/Rack/issues/494

**Comment by antoniograzioli** [comment] 2017-12-06 22:26
yep sorry just seen there was a closed issue ...my fault

**Closed by AndrewBelt** 2017-12-06 22:25 UTC
