### ISSUE TITLE
warning: array subscript 16 is above array bounds of 'float [16]' [-Warray-bounds]

### ISSUE THREAD

**Issue by Nowhk** [VCVRack/Rack#1771] opened 2020-05-05 08:48 UTC
When I compile, I always see this warning:

`C:\repos\Rack/include/engine/Port.hpp:138:14: warning: array subscript 16 is above array bounds of 'float [16]' [-Warray-bounds]`

I think you are aware of this.
Otherwise, I'll just let you know, so you can "ensure" this :)

**Comment by AndrewBelt** [comment] 2020-05-05 09:49
Duplicate of https://github.com/VCVRack/Rack/issues/1524

**Closed by AndrewBelt** 2020-05-05 09:49 UTC
