### ISSUE TITLE
Rack.exe won't run in Win10

### ISSUE THREAD

**Issue by Plsmakeitwork** [VCVRack/Rack#47] opened 2017-09-12 14:38 UTC
Hello, I am having an issue using Rack, whenever I run it I get the following message: 
![default](https://user-images.githubusercontent.com/31893598/30331655-1070f108-97e1-11e7-9bf9-424df40ba79c.png)

Could you please help me to fix this?

**Comment by tedpallas** [comment] 2017-09-12 16:54
Same error, windows 7

**Comment by vukovinski** [comment] 2017-09-12 17:11
Same error, W10

**Comment by tractuspk** [comment] 2017-09-13 19:31
Same issue persists in v31 for me, but now it says gWindow.

**Comment by tedpallas** [comment] 2017-09-14 12:08
Error has gone away for me with v31!

**Comment by AndrewBelt** [comment] 2017-10-02 04:13
Duplicate of #18

**Closed by AndrewBelt** 2017-10-02 04:13 UTC
Labels: compatibility, duplicate
