### ISSUE TITLE
Sound constantly cuts out - audio write error, underrun.

### ISSUE THREAD

**Issue by maniexx** [VCVRack/Rack#420] opened 2017-11-21 21:43 UTC
OS (if applicable): ubuntu 16.04 LTS
Version (or "dev" if compiling from source): 0.5.0 binary from website

Even in the simplest synth setup, even with a long buffer, the sound cuts out, and rack is printing
`RtApiAlsa::callbackEvent: audio write error, underrun.` to the console constantly. 
Version 0.4 still works for me, on the same audio device, also using ALSA.

**Comment by bontric** [comment] 2017-11-22 09:36
Hey,
some questions:

* are you able to build from sources? If so could you check out 
215f9675954e02162ae35a8f429c84adace33ac7 (last commit before switch to `RtAudio`) to confirm this is issue is caused only by the switch to RtAudio?

* What hardware are you running Rack on? (Processor/graphics card would be helpful)

* What is your global/audio interface frame rate?

`underrun` itself only means that Rack did not write enough audio to the alsa buffer which is either caused by a lack of performance or a problem with the way RtAudio handles underruns.

Note @AndrewBelt under/overruns are currently not handled by the Audio interface. This might not be problematic since this might be another issue with RtAudio (I'll have to compare the handling of Alsa underruns between `portaudio` and `RtAudio`). If there is a way to solve this in our implementation we'd have to add:

```cpp
static int rtCallback(void *outputBuffer, void *inputBuffer, unsigned int nFrames, double streamTime, RtAudioStreamStatus status, void *userData) {
	if (status&RTAUDIO_INPUT_OVERFLOW) {
          // Handle Overflow
	}

	if (status&RTAUDIO_OUTPUT_UNDERFLOW) {
	  // Handle Underflow
	}

```

**Comment by AndrewBelt** [comment] 2017-11-22 09:43
Do you know what those flags mean btw? You'd think that an overflow or underflow is a *result* (output) of the callback function, not an input. Doesn't makes sense to me.

**Comment by maniexx** [comment] 2017-11-22 09:54
- are you able to build from sources? 

Yes, I'll try tonight and let you know.

- What hardware are you running Rack on? (Processor/graphics card would be helpful)
CPU: Intel i5-4210M CPU @ 2.60GHz × 4 
GPU: Intel 4th Gen Core Processor Integrated Graphics Controller (rev 06)

- What is your global/audio interface frame rate?
I am not sure if this is what you need, let me know how to find it if not.
```
pactl list short sinks
1 alsa_output.pci-0000_00_1b.0.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	SUSPENDED
```

**Comment by bontric** [comment] 2017-11-22 10:11
> Do you know what those flags mean btw? You'd think that an overflow or underflow is a result (output) of the callback function not meeting its deadline, not an input to the function. Doesn't makes sense to me.

@AndrewBelt Taking a quick look at Alsa/RtAudio the `state flag is set _after_ writing to the audio buffer. So the Under/Overflow refers to the previous write operation. 

@maniexx
> Yes, I'll try tonight and let you know.

Thanks!

> CPU: Intel i5-4210M CPU @ 2.60GHz × 4
GPU: Intel 4th Gen Core Processor Integrated Graphics Controller (rev 06)

Okay, your resources shouldn't be the problem. Are you running any other hardware demanding applications parallel to Rack? Which Linux Distribution are you using? (If we can't fix this, you might want to set the realtime priority in `limits.conf` to improve audio performance, for archlinux see [here](https://wiki.archlinux.org/index.php/realtime_process_management) and [here](https://wiki.archlinux.org/index.php/Professional_audio))

>> What is your global/audio interface frame rate?
> I am not sure if this is what you need, let me know how to find it if not.

I meant the settings in Rack: Global Frame rate is in the top left corner next to `File` and the AudioInterface framerate is set in the `Audio Interface` module.

**Comment by AndrewBelt** [comment] 2017-11-22 10:18
Oh okay. I'm not sure how doing anything in the RtCallback function would help. What are you suggesting goes in the `// Handle Overflow/Underflow` sections?

**Comment by bontric** [comment] 2017-11-22 10:35
> Oh okay. I'm not sure how doing anything in the RtCallback function would help. What are you suggesting goes in the // Handle Overflow/Underflow sections?

I honestly don't know yet. I've only done some rather low level stuff with Alsa and I remember `xruns` where always a nasty problem since you basically have to "prepare" the device every time (The Alsa function is called `snd_pcm_prepare`), so they should be avoided with all means if possible. 

However, since this seems to be a `new` problem I'm assuming this is an issue with `RtAudio` (See #410 .. I also encountered more xruns with RtAudio than with portaudio). I just wanted to leave a note regarding the handling since we might need that in the future.  

Also fine tuning the RtAudio buffer parameters might help improve the performance and in turn avoid xruns: 

_(From the [RtAudio API notes] (http://www.music.mcgill.ca/~gary/rtaudio/apinotes.html) )_

>  Input/output latency on the order of 15 milliseconds can typically be achieved using any of the Linux APIs by fine-tuning the RtAudio buffer parameters (without kernel modifications).

**Comment by cmorse01** [comment] 2017-12-03 15:40
VCV Rack newbie here...  Discovered VCVRack a few days ago, initially downloaded the precompiled version and the official modules.  (Very nice, btw, looking forward to following this project).

My system: Ubuntu 17.04 running MATE desktop and 4.10.0-40-generic kernel.  i5-6260 (4 core) @ 2.9ghz, Intel Iris 540 graphics

Anyway - had the same distortion problems and hit this thread re: underrun errors.  So I elected to clone the source and compile myself in a separate directory.  After hunting down a few missing libraries I got everything to compile and run, still getting the glitches.

Followed the instructions for adding the JACK support and now I get ALSA & JACK driver options in the audio interface, but no JACK devices.  For all my other audio work I use the KXStudio/Carla/Cadence packages.  Cadence has now disappeared which may explain my lack of JACK devices.

Does installing the rtaudio automatically nuke any previous JACK setups?  I'll keep hunting but figured I'd ask here.  I'm hoping I don't have to rebuild a major portion of my system to get JACK audio back up and running.

**Comment by bontric** [comment] 2017-12-03 16:56
> Cadence has now disappeared which may explain my lack of JACK devices.

I'm not sure how that would explain your lack of JACK devices? (Not using these tools so maybe you usually run/start Jack through Cadence? Or how do you run/start Jack?)

> Does installing the rtaudio automatically nuke any previous JACK setups?

Installing/compiling rtAudio should not effect your Jack setup in any way. 



I need a more detailed description of your problems to help you.

1) Do you run Jack _before_ you start Rack? If so, can you provide a log from Jack?

2) Have you done any other installations or upgrades recently? Your problem with Cadence seems unrelated (Maybe not, we'll have to figure that out)  

3) What exactly do you mean by

> Cadence has now disappeared 

? Software usually doesn't magically disappear from a System..

If you can give me some more information we might figure out what's going on :wink:

**Comment by cmorse01** [comment] 2017-12-03 17:20
Still trying to sort out what happened.  But prior to beginning with VCVRack, I would generally run cadence first (which started jack), then run Carla (plugin host).  And everything was peachy.  I normally start cadence manually from a system tray icon, but that has now disappeared from the tray and from my application menu.  And trying to start it from command line simply says 'command not found' now.

Carla  (& Catia etc) are still in my menu, and start up fine, but there are no JACK devices present in the patchbay (midi controllers or audio outputs to Scarlett USB Audio interface is what I have attached)

Running the precompiled VCVRack, it just came up and ran with ALSA, but Cadence was running with ALSA bridge active.  JACK was not an option in the audio interface of the precompiled version but selecting ALSA worked (with minor audio glitching)

Only other installations I have done were for missing libraries that came up as errors in the VCVRack compiling process.  I don't recall all of them (should have written them down as I added them), but one I do remember having to add was asound.

I have noted that there are now a number of packages listed as 'no longer required' when i do apt-get upgrade.  The a2jmidid and catia jump out at me, I'm not sure what most of the others are, but am guessing they are packages somehow superseded by installing the new libs?

The following packages were automatically installed and are no longer required:
  a2jmidid catia glib-networking:i386 gstreamer1.0-x:i386 libaa1:i386 libavc1394-0:i386
  libcaca0:i386 libcairo-gobject2:i386 libdatrie1:i386 libdv4:i386 libgdk-pixbuf2.0-0:i386
  libgraphite2-3:i386 libgstreamer-plugins-good1.0-0:i386 libgudev-1.0-0:i386
  libharfbuzz0b:i386 libiec61883-0:i386 libpango-1.0-0:i386 libpangocairo-1.0-0:i386
  libpangoft2-1.0-0:i386 libproxy1v5:i386 libraw1394-11:i386 libsamplerate0:i386 libshout3:i386
  libslang2:i386 libsoup2.4-1:i386 libspeex1:i386 libtag1v5:i386 libtag1v5-vanilla:i386
  libthai0:i386 libv4l-0:i386 libv4lconvert0:i386 libvpx4:i386 libwavpack1:i386 libxv1:i386
Use 'sudo apt autoremove' to remove them.

I'm heading out of town this afternoon, so not sure when I'll get back to playing with this, but if you have any ideas on where to start, that would be great.  Right now I'm leaning toward removing the full VCVRack git clone directories and trying to get my original system back where it was.  Then a full system backup so I have it when I inevitably bork things again..  I should have done that before trying to build VCVRack...

**Comment by bontric** [comment] 2017-12-03 17:34
Uhg.. Yeah welcome to the unforgiving world of Debian dependency resolution. I stopped using Debian based systems because of stuff like that. 

_Short description/guess_: When you installed these libraries there was probably a conflict between packages which led aptitude to suggest something like "To Install X you need to remove Y because X won't work as long as Y is installed". So you thought: Well I probably don't need Y then and said "Remove Y". Turns out Y was apparently quite important for something else and now stuff stopped working because Y is not there anymore :disappointed: (In this example Y is either cadence or something cadence depends on)

Here is my suggestion:

First, check if there is a way to see what you installed earlier. You'll need to basically undo what you did there since it caused a conflict which led to your new problems. Either check your bash history or check the ubuntu wiki to figure out how to do that.

Another option might be manually install `cadence` again. By doing that you might be able to figure out which package was causing the conflict and in turn solve the problem by removing that package and installing cadence again. 

If you don't have the time/ don't want to look into this: Reinstall the system. It might be easier and faster :wink:

**Comment by cmorse01** [comment] 2017-12-04 00:18
Yeah, that's the direction I'm heading.  Cadence was part of the larger KXStudio package and can't be installed on its own even though the other KXStudio components are still there.  So if I can't gracefully back out of the changes I made this AM, then I'll pull everything related to the KXStudio repo and reinstall from there.

Alternate option - maybe I'll just back up my user files and do a fresh install with the 17.10 version and start fresh.

**Comment by cmorse01** [comment] 2017-12-04 00:29
Putting this here for reference more than anything else - these are the packages I needed to add in order to get VCVRack to compile on my system.  

sudo apt-get install xorg-dev
sudo apt-get install libglu1-mesa-dev
sudo apt-get install alsa-lib
sudo apt-get install libasound2
sudo apt-get install libasound
sudo apt-get install libasound2-dev
sudo apt-get install libjack-dev
sudo apt-get install gtk2.0
sudo apt-get install libgtk2.0-dev

**Comment by cmorse01** [comment] 2017-12-04 23:37
Follow up - 
I installed a fresh OS -  now running Ubuntu MATE 17.10.  
Have Carla/Cadence running successfully on JACK.
After installing some missing dependencies, got the ALSA version of VCVRack running.  Audio is fine via ALSA->PulseAudio->JACK(plugin) bridge in cadence.  (bridge is autostarted by default in my setup)

Time to add JACK support directly.  And this is presumably where it went bad for me yesterday.  Following the instructions on the wiki, make returns the following:

checking for audio API... using JACK
checking for jack_client_open in -ljack... no
configure: error: JACK support requires the jack library!

The library I added yesterday was libjack-dev 
Is this in fact the correct library its looking for or is there some other one.?

Figured I'd ask before I proceed further, taking a break anyway.  If I don't hear anything, I'll go ahead and try libjack-dev again later and hope for the best..

**Comment by AndrewBelt** [comment] 2017-12-04 23:48
A bit of a distro promotion here, but I honestly don't see how people tolerate using Ubuntu, Fedora, Debian, OpenSuse, Mint, etc. On Arch Linux, I just type `pacman -S jack` (or `yaourt jack` if I want to search the user repository sorted by popularity), and it installs jack and all the headers needed to compile against jack, and then I'm ready to link against jack. It takes a minimum of 10 `apt` commands for me to figure out the name of the packages I need to install to get the jack headers with the right versions and not some legacy package.

**Comment by cmorse01** [comment] 2017-12-05 01:26
Update (in case it helps others down the line).  

Rather than adding libjack-dev, I added libjack-jackd2-dev.   Everything compiled.  Carla/Cadence is still intact and JACK now appears in VCVRack.

JACK shows up as an Audio Driver (along with ALSA still operational).  But trying to select any one of a number of presented audio devices throws errors and not selectable.

a2j (5in, 5out) yields: [warning] Failed to start audio stream: RtApiJack::startStream(): error connecting output ports!

Same with system (7in, 7out)

PulseAudio JACK Sink (2in,0out) connects ok, but with no outputs is kind of useless.

Back to the drawing board.  But further along than we were...

**Comment by bontric** [comment] 2017-12-05 11:46
> A bit of a distro rant/promotion here, but I honestly don't see how people tolerate using Ubuntu, Fedora, Debian, OpenSuse, Mint, etc. On Arch Linux, I just type pacman -S jack (or yaourt jack if I want to search the user repository sorted by popularity), and it installs jack and all the headers needed to compile against jack, and then I'm ready to link against jack. It takes a minimum of 10 apt commands for me to figure out the name of the packages I need to install to get the jack headers with the right versions and not some legacy package.

@AndrewBelt I completely agree. I think the issue is that even a lot of Linux users don't usually compile by hand. Once you start installing smaller or newer projects you will run into all these dependency issues which also made me switch to Arch a few years ago. On Arch I basically have zero problems with my OS while on Ubuntu I remember spending hours fixing after some upgrades/installations. I guess as a "normal" Linux user you don't encounter these issues until you dive into projects which require you to compile yourself. Also for a user like that it's probably also quite a hassle to install Arch properly..

> JACK shows up as an Audio Driver (along with ALSA still operational). But trying to select any one of a number of presented audio devices throws errors and is not selectable.
"a2j (5in, 5out)" yields: [warning] Failed to start audio stream: RtApiJack::startStream(): error connecting output ports!
Same with "system (7in, 7out)"
"PulseAudio JACK Sink (2in,0out)" connects ok, but with no outputs is kind of useless.
Back to the drawing board. But further along than we were...
 
My first guess would be that you might have compiled RtAudio before installing `libjack-jackd2-dev`. If so try to recompile RtAudio. It's rather difficult to help you here since your problem seems quite specific. I hope you can make some progress..

**Comment by cmorse01** [comment] 2017-12-05 11:55
Good point.  Now that I have a list of all the missing dependencies, I'll delete everything and do a fresh compilation from the top down. 
Thank you for the suggestion - as noted I'm one of those users that doesn't compile from source very often, so still learning the ropes in that regards.
And thanks for putting this whole project together.  I built some hardware synth modules back in the early 80s (not too stable) and look forward to dabbling again in the digital domain..

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 5, 2017 at 6:46, Ben<notifications@github.com> wrote


My first guess would be that you might have compiled RtAudio before installing libjack-jackd2-dev. If so try to recompile RtAudio.

**Comment by Skrylar** [comment] 2019-02-01 23:32
Can confirm there is something wrong with either RtAudio or ALSA. Just replicated a performance stuttering problem that _only_ exists under an ALSA use case, and solely switching output to JACK (via SkJACK) fixed it.

(xref https://community.vcvrack.com/t/rtaudio-alsa-vs-raw-jack-performance-stuttering-observations/1685)

It may be worth seeing if ALSA's underruns are Pulse related, because there have been historical issues with the two in DAW contexts.

**Comment by modlfo** [comment] 2019-06-04 19:18
Closing this issue. Audio related problems in Linux will be covered in #1317

**Closed by modlfo** 2019-06-04 19:18 UTC
