### ISSUE TITLE
wrong patch overwrite issue after Rack crash on save after re-open

### ISSUE THREAD

**Issue by fractalgee** [VCVRack/Rack#1702] opened 2020-02-05 09:25 UTC
### Details

Operating system: Windows 10 Pro
Rack version: v1.1.6
Not relevant to current issue

### Summary

It is rather easy to end up accidentally overwriting previously open patch if saving what one thinks is current one when Rack opens after a crash

### Steps to reproduce

This is a bit trickier. You need the following conditions:

1) Settings.json was last updated when a previous patch had been open
2) You had opened another patch (template, or other patch file) and Rack crashed due to some plugin misbehaving on add or soon after soon after opening new patch, so Settings.json does not yet get updated when it crashes.
3) after restart of Rack the wrong filename still in Settings.json is in use and hitting 'save'has overwritten the previous patch, NOT the one one had open when Rack crashed.

So the lag between opening patch and Settings.json updated with current patch name open is issue of this illusive issue that has bitten many a folk over time. I finally managed to track this down, after it happened again recently as I was too irked to leave it be ;) 

Easy fix I can think of: Immediately update Settings.json and any in-memory patch name there may be held on open of a patch, or hitting New..., so no way old patch name can still be there when Rack should crash during that update lag.

**Comment by cschol** [comment] 2020-02-08 21:15
I just ran into the same issue. Luckily I noticed the patch name in the window title before hitting save. Rack had crashed with a faulty plugin and re-loaded my current patch, but with the file name of the previously loaded patch.

**Comment by fractalgee** [comment] 2020-02-08 21:17
exactly this issue

**Comment by pauldavisthefirst** [comment] 2021-01-24 23:16
This is getting to be a serious bug for me. I've now lost half a dozen patches caused by this sequence of events (just as fractalgee has described). It took me a while to figure out what was happening too.

**Comment by AndrewBelt** [comment] 2021-01-24 23:34
Identified source and fixed in Rack v2 branch (currently private) about 2 weeks ago. Will be included in the 2.0 release.

**Closed by AndrewBelt** 2021-01-24 23:34 UTC

**Comment by AndrewBelt** [comment] 2021-01-24 23:45
Duplicate of https://github.com/VCVRack/Rack/issues/1559
