### ISSUE TITLE
Connecting wires to offscreen gates

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#136] opened 2017-09-24 21:33 UTC
OS: Mac
Version: 0.3.1

There is no way to connect an output to an offscreen input. If  I take a wire connected to an output and drag it to  a side of a screen, I expect it to scroll to the side. Currently there is no way to scroll while holding the wire.

**Comment by AndrewBelt** [comment] 2017-09-24 23:33
Duplicate of #15

**Closed by AndrewBelt** 2017-09-24 23:33 UTC
