### ISSUE TITLE
Randomizer for multiple modules.

### ISSUE THREAD

**Issue by gogobanziibaby** [VCVRack/Rack#1472] opened 2019-07-11 05:41 UTC
I would like to see a way to select multiple modules in vcv, and then be able to randomize their parameters all with a right click or keyboard shortcut. Instead of hovering the mouse over one module at a time and hitting ctrl r.  It would also be nice to have a way to select specific parameters to be randomized across this group, in other words a do or do not randomize option for parameters. I would also like to see something similar to 'what the jack' and 'what the rack' but implemented natively, with greater control of which ports should be available for random connections, and control over which modules are possible to randomly insert.

**Comment by CyaNox** [comment] 2019-07-12 15:20
[Strip](https://github.com/stoermelder/vcvrack-packone/blob/v1/docs/Strip.md) by @stoermelder may partially fulfill your request (It also allows silly things [like this](https://cdn.discordapp.com/attachments/126525675753570305/597482252573737066/2019-07-07_19-28-58.mp4)).

**Comment by stoermelder** [comment] 2019-07-14 17:34
As @CyaNox said my STRIP module can be used to randomize multiple modules at once, even by CV. If you want to randomize only specific parameters you can add my CV-MAP module, map the parameters you want and feed the module with any clocked random source.
Feel free to open issues on my GitHub repo for feature requests, I will look into it what I can do!

**Comment by gogobanziibaby** [comment] 2019-07-15 00:05
Great, thanks to you both!

**Comment by AndrewBelt** [comment] 2020-04-01 18:44
Duplicate of https://github.com/VCVRack/Rack/issues/1225

**Closed by AndrewBelt** 2020-04-01 18:44 UTC
