### ISSUE TITLE
Unable to exit fullscreen mode on Mac after selecting show fullscreen in VCV Rack's menu.

### ISSUE THREAD

**Issue by bvrp** [VCVRack/Rack#1913] opened 2021-04-27 02:15 UTC
This issue was reported previously an improperly closed.

### Details

Operating system and version:
Rack version (vX.Y.Z):
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

**Comment by AndrewBelt** [comment] 2021-04-27 03:15
Duplicate of https://github.com/VCVRack/Rack/issues/1872. Please do not purposely open duplicate issues. Comment on the original issue instead.

**Closed by AndrewBelt** 2021-04-27 03:15 UTC
