### ISSUE TITLE
Long MIDI and Audio devices menu are not scrollable

### ISSUE THREAD

**Issue by alfonso73** [VCVRack/Rack#97] opened 2017-09-17 10:53 UTC
Hi, i've a lot of MIDI and audio in/out in my system. If the scroll menu is too long it can't be scrolled and i can't reach the desired IN/OUT.

**Comment by TronicLabs** [comment] 2017-09-17 11:51
duplicate of #68

**Closed** 2017-09-17 11:57 UTC
