### ISSUE TITLE
VCV Rack crashes if plugin.json is not consistent

### ISSUE THREAD

**Issue by vooh** [VCVRack/Rack#1318] opened 2019-06-05 18:47 UTC
hello,

Operating system: Win10 x64, core i5 8300H coffee lake
Rack version: v1.dev.ca5e496

in case if plugin.json file contains errors, VCV Rack may crash or behave unexpectedly when pressing right button mouse on the module. This is not obvious in some cases (unless a developer validates the json file every time before compilation) and maybe it would be good to add a 'try\catch' block.

cheers,
Alex

**Comment by AndrewBelt** [comment] 2019-06-05 22:20
Can't reproduce, and I doubt the problem is actually caused by plugin.json. Probably an ABI mismatch. Did you recompile Fundamental after recompiling Rack?

**Comment by vooh** [comment] 2019-06-06 22:48
hi Andrew,

hmm, I cannot get this issue reproduced again either. But I clearly remember it was related to some plugin.json faulty lines. I didn't recompile Rack, I've only updated my MinGW compiler and also some deps and recompiled them. Maybe I missed the compiler warning.. Don't know..Now, once I change the json file to incorrect, I just don't see my plugin in the list and also I see the warning during compilation..
 I'm working on my own module, so it is not related to any of Fundamentals. Maybe we can close this for now.   Thank you and sorry for disturbing, mate. You do awesome work!
thanks!

**Comment by Coirt** [comment] 2019-06-07 14:36
If you have any discrepancy with your plugin slug in the manifest and the slug at the end of the module.cpp it can fail on loading the plugin. Also if you have a plugin disabled (commented out) in your plugin.hpp/.cpp but that is still in the manifest it will cause the plugin to fail load. 
If you do have modules commented out in the .cpp/.hpp you can use `"disabled": true` in the manifest for that "slug" instead of deleted.

You can close yourself if you feel it is resolved!

**Comment by AndrewBelt** [comment] 2019-12-03 22:40
Closing as unreproducible.

**Closed by AndrewBelt** 2019-12-03 22:40 UTC
