### ISSUE TITLE
As a user I'd like to be able to easily open the last few recent projects from File menu using a shortcut.

### ISSUE THREAD

**Issue by jjdeprisco** [VCVRack/Rack#1744] opened 2020-04-06 13:47 UTC
Provide "recent projects" option under File menu that shows 3-5 recent patches.

### Summary

Better UX, consistency with most software where files are saved, ease of use.

### Proposed design

Under File menu, add option for "Recent Projects" under which there would be 3-5 (or more) file names listed for projects recently worked. When a project is selected, it will be loaded. See Ableton, Reason and MS Word for similar implementations.

**Comment by AndrewBelt** [comment] 2020-04-06 18:59
Duplicate of https://github.com/VCVRack/Rack/issues/969

**Closed by AndrewBelt** 2020-04-06 18:59 UTC
