### ISSUE TITLE
Mac 10.10.5 issues

### ISSUE THREAD

**Issue by fmgguy** [VCVRack/Rack#24] opened 2017-09-11 17:29 UTC
I've tried the download twice. I just get a blank rack. What am I doing wrong?

**Comment by QrchackOfficial** [comment] 2017-09-11 17:33
Nothing. Right click on the rack area to add stuff.

**Comment by fmgguy** [comment] 2017-09-11 17:59
I read that, but right clicking (control click MAC) does nothing. Can'd add modules, can't add add audio interface.

**Comment by oblivionratula** [comment] 2017-09-11 18:03
Can confirm in 10.10.5, two-finger click if you have a trackpad works, but control-click, which should do the same, does not.

**Comment by oblivionratula** [comment] 2017-09-11 18:05
FYI, duplicate of #20 it seems.

**Comment by juanjocov** [comment] 2017-09-11 18:10
I'm having the same problem in 10.11.6, control click does nothing...

**Comment by fmgguy** [comment] 2017-09-11 18:33
Ahh! two-finger click does it. SWEET! Thanks all.

**Comment by nay-seven** [comment] 2017-09-12 07:51
you're lucky , cause here , the application say you have 10.10.5 the app require 10.12...( works perfectly on 
 my mac mini with last High Sierra beta 10.13 happily

**Comment by oblivionratula** [comment] 2017-09-12 12:04
@nay-seven Had you tried re-downloading? The package was updated re: #12 and then worked for many of us.

**Comment by nay-seven** [comment] 2017-09-12 12:25
Thanks a lot oblivionratula, you're right, works perfectly on Yosemite now !

**Comment by LazyPike** [comment] 2017-09-12 17:31
@juanjocov 
I've got 10.11.6 and managed to fix the problem like this:
System Prefs > Mouse > Turn ON Secondary Click
I was then able to use the Right Click on my mouse where before I was using the Ctrl key.
(fyi - I use a Mac Magic Mouse)
G'luck

**Comment by AndrewBelt** [comment] 2017-09-12 22:40
Duplicate #20 was closed, so I'm closing this one. Will be included in v0.3.1 build.

**Closed by AndrewBelt** 2017-09-12 22:40 UTC
