### ISSUE TITLE
save groups of modules as preset

### ISSUE THREAD

**Issue by modman2019** [VCVRack/Rack#1757] opened 2020-04-16 12:35 UTC

**Comment by modman2019** [comment] 2020-04-16 12:36
This would be very good in the future where we can load a module group into a patch and everything is wired up and set the way we like it.  you know that favorite bass sequence or drum kit performance etc.

**Comment by AndrewBelt** [comment] 2020-04-16 14:28
Duplicate of #1443

**Closed by AndrewBelt** 2020-04-16 14:28 UTC
