### ISSUE TITLE
1.1.6 can cause a BSOD

### ISSUE THREAD

**Issue by SaccoSVD** [VCVRack/Rack#1723] opened 2020-03-16 03:35 UTC
I got 2 BSODs while working on two different VCV patches. I'm sure it was VCV as the BSOD was quite abrupt and there was no error code either, also my PC beeped and showed 0GB in each DImm in the BIOS, discarding and POSTing again showed all RAM.

Seems to me VCV 1.1.6 is capable of abruptly corrupt all RAM and cause a hard system halt.

Also is quite unstable, one time it opens fine, one time the audio is quite corrupted, sometimes it uses more or less CPU in a random fashion.

Other than that I'm having a blast making a Chariots of Fire realtime playable project.

**Comment by AndrewBelt** [comment] 2020-03-16 03:42
Rack doesn't run in kernel space, so it's impossible to crash the kernel. The crash is likely due to a faulty audio or graphics driver.

**Comment by SaccoSVD** [comment] 2020-03-16 04:10
Hmmm... got it.

So, you say there's no way Rack can corrupt the memory? Even if the coder wanted it to?

The interesting things are:

1) Rack seems to be quite crazy with the CPU. My machine crashed while using only 2 threads. You can see Rack CPU usage goes higher as you go with higher thread counts. I understand real time audio doesn't like MT, but I can go from 2 to 8 threads and then back to 2 threads and the CPU usage per core lowers instead of increasing despite less cores being utilized. Maybe is the nature of the beast. 

Are rack Oscillators / Filters of super high quality? I generally feel Rack's CPU usage is quite high compared to a DAW and plugins.

2) Literally no other software crashes my system, even less in such a weird fashion. I can render in Blender for hours without a problem, CPU temp at 76c. The last crash occurred while Rack was using only 2 Threads and at idle temps, that's why I suspect Rack is very RAM active also because despite the CPU usage at say 12 or 16 threads the CPU temperature rounds the 50c and that's typical of a RAM intensive app such as CEMU.

The two projects I was working on while experiencing the crashes were both quite big. Not extremely big though, but rather rich in modules and polyphony.

System, is:

3900X
64GB RAM

**Comment by AndrewBelt** [comment] 2020-03-16 04:57
Your questions are beyond the scope of this issue. Since Rack cannot *directly* cause a kernel crash (although it could indirectly through its use of audio or graphics drivers), I'm closing this as not an issue.

**Closed by AndrewBelt** 2020-03-16 04:57 UTC

**Comment by SaccoSVD** [comment] 2020-03-31 23:33
Sorry to comment again. but the crashes keep occurring and I'm not the only one. I do really hope you find the problem.

I don't think it has to do with my ASIO, or MIDI drivers. There has to be something else causing it. As I said nothing else crashes my machine at all.

**Comment by AndrewBelt** [comment] 2020-03-31 23:37
@SaccoSVD I can't solve your problem unless I can reproduce the issue, or if you debug the issue yourself. I have virtually no information about your system because you failed to fill out the issue template in your initial post, so there's no hope at all that I'll be able to reproduce this issue.

**Comment by SaccoSVD** [comment] 2020-03-31 23:45
https://patchstorage.com/mm-realtime-chariots/

If you try this project and leave it playing for a while I hope you can reproduce it. It is very random, Rack can be running for hours or minutes before a crash.

I cannot hunt for a way to reproduce as good as you can since you're the developer.

I'm actively looking for a culprit, but 10 out of 10 the system crashed while using Rack. Sadly the crash dump analysis and the even viewer doesn't show anything concrete.

**Comment by AndrewBelt** [comment] 2020-03-31 23:50
I won't attempt to reproduce this issue unless you fill out the bug report template. https://github.com/VCVRack/Rack/issues/new/choose
