### ISSUE TITLE
Change GUI resolution / zoom

### ISSUE THREAD

**Issue by lanthias** [VCVRack/Rack#248] opened 2017-10-17 09:13 UTC
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): 0.4.0

I'm using VCV on a 3200x1800 13 inch laptop, and the components are a bit too small to use comfortably. I would love the ability to change the resolution or zoom the screen, so I can more easily see everything.

Absolutely loving it -- great work.

**Comment by bontric** [comment] 2017-10-17 10:26
This has already been discussed here #89 and #76

**Comment by odahan** [comment] 2017-10-17 12:05
there is not only a need for HDPI devices, but there are lot of people with near vision problem, some modules have little texts. It could be very interesting to get a manual zoom. Most resources used to draw the modules are in SVG, a vector system, so zooming must not be a problem, easy scaling is part of the advantages of SVG.

**Comment by bontric** [comment] 2017-10-17 12:19
Sorry, maybe I misunderstand something but what you describe sounds exactly like #76

**Comment by AndrewBelt** [comment] 2017-10-17 14:01
Duplicate of #89 and #76. Thanks @bontric

**Closed by AndrewBelt** 2017-10-17 14:01 UTC

**Comment by odahan** [comment] 2017-10-17 16:22
#89  is speaking only about Hdpi, this is another story (even if technically speaking it is near but supporting hdpi does not strictly need a manual zoom the user can interact with).
But current discussion should be merged with #76 and it will be better to close this one and redirect to the latter.

**Comment by AndrewBelt** [comment] 2017-10-17 17:07
I still fail to see why this is different than those two issues.
