### ISSUE TITLE
Windows 10 Build Error

### ISSUE THREAD

**Issue by dshulman130** [VCVRack/Rack#988] opened 2018-06-04 22:00 UTC
Having trouble building for Windows 10. Followed the README instructions exactly. `deps` built successfully, Rack fails, showing this. I'm not sure what these references are, but apparently I'm missing them. Any help would be appreciated

```
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x33): undefined reference to `EVP_MD_CTX_create'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x6f): undefined reference to `EVP_MD_CTX_destroy'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x97): undefined reference to `EVP_MD_CTX_create'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xd3): undefined reference to `EVP_MD_CTX_destroy'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x932): undefined reference to `SSLeay'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xa29): undefined reference to `EVP_cleanup'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xa2e): undefined reference to `ENGINE_cleanup'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xa33): undefined reference to `ERR_free_strings'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xa3f): undefined reference to `CONF_modules_free'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xa44): undefined reference to `SSL_COMP_free_compression_methods'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xd5b): undefined reference to `SSL_load_error_strings'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xd60): undefined reference to `SSL_library_init'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xd6f): undefined reference to `OPENSSL_add_all_algorithms_noconf'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0xfdf): undefined reference to `RAND_egd'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x110c): undefined reference to `SSLv3_client_method'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x12a8): undefined reference to `RAND_egd'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x1798): undefined reference to `SSLv23_client_method'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x232b): undefined reference to `sk_pop_free'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x2755): undefined reference to `sk_pop'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x2793): undefined reference to `sk_num'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x27c5): undefined reference to `sk_pop_free'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x3b3b): undefined reference to `sk_num'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x3bb2): undefined reference to `sk_value'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x3e48): undefined reference to `sk_num'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x3e65): undefined reference to `sk_num'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x3e7b): undefined reference to `sk_value'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x3f96): undefined reference to `sk_num'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x420e): undefined reference to `sk_num'
dep/lib\libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x425e): undefined reference to `sk_value'
collect2.exe: error: ld returned 1 exit status
make: *** [compile.mk:52: Rack.exe] Error 1
```
Operating system(s): Windows 10
Version of Rack if using official binary, or commit hash and branch if compiling from source: 0.6.0
All hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): N/A

**Comment by AndrewBelt** [comment] 2018-06-04 22:01
Duplicate of a few issues, too lazy to find.

**Closed by AndrewBelt** 2018-06-04 22:01 UTC

**Comment by dshulman130** [comment] 2018-06-04 22:03
@AndrewBelt I've looked at those issues, this isn't a duplicate. I'm missing some libraries and they're not the same as the other issues. I've read the rest. Please reopen this

**Comment by dshulman130** [comment] 2018-06-04 22:05
@AndrewBelt Their issue was with BrotliDecoder, if you read the log I posted, you'll see it's not the same issue.

**Comment by AndrewBelt** [comment] 2018-06-04 22:21
Okay, I'll list them specifically: https://github.com/VCVRack/Rack/issues/972 https://github.com/VCVRack/Rack/issues/971 https://github.com/VCVRack/Rack/issues/948

**Comment by dshulman130** [comment] 2018-06-04 22:22
Ok, #972 solved it, but why wasn't that fix committed to source?
