### ISSUE TITLE
VCV Rack 1.1.6 won't launch on OS X 10.10.5

### ISSUE THREAD

**Issue by pffui** [VCVRack/Rack#1768] opened 2020-04-30 17:59 UTC
[log.txt](https://github.com/VCVRack/Rack/files/4560270/log.txt)
![vcv error](https://user-images.githubusercontent.com/34107561/80743522-0274bb00-8b15-11ea-8949-01c4e6ea6edc.jpg)

Operating system and version:Mac OS 10.10.5 Yosemite
Rack version v1.1.6
Mac mini 16 gig Ram

I’m struggling to install vcv rack. It just won’t launch, keeps hanging.

**Comment by eun-ice** [comment] 2020-05-31 15:43
same here
<img width="423" alt="image" src="https://user-images.githubusercontent.com/17766811/83356403-42260100-a366-11ea-8537-02a29a1d4a24.png">

**Comment by welby12** [comment] 2020-07-11 19:01
I'm having the exact same issue, only this is on Mac OS 11.0 Big Sur beta 2!! Just starting to search the topic here myself. I know I received the same error on 10.15.5 Catalina, but somehow it launched on the second try. Won't launch at all for me on Big Sur

**Comment by AndrewBelt** [comment] 2020-07-11 19:46
Duplicate of #1623

**Closed by AndrewBelt** 2020-07-11 19:46 UTC
