### ISSUE TITLE
Mac compilation broken

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#308] opened 2017-10-24 08:11 UTC
OS (if applicable): Mac OS X 10.10.5
Version (or "dev" if compiling from source): dev

Compilation on mac is broken since commit 

commit 7df90920caffc7192697f782e6808507c9b444d5
Author: ben <benjohnwie@gmail.com>
Date:   Thu Oct 19 16:09:30 2017 +0200

    Fix handling for ignore types

Error message is attached.

[make.log](https://github.com/VCVRack/Rack/files/1410013/make.log)

**Comment by AndrewBelt** [comment] 2017-10-24 08:16
Duplicate of #301 I believe

**Closed by AndrewBelt** 2017-10-24 08:16 UTC
