### ISSUE TITLE
Build issue with MSYS2

### ISSUE THREAD

**Issue by r4sas** [VCVRack/Rack#941] opened 2018-05-02 22:16 UTC
I've tried to build on clear installation of MSYS2 under Win8.1 Pro x64.

MSYS2 core have updated to latest versions with `pacman -Syu` and `pacman -Su` commands.

Builded branch: v0.6.
Dependencies compiled without errors, but app linking fails with libcurl errors:

```make
g++ -o Rack.exe build/dep/nanovg/src/nanovg.c.o build/src/asset.cpp.o build/src/main.cpp.o build/src/window.cpp.o build/src/audio.cpp.o build/src/bridge.cpp.o build/src/plugin.cpp.o build/src/midi.cpp.o build/src/tags.cpp.o build/src/settings.cpp.o build/src/engine.cpp.o build/src/app/MidiWidget.cpp.o build/src/app/app.cpp.o build/src/app/ToggleSwitch.cpp.o build/src/app/Port.cpp.o build/src/app/SpriteKnob.cpp.o build/src/app/CircularShadow.cpp.o build/src/app/ModuleLightWidget.cpp.o build/src/app/SVGPort.cpp.o build/src/app/MomentarySwitch.cpp.o build/src/app/SVGPanel.cpp.o build/src/app/RackScrollWidget.cpp.o build/src/app/RackWidget.cpp.o build/src/app/SVGKnob.cpp.o build/src/app/WireContainer.cpp.o build/src/app/Toolbar.cpp.o build/src/app/RackRail.cpp.o build/src/app/Panel.cpp.o build/src/app/ModuleWidget.cpp.o build/src/app/SVGSlider.cpp.o build/src/app/MultiLightWidget.cpp.o build/src/app/LedDisplay.cpp.o build/src/app/WireWidget.cpp.o build/src/app/SVGSwitch.cpp.o build/src/app/SVGScrew.cpp.o build/src/app/SVGButton.cpp.o build/src/app/AudioWidget.cpp.o build/src/app/ModuleBrowser.cpp.o build/src/app/Knob.cpp.o build/src/app/LightWidget.cpp.o build/src/app/PluginManagerWidget.cpp.o build/src/app/ParamWidget.cpp.o build/src/app/RackScene.cpp.o build/src/Core/Blank.cpp.o build/src/Core/MIDITriggerToCVInterface.cpp.o build/src/Core/Core.cpp.o build/src/Core/MIDICCToCVInterface.cpp.o build/src/Core/MIDIToCVInterface.cpp.o build/src/Core/MidiIO.cpp.o build/src/Core/AudioInterface.cpp.o build/src/Core/QuadMIDIToCVInterface.cpp.o build/src/Core/Notes.cpp.o build/src/dsp/minblep.cpp.o build/src/ui/Button.cpp.o build/src/ui/Label.cpp.o build/src/ui/Menu.cpp.o build/src/ui/ScrollWidget.cpp.o build/src/ui/MenuItem.cpp.o build/src/ui/List.cpp.o build/src/ui/PasswordField.cpp.o build/src/ui/ui.cpp.o build/src/ui/ChoiceButton.cpp.o build/src/ui/WindowWidget.cpp.o build/src/ui/Slider.cpp.o build/src/ui/layouts.cpp.o build/src/ui/Tooltip.cpp.o build/src/ui/ProgressBar.cpp.o build/src/ui/TextField.cpp.o build/src/ui/Scene.cpp.o build/src/ui/MenuLabel.cpp.o build/src/ui/RadioButton.cpp.o build/src/ui/MenuOverlay.cpp.o build/src/util/logger.cpp.o build/src/util/system.cpp.o build/src/util/string.cpp.o build/src/util/request.cpp.o build/src/util/random.cpp.o build/src/widgets/TransformWidget.cpp.o build/src/widgets/SpriteWidget.cpp.o build/src/widgets/SVGWidget.cpp.o build/src/widgets/widgets.cpp.o build/src/widgets/QuantityWidget.cpp.o build/src/widgets/Widget.cpp.o build/src/widgets/ZoomWidget.cpp.o build/src/widgets/FramebufferWidget.cpp.o build/dep/osdialog/osdialog_win.c.o Rack.res -static -Wl,--export-all-symbols,--out-implib,libRack.a -mwindows -Ldep/lib -lglew32 -lglfw3 -ljansson -lspeexdsp -lzip -lz -lcurl -lssl -lcrypto -lrtaudio -lrtmidi -lpthread -lopengl32 -lgdi32 -lws2_32 -lcomdlg32 -lole32 -ldsound -lwinmm -lksuser
dep/lib\libcurl.a(libcurl_la-version.o):version.c:(.text+0x68): undefined reference to `BrotliDecoderVersion'
dep/lib\libcurl.a(libcurl_la-version.o):version.c:(.text+0x73): undefined reference to `BrotliDecoderVersion'
dep/lib\libcurl.a(libcurl_la-version.o):version.c:(.text+0x13b): undefined reference to `BrotliDecoderVersion'
dep/lib\libcurl.a(libcurl_la-version.o):version.c:(.text+0x236): undefined reference to `BrotliDecoderVersion'
dep/lib\libcurl.a(libcurl_la-version.o):version.c:(.text+0x2fe): undefined reference to `BrotliDecoderVersion'
dep/lib\libcurl.a(libcurl_la-version.o):version.c:(.text+0x309): more undefined references to `BrotliDecoderVersion' follow
dep/lib\libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:(.text+0x3e): undefined reference to `BrotliDecoderDestroyInstance'
dep/lib\libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:(.text+0xfb): undefined reference to `BrotliDecoderDecompressStream'
dep/lib\libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:(.text+0x141): undefined reference to `BrotliDecoderGetErrorCode'
dep/lib\libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:(.text+0x177): undefined reference to `BrotliDecoderDestroyInstance'
dep/lib\libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:(.text+0x1f0): undefined reference to `BrotliDecoderCreateInstance'
collect2.exe: error: ld returned 1 exit status

```

**Comment by AndrewBelt** [comment] 2018-05-03 02:50
Duplicate of https://github.com/VCVRack/Rack/issues/923?

**Closed by AndrewBelt** 2018-05-03 02:50 UTC

**Comment by r4sas** [comment] 2018-05-03 06:19
Oops, yes it is. Not found it with search on issues page.
