### ISSUE TITLE
Problems Saving and Loading patches in version 1.1

### ISSUE THREAD

**Issue by audinf** [VCVRack/Rack#1411] opened 2019-06-27 13:50 UTC
### Details

Operating system: Windows 7 Pro
Rack version: v1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Intel Core i7-3770 @ 3.4 GHz, with 24 GB of RAM installed, and using a NVidia GeForce GTX 460 with driver version 390.65

### Summary

I updated VCV to version 1.1 and now, when I try to open a patch from inside VCV, it doesn't show any patch, despite the fact it is pointing to the right folder, and using the right file type (.vcv). I also cannot choose the ALL option (many times a saviour in these circumstances). But I can see a lot of file types with what seem like chinese or some sort of oriental language characters). This is happening in Windows 7 Pro

**Comment by SteveRussell33** [comment] 2019-06-27 14:00
Also happens in Win 10. See https://github.com/VCVRack/Rack/issues/1407

**Comment by audinf** [comment] 2019-06-27 15:10
Thanks. After the thread in FB, I was under the impression that this wasn't happening in Windows 10. Unfortunately, it seems to also affect Windows 10 as well :-(

**Comment by AndrewBelt** [comment] 2019-06-27 16:32
Duplicate of https://github.com/VCVRack/Rack/issues/1407

**Closed by AndrewBelt** 2019-06-27 16:32 UTC
