### ISSUE TITLE
VCV Rack does not start on MacOS 10.16 Beta 1 gives a error about resource directory

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#1805] opened 2020-06-25 12:09 UTC
### Details

Operating system and version:
Rack version (1.1.6):
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
MacBookPro15,2

### Steps to reproduce

* Start Rack on MacOS 10.16 Developer Beta 1

See error message in screenshot, I
<img width="265" alt="Screenshot 2020-06-25 at 14 08 34" src="https://user-images.githubusercontent.com/15910225/85717117-72ef2100-b6ed-11ea-9ac6-e2b62b936b74.png">
 find no way to start Rack.

**Comment by AndrewBelt** [comment] 2020-06-25 12:17
Duplicate of https://github.com/VCVRack/Rack/issues/1623

**Closed by AndrewBelt** 2020-06-25 12:17 UTC

**Comment by sanderbaan** [comment] 2020-06-25 12:23
If manually adding this res file in the resources is the solution to this problem then this is not a solution in my eyes. I installed the OS and downloaded VCV Rack from www.vcvrack.com and launched the App. This should just work and it should not include manual steps messing in the App bundle!

**Comment by sanderbaan** [comment] 2020-06-25 12:27
I tried the work around mentioned in 1623 at the bottom and it does not work it keeps complaining about another folder name which it cannot find. So this problem is not fixed.

**Comment by sanderbaan** [comment] 2020-06-25 12:30
I followed the steps you described:
1. Try launching again > FAIL
2. Copy Rack > Applications > FAIL
3. Run xattr -d com.apple.quarantine /Applications/Rack.app in terminal > FAIL

**Comment by sanderbaan** [comment] 2020-06-25 12:37
Figured it out, Rack needs Access to the Documents folder as it tries to create something there on first launch. If you start Rack from the command line it works. There should be a proper fix for users who do not know how to do things in Terminal.

**Comment by AndrewBelt** [comment] 2020-06-25 13:00
>If manually adding this res file in the resources is the solution to this problem

Not sure where you made this up. I never said anything like this.

Locking thread because this is a duplicate, as I stated above.
