### ISSUE TITLE
Scalar: Issue resetting CENTS

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#1099] opened 2018-09-14 03:21 UTC
Operating system(s): Ubuntu 18.04
Version of Rack: 0.6.2b

- Add Scalar plugin to Rack
- Right-click on CENTS value, NOTES reset to 0.
- Right-click CENTS again, observe that NOTES changes to -4194304.
- Right-click CENTS again, observe that NOTES changes to -2147484648.

**Comment by AndrewBelt** [comment] 2018-09-14 23:46
This issue is caused by the disabled CENTS value on note 0 (the root note) not actually being disabled, creating undefined behavior when the right-click action is triggered. Will be fixed in Scalar 0.6.1.

**Comment by AndrewBelt** [comment] 2018-09-15 00:12
Updated

**Closed by AndrewBelt** 2018-09-15 00:12 UTC

**Comment by cschol** [comment] 2018-09-15 00:17
Fix confirmed. Thank you!
