### ISSUE TITLE
List of plugins doesn't scroll/expand

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#137] opened 2017-09-25 09:46 UTC
Both on Mac or PC
I now have a long list of plugins I am developing, and the list of plugins goes out of the screen, it's clipped, and it's not possible to scroll down.
I see 2 possibilities. 
1) Make it scrollable vertically with mouse wheel
2) Group plugins by developer, with a second level menu with the list of plugins...Maybe it's a better option because we will probably soon have lots of developers joining in...

![longlist](https://user-images.githubusercontent.com/16060683/30802505-074f7288-a1e7-11e7-9d51-64d1588610b3.png)

**Comment by AndrewBelt** [comment] 2017-09-25 09:53
Duplicate of #68 and #97

**Closed by AndrewBelt** 2017-09-25 09:53 UTC
