### ISSUE TITLE
BUG: ".vcv" not appended to patch name when saving (Win10)

### ISSUE THREAD

**Issue by patman023** [VCVRack/Rack#1471] opened 2019-07-11 04:46 UTC
**_NOT a copy of #1407_**

Operating system: Win10 Home
Rack version: v1.1.1 Production Release

----

When you go to save files, unless you manually type in ".vcv", it is not being appended to the File Name. 

These files are saved properly as a VCV formatted JSON, and if renamed in Windows Exploder, function correctly. 

However, if a user does not rename the file(s), this can cause issues when trying to retrieve files to reopen them.

Saving .vcvm files is working correctly.

![Untitled](https://user-images.githubusercontent.com/36520477/61022030-3356ea00-a361-11e9-9de7-0665d5e14ab9.png)
![Untitled2](https://user-images.githubusercontent.com/36520477/61022034-38b43480-a361-11e9-92ad-d0c6dfac0d51.png)

_For comparison, when I saved the above screenshot in MSPaint without an extension, ".png" was appended automatically._
![Untitled3](https://user-images.githubusercontent.com/36520477/61022110-8a5cbf00-a361-11e9-9de3-901cd2f657d0.png)
![Untitled4](https://user-images.githubusercontent.com/36520477/61022114-8e88dc80-a361-11e9-95ab-05827090be33.png)

**Comment by ilambert** [comment] 2019-07-14 03:49
Confirmed for Linux (Ubuntu 18.04) as well.

**Comment by Ghalebor** [comment] 2019-07-18 21:26
Win10 Pro VCV Rack v.1.1.1 the same problem I cant save and open a .vcv files. When I try to save patch to files program save only name of patch as zerobytes file without extention *.vcv

**Comment by AndrewBelt** [comment] 2019-07-19 17:31
Fixed in f381e12. Since you were saving the file with the path `C:\whatever\Rack1.x\patches\mypatch`, Rack thought that your requested extension was `x\patches\mypatch`, so it thought that you wanted that extension instead of `vcv`.

**Closed by AndrewBelt** 2019-07-19 17:31 UTC

**Comment by patman023** [comment] 2019-07-20 02:19
Ah, so the "." in the folder name borked it?

Also, I'm assuming this fix will go live on the next production release, since I don't build from source?
