### ISSUE TITLE
Win Seven no police ?

### ISSUE THREAD

**Issue by nay-seven** [VCVRack/Rack#40] opened 2017-09-12 07:56 UTC
I try to use this great tool on a Win Seven ( via VMWare on a mac book pro to be precise) but i don't see any text, in the top header or in the right click menu, i can open a module, but this one with no text. i use right click on the _DejaVuSans.ttf_ and "install" , restart computer but same.
Thanks

**Comment by AndrewBelt** [comment] 2017-09-14 06:06
Probably duplicate of #17?

**Closed by AndrewBelt** 2017-09-14 06:06 UTC
