### ISSUE TITLE
alsa error

### ISSUE THREAD

**Issue by LOGUNIVPM** [VCVRack/Rack#114] opened 2017-09-19 18:14 UTC
Every few minutes I get an engine crash (probably after a few alsa underruns)

ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
Expression 'err' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3350
Expression 'ContinuePoll( self, StreamDirection_In, &pollTimeout, &pollCapture )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3891
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4269

I have a self-compiled version of the core. This happens even with no plugins loaded at startup.

**Comment by maricn** [comment] 2017-10-12 21:16
I experience the same on "dev" version I compiled on Debian.
```
Saving settings ./settings.json
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
```

**Comment by AndrewBelt** [comment] 2017-10-12 21:20
^ That's not the same issue @leopard86 is having.

**Comment by leopard86** [comment] 2017-10-13 08:05
@maricn do you experience a crash after this? Alsa underruns are not scary, maybe you will just hear some glitches, the problem is if these will crash your app.
I still experience these crashes with the latest dev, but maybe it's my machine. I can run VCV for hours if not connected to the audio card, but after I connect to Alsa some underruns occur in one or two minutes and then boom.

BTW: maybe I could ask for help in the linux audio mailing list?

**Comment by maricn** [comment] 2017-10-13 08:20
I have audio glitches - clicking sound when underrun occurs, and usually experience crash after some time. I just built it last night, so didn't have a chance to properly play around yet..

**Comment by leopard86** [comment] 2017-10-13 09:40
@maricn ok then maybe post your console output right after a crash.

**Comment by maricn** [comment] 2017-10-25 20:34
I am actually experiencing #131. Attaching details there.

**Comment by leopard86** [comment] 2017-10-26 20:12
I wrote to the linuxaudio and the portaudio mailing list but so far I got no one replying.
BTW: I think this should be merged with #131 
Increasing the buffer size reduces the number of underruns and this increases the "longevity" before the crash, but it is not a guarantee of success on the long run.

**Comment by jcelerier** [comment] 2018-01-20 10:31
hi, I had the same problem in my software and posted on the portaudio mailing list: apparently this is due to ALSA's pulseaudio wrapper alsa-pulse.

Here's the mail: https://lists.columbia.edu/pipermail/portaudio/2018-January/001342.html

There is a WIP for a native pulseaudio backend https://app.assembla.com/spaces/portaudio/git/merge_requests/3719213

**Comment by modlfo** [comment] 2019-06-04 19:19
Closing this issue. Audio related problems in Linux will be covered in #1317

**Closed by modlfo** 2019-06-04 19:19 UTC
Labels: build system
