### ISSUE TITLE
Text on Modules show up as blocks

### ISSUE THREAD

**Issue by nharral** [VCVRack/Rack#1798] opened 2020-06-19 01:44 UTC
All of the text on the modules in VCV Rack show up as blocks which makes patching to the various parameters on a module quite difficult.

Any thoughts on how I can fix this?
![Screen Shot 2020-06-18](https://user-images.githubusercontent.com/67131437/85087956-bdbfe480-b193-11ea-9ba7-8b51a9842072.jpg)

**Comment by AndrewBelt** [comment] 2020-06-19 03:05
Duplicate of https://github.com/VCVRack/Rack/issues/399

**Closed by AndrewBelt** 2020-06-19 03:05 UTC
