### ISSUE TITLE
VCV RACK 1.1.0 does not show saved patches in Win 10

### ISSUE THREAD

**Issue by WinkenNod** [VCVRack/Rack#1432] opened 2019-06-30 17:12 UTC
### Details

Operating system: Win 7 and Win 10
Rack version: v1.1.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Two different PC's one with Win 7 the other with Win 10. 

### Summary
After saving a patch to a project folder in Windows, .vcv files are not displayed when trying to open a patch from within VCV Rack under File > Open.

Workaround: Sometimes this can be corrected by closing the patch and then loading the default patch ( File > New) and then trying to open a saved patch (File > Open). Otherwise, VCV Rack must be closed and the previously saved patch must be opened from windows explorer.

### Steps to reproduce
Save a Patch using "Save" or "Save As". Open another patch ( File > Open). No VCV patches appear in any folder that contain them. Close VCV Rack and navigate to the folder with saved patches. A patch can be opened from there. After doing this, the problem persists; with VCV Rack open, try to open another patch (File > Open) The dialogue box "Current patch is unsaved. clear it and open a new patch?" appears. Select OK -same problem occurs.
 See workaround above- this works but sometimes requires several tries.

**Comment by stoermelder** [comment] 2019-06-30 17:15
Duplicate of https://github.com/VCVRack/Rack/issues/1407, already fixed. Please close.

**Closed** 2019-06-30 19:10 UTC
