### ISSUE TITLE
Quad MIDI to CV bug when playing back more than 2 notes in legato.

### ISSUE THREAD

**Issue by Uriel-A** [VCVRack/Rack#535] opened 2017-12-19 10:20 UTC
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): Both dev and v0.5.0

Not sure if this is intended behavior or a bug but nobody had reported this so far. Maybe not many people are actually using the Quad MIDI to CV module? I did found someone else on Facebook who also has this problem, except he's only experiencing it when playing it live and didn't test playback. See the P.S. at end of this post for my experience on this.

Issue:
When more than 2 notes are played back from a DAW in legato style (i.e. previous notes off and next notes on are back to back but NOT overlapping. See pic) and sent to VCV, the Quad MIDI to CV module will fail to reliably output ONE of the notes.

![full](https://user-images.githubusercontent.com/34455276/34148851-f68b45dc-e4dd-11e7-9c1b-d76d01cb7ef9.PNG)

If 3 notes are sent, only 2 will always trigger and the third will occasionally fail, and if 4 notes are sent, only 3 will trigger and the 4th will occasionally fail. The gates LED also verify this.

The note that goes missing always seems to be the lowest pitch of the group.

I've also tested using Gratrix's MIDI-C1/G1 modules just to be sure and all the notes do trigger correctly, and in legato (no full envelope retriggering). The Quad MIDI to CV module will also work correctly in this manner but only when not more than 2 notes are being sent.

Workaround:
I discovered an allowance of at least 20ms (19.5ms to be exact) between the notes are needed in order for the Quad MIDI to CV module to trigger all the notes reliably but that will also result in full envelope retriggering. Maybe the module requires that much time to process the data and Gratrix's MIDI-C1/G1 code is faster? (note: I did encounter a different set of issue with Gratrix's modules however)

![shorten](https://user-images.githubusercontent.com/34455276/34149311-a6c0ea0a-e4df-11e7-967b-e91955e60665.PNG)

All tests were done using all the 3 modes. The results of Rotate and Reassign mode are identical whereas the Reset mode seems to be behaving in a monophonic manner? I can hear all the other notes getting choked out immediately every time leaving only one note sounding even when playing it live.

This issue (apart from the Reset mode) currently doesn't manifest when playing live directly into VCV using a controller, but I believe that probably just because nobody can switch chords fast enough in under 20ms?

It would be great if more people could test and verify this. The pitches doesn't matter as long as the notes off and notes on are back to back with at least 3 notes.

P.S. The problem actually does exists before when playing live, even when not playing legato but it went away yesterday when I changed my anti-virus software. Who knows. These tests are done with my new AV switched off anyway, just to be certain.

**Comment by bontric** [comment] 2017-12-19 10:36
Thank you for the detailed report. I've experienced something similar with the MIDI to CV module as well. My first guess was that it is due to receiving note off/on messages simultaneously (The logic, as it is implemented now, will lead to one message being ignored) . I haven't really had the time to take a deeper look but I can give you something to work with for now:

+ Try increasing the global sample rate to the maximum value (top left corner in rack). This will probably not fix it but might give us another idea.

+ If you are able to build dev, try changing : 

https://github.com/VCVRack/Rack/blob/v0.5/src/core/QuadMidiToCV.cpp#L106
```cpp
	if (isPortOpen()) {
		std::vector<unsigned char> message;
		int msgsProcessed = 0;

		// midiIn->getMessage returns empty vector if there are no messages in the queue
		// NOTE: For the quadmidi we will process max 4 midi messages per step to avoid
		// problems with parallel input.
		getMessage(&message);
		while (msgsProcessed < 4 && message.size() > 0) {
			processMidi(message);
			getMessage(&message);
			msgsProcessed++;
		}
	}
```

to

```cpp
	if (isPortOpen()) {
		std::vector<unsigned char> message;
		getMessage(&message);
	        processMidi(message);
		}
	}
```

This will ensure that _only one_ midi message is processed in each step. This **might** fix the issue.

Another thing to look at would be the different modes. Can you reproduce the issue with each Quad-Midi-To-CV mode (reassign, rotate, reset) ?

**Comment by Uriel-A** [comment] 2017-12-19 10:44
I've just tested increasing the global sample rate to the maximum. My audio output barfs if I go beyond 96kHz but at 192kHz I did see only 2 gate LED lighting up sometimes instead of 3. Same thing in 96kHz.

I will try to compile and test the code changes later.

As in the first post:
The results of Rotate and Reassign mode are identical whereas the Reset mode seems to be behaving in a monophonic manner? I can hear all the other notes getting choked out immediately every time leaving only one note sounding even when playing it live.

**Comment by bontric** [comment] 2017-12-19 11:02
> I've just tested increasing the global sample rate to the maximum. My audio output barfs if I go beyond  96kHz but at 192kHz I did see only 2 gate LED lighting up sometimes instead of 3. Same thing in 96kHz.

Okay, good to know, seems like the issue is somewhere else.

> I will try to compile and test the code changes later.

That would be great. i'll look at the code in the mean time and try to figure out whether the problem might be somewhere else.

> The results of Rotate and Reassign mode are identical whereas the Reset mode seems to be behaving in a monophonic manner? I can hear all the other notes getting choked out immediately every time leaving only one note sounding even when playing it live.

Interesting, thanks. The modes are explained here: https://github.com/VCVRack/Rack/wiki/MIDI-Modules#modes

**Comment by bontric** [comment] 2017-12-19 11:14
> I've also tested using Gratrix's MIDI-C1/G1 modules just to be sure and all the notes do trigger correctly, and in legato (no full envelope retriggering). The Quad MIDI to CV module will also work correctly in this manner but only when not more than 2 notes are being sent.
[...]
Maybe the module requires that much time to process the data and Gratrix's MIDI-C1/G1 code is faster? (note: I did encounter a different set of issue with Gratrix's modules however)

This is really  strange. The Gatrix module [is based on the Quad-MIDI-to-CV module](https://github.com/gratrix/vcv-gratrix/blob/master/src/MIDI-G1.cpp#L5) and uses exactly the same code for handling polyphonic midi.

**Comment by Uriel-A** [comment] 2017-12-19 11:16
That's what I thought I've read it somewhere in his release notes too, which makes this whole thing a bigger mystery!

**Comment by bontric** [comment] 2017-12-19 12:01
> That's what I thought I've read it somewhere in his release notes too, which makes this whole thing a bigger mystery! But his modules has other problems with pedal point style playing. Moving notes completely goes missing after a while sometimes, but that problem doesn't happen in the core Quad MIDI to CV module.

Which version of the Gratix modules are you using? I remember in the early versions of the Quad midi module the pedal was buggy. Looking at the code now, it seems to be up-to-date but maybe he implemented the fix later.

**Comment by Uriel-A** [comment] 2017-12-19 15:36
I have no idea to be certain but the context menu in VCV says Gratrix v0.5.0.

Just to clarify, the pedal point I'm talking about is the compositional technique https://en.wikipedia.org/wiki/Pedal_point and not the CC64 sustain pedal. It's basically holding a bass note or notes while arpeggiating another set notes on top of it at the same time.

I'm not a programmer but I do know how to read C++ to some extend. I have a better understanding in Max for Live and have written my own patch before to split polyphonic notes into individual outputs so as to feed into individual monophonic synths.

If you can guide me along some of the stuffs that I'm uncertain about in the module's code, I should be able to get a handle on the algorithm and try to figure out where went wrong. I'm suspecting it could be in the vector itself, how each set of data are retrieved and cleared but there are some terms that I have no idea what it does exactly.

**Comment by Uriel-A** [comment] 2017-12-19 17:24
OK, I've just did a compile with the code changes you suggested and the moment I select any device in the Quad MIDI to CV module VCV just crashes.

**Comment by bontric** [comment] 2017-12-19 21:20
> OK, I've just did a compile with the code changes you suggested and the moment I select any device in the Quad MIDI to CV module VCV just crashes.

Oops, I forgot something. I updated the original comment with the code changes

> Just to clarify, the pedal point I'm talking about is the compositional technique https://en.wikipedia.org/wiki/Pedal_point and not the CC64 sustain pedal. It's basically holding a bass note or notes while arpeggiating another set notes on top of it at the same time.

Ah okay, I'm glad to get some feedback regarding more sophisticated usage since I'm certainly lacking some knowledge when it comes to musical or compositional techniques and therefore I can only test the basic functionalities.

> If you can guide me along some of the stuffs that I'm uncertain about in the module's code, I should be able to get a handle on the algorithm and try to help figure out where went wrong. I'm suspecting it could be in the vector itself, how each set of data are retrieved and cleared but there are some terms that I have no idea what it does exactly

If you want you can take a look and I will help you as much as I can. I'm also able to test this soon myself. What you describe sounds like the issue I'm trying to resolve with the proposed fix, but there might be something somewhere else that needs fixing. I'm sure we'll get to the bottom of this :wink:

**Comment by Uriel-A** [comment] 2017-12-20 06:28
We shouldn't need to worry about pedal point playing as that issue doesn't seem to manifest in the Quad MIDI to CV module, just the Gratrix modules and it's an even weirder issue.

I see your update now, am going to compile and test it. Will also be taking a closer look at the entire code. I'll need your help to clarify what parts of the code are suppose to be doing like open.push_back and open.push_front for a start.

**Comment by Uriel-A** [comment] 2017-12-20 09:46
@bontric I have some good news! 🙌 Looks like your code changes fixed the notes from dropping out!

However, the envelopes are always fully retriggered as confirmed with a scope. Gratrix's modules do not retrigger the envelopes. But in truth, it's also somewhat random. Half the time it doesn't and half the other time it randomly does.

Here's the thing, I'm not actually sure what is suppose to be the expected behavior from what is actually written in the code. Are the current code actually provisioned for legato playing?

The ideal behavior for legato playing is to not retrigger at all. Of course, one could also try to somewhat emulate that by using a slow attack and release. So, I will take this win for now. 😃 

Reassign and Rotate mode has the same results. Reset mode is still choking out all but one of the notes which it shouldn't because there's only 3 notes playing. So essentially, Reset mode is and remains broken?

**Comment by Uriel-A** [comment] 2017-12-20 09:54
Ok. I've decided to test the CC64 sustain function and found a bug too. Do I need to open a new issue or just post it in here?

**Comment by bontric** [comment] 2017-12-20 13:43
> @bontric I have some good news! :raised_hands: Looks like your code changes fixed the notes from dropping out!

Well that's something :+1: . Can you confirm that this works consistently? 

> However, the envelopes are always fully retriggered as confirmed with a scope. Gratrix's modules do not retrigger the envelopes. But in truth, it's also somewhat random. Half the time it doesn't and half the other time it randomly does.
Here's the thing, I'm not actually sure what is suppose to be the expected behavior from what is written in the code. Are the current code actually provisioned for legato playing?

Well I did not consider it. From my understanding the Midi-To-CV module allows legato playing, but  
I'm not sure whether it should be the default behavior for the Quad-Midi module. It shouldn't be a big
deal to implement this so I might simply add a _legato mode_ to the module. Or do you have a suggestion?

> Reassign and Rotate mode has the same results. Reset mode is still choking out all but one of the notes which it shouldn't because there's only 3 notes playing. So essentially, Reset mode is and remains broken?

I need to test this my self and get back to you.

> Ok. I've decided to test the CC64 sustain function and found a bug too. Do I need to open a new issue or just post it in here?

Maybe add it to #81 if it needs discussion we can also open an [issue in my fork](https://github.com/bontric/Rack-MIDI)

**Comment by Uriel-A** [comment] 2017-12-20 15:33
I won't be able to do it today but I will do further thorough testing with it tomorrow and get back to you.

I believe many implementation of MIDI legato is based on some form of detection of the time passed from the last note off. If it is shorter than a specified amount then no retrigger, so if you don't want to legato simply make sure your note lengths aren't too close together; Or, it could simply be an option switch to turn it on and off permanently. Easier to implement but more troublesome for the end user.

However, do consider the implications of a logic failure in a polyphonic scenario, especially when some form of pedal point playing (again) or similar is being performed. i.e. not every notes are moving rhythmically together. Which is similar to the CC64 bug I'm seeing now.

Are each MIDI packet tagged with the port number that it's meant to be sent to stored inside the vector? How does the code know where to send the corresponding note off to the right port?

The CC64 bug is polyphonic specific. How do I add it to there anyway? GitHub noob here. 😅

**Comment by Uriel-A** [comment] 2017-12-21 08:50
Tested the same MIDI clip play back for one hour without any dropouts. Also tested with 1/8 note chords for speed with no dropouts. Did further testing by playing live, including some pedal point style also without any dropouts.

Both Reassign and Rotate mode were tested. Reset mode couldn't be tested due to the monophonic bug.

I say your fix is rock solid.

P.S. I've edited my previous post regarding the legato implementations, so please do re-read.

**Comment by bontric** [comment] 2017-12-22 09:17
> Tested the same MIDI clip play back for one hour without any dropouts. Also tested with 1/8 note chords for speed with no dropouts. Did further testing by playing live, including some pedal point style also without any dropouts.

Thanks, that is good news! I guess there needs to be some more testing since this _might_ lead to problems if Rack receives too many midi messages at the same time. (Imagine a sequencer sending polyphonic notes, multiple CC and additional Aftertouch messages from multiple channels). In an extreme scenario we might get some delays, but we might get these delays either way. (Handling multiple messages in one step vs. handling only one message per step). However, there would be other workarounds as well so we'll have to see.

> Or, it could simply be an option switch to turn it on and off permanently. Easier to implement and is also the traditional implementation in many old hardware synths.

Having an On/Off switch for legato seems more reasonable not only because it's easier to implement but also because it's clear to the user whether they are using legato or not. Implementations based on timing can always lead to some weird undefined behavior if the timing is slightly off.

> The CC64 bug is polyphonic specific. How do I add it to there anyway, or you mean just post it there? GitHub noob here. :sweat_smile:

Rethinking this, it'll probably be better to open a separate new issue. Since I'm on vacation and unfortunately don't carry around a pedal, I'll have to hack something together to figure out what's going on. However if you open an issue and provide information as detailed as you did with this issue, I might be able to come up with a fix without testing :wink:

**Comment by Uriel-A** [comment] 2017-12-22 10:00
> Thanks, that is good news! I guess there needs to be some more testing since this might lead to problems if Rack receives too many midi messages at the same time. (Imagine a sequencer sending polyphonic notes, multiple CC and additional Aftertouch messages from multiple channels). In an extreme scenario we might get some delays, but we might get these delays either way. (Handling multiple messages in one step vs. handling only one message per step). However, there would be other workarounds as well so we'll have to see.

I thought the MIDI CC to CV module is the only one that's handling CC, other than CC64 that is? I don't use aftertouch and my controller doesn't have it either so I can't help to test that out.

> Having an On/Off switch for legato seems more reasonable not only because it's easier to implement but also because it's clear to the user whether they are using legato or not. Implementations based on timing can always lead to some weird undefined behavior if the timing is slightly off.

Yeah, I was going to say that having a On/Off switch for legato is probably for the best because I don't use sequencers within VCV but I believe that sequencers always output full length notes and there's no way to fine tune the note length with it?

> Rethinking this, it'll probably be better to open a separate new issue. Since I'm on vacation and unfortunately don't carry around a pedal, I'll have to hack something together to figure out what's going on. However if you open an issue and provide information as detailed as you did with this issue, I might be able to come up with a fix without testing 😉

I took a better look at the code and found the cause the of CC64 bug. It would require a rewrite of the implementation. I do a detail write up of it in a new issue later.

Also, I found a C++ reference website that really helped me a lot to understand the code better and I may have fixed the Reset mode problem.

line 214
```	switch (mode) {
		case RESET:
			if (open.size() >= 4) {
				for (int i = 0; i < 4; i++) {
					activeKeys[i].gate = false;
					open.push_back(i);
				}
			}
```
`open.push_back(i);` needs to be deleted. Or else open.size() is forever >=4?

Compiled and tested it. Playing a 5th note will drop off the other notes leaving only the 5th note sounding. 😃

**Comment by Uriel-A** [comment] 2017-12-22 10:06
Oh, and most importantly, enjoy your vacation! Happy Solstice! 😄

**Comment by bontric** [comment] 2017-12-22 13:33
> I thought the MIDI CC to CV module is the only one that's handling CC, other than CC64 that is? I don't use aftertouch and my controller doesn't have it either so I can't help to test that out.

Oh yeah you are right. I was thinking a step ahead and was going to implement that for all modules. But even then there would be a limitation. Assume the quad midi to cv could receive 128*4=512 Note ON + 512 Note OFF = 1024 note messages. Additionally there could be 128 After touch messages. In this absolute extreme scenario we'd have to handle 1152 messages. Assuming 48K Hz as the frequency we would requite about 1152/48000 = 24 milliseconds to handle them all. That's okay for the absolute worst case scenario (which also doesn't make a lot of sense). Hence we can probably apply this for all modules and ensure a more stable handling since messages are always handled exclusively.

> Yeah, I was going to say that having a On/Off switch for legato is probably for the best because I don't use sequencers within VCV but I believe that sequencers always output full length notes and there's no way to fine tune the note length with it?

I guess it would depend on the sequencer. The ones I use (and also the one I'm currently programming) would only allow you to "fine tune" up to the resolution of the midi clock (which is 6 ticks per 16th) so depending on your bpm you might get quite fine tuning but I wouldn't rely on it.

 > `open.push_back(i);` needs to be deleted. Or else open.size() is forever >=4?
Compiled and tested it. Playing a 5th note will drop off the other notes leaving only the 5th note sounding. 

I think this is almost correct but as far as I remember my original intention this would be

```cpp
		case RESET:
			if (open.size() >= 4) {
				open.clear()
				for (int i = 0; i < 4; i++) {
					activeKeys[i].gate = false;
					open.push_back(i);
				}
			}
```

The reason for this is that  `open.push_back(i);` in the loop ensures that the order is also reset so _after_ all notes are reset, the outputs will be used on the order 1..4 . (Assume you play 3 notes, release the second and play another 2. Now the order will be 1,3,2,4)

> Oh, and most importantly, enjoy your vacation! Happy Solstice! :smile:

Aww, thank you! The same to you :tada:

**Comment by bontric** [comment] 2017-12-22 14:49
I created a branch which contains these fixes (based on the v0.5 branch). You can apply it to your rack by typing:

`git pull https://github.com/bontric/Rack-MIDI v0.5-bontric-midi-fixes`

I'll play around with this for a bit and create a pull request later on. 

(@AndrewBelt should I create a PR for the v0.5 branch or for the master branch?)

**Comment by Uriel-A** [comment] 2017-12-22 14:50
> The reason for this is that open.push_back(i); in the loop ensures that the order is also reset so after all notes are reset, the outputs will be used on the order 1..4 . (Assume you play 3 notes, release the second and play another 2. Now the order will be 1,3,2,4)

I'm a little confused. What you're describing only makes sense for the other 2 modes.

Now after removing push_back, the order is always reset back to 1,2,3,4 with the 5th note playing out on 1. Isn't that what the Reset mode is suppose to behave? Dropping all previous 4 notes i.e. all 4 gates off before playing the 5th note hence the order is also literally reset back to 1,2,3,4?

**Comment by AndrewBelt** [comment] 2017-12-22 14:51
@bontric Master branch

**Comment by bontric** [comment] 2017-12-22 16:50
> I'm a little confused. 

Sorry I might have phrased this wrong.

> Now after removing push_back, the order is always reset back to 1,2,3,4 with the 5th note playing out on 1. 

What I meant is that your suggested fix will mix up the order in some specific cases. Follow the example I gave before (with your fix) and the order will not be reset to 1,2,3,4 .

**Comment by Uriel-A** [comment] 2017-12-22 17:54
Ah, I think I get what you're trying to say.

I've just tried to test your example and yes the order does gets mixed up when playing with 4 or less notes. But the weird thing is the moment it goes beyond 4 it always reset back to 1,2,3,4. TBH I honestly don't know why it happens but it does! 😆 

Yes your code is a safer and proper way of doing it but with push_back in the loop doesn't it goes back to the vector is always >=4 again even if you clear it before entering? Or maybe the check should be changed to >4 instead in that case? I could be wrong tho since I'm not the real coder here haha.

**Comment by Uriel-A** [comment] 2017-12-22 18:04
> TBH I honestly don't know why it happens but it does! 😆

Could it be because of this happening earlier up the code upon the next run of the function?

line 197:
```
	if (open.empty()) {
		for (int i = 0; i < 4; i++) {
			open.push_back(i);
		}
	}
```

**Comment by bontric** [comment] 2017-12-22 22:06
> I've just tried to test your example and yes the order does gets mixed up when playing with 4 or less notes. But the weird thing is the moment it goes beyond 4 it always reset back to 1,2,3,4. TBH I honestly don't know why it happens but it does! :laughing:

My example wasn't correct. I'll try to give you a more precise example (Make sure you compile rack with your fix):

1) Play any 4 notes and hold

2) release the second and fourth note you initially played

3) play another 3 notes and hold (while still holding the others, now holding 5 notes in total)

4) release the 4 initial notes (which have already been reset) and keep holding the last (which is on output 1)

5) Play another 3 notes and the order will be 3, 2, 4

Now the fun part starts. This is actually not due to your implementation but due to another small bug. (I was testing that with both your and my fix and realized that this is occurring with both implementations)

(In QuadMidiToCV.cpp line 180)

```cpp
      if (activeKeys[i].pitch == data1) {
```

should be:

```cpp
      if (activeKeys[i].pitch == data1 && activeKeys[i].gate) {
```

Due to this the order was messed up in the example I gave before and you are right, your example works due to:

```cpp
	if (open.empty()) {
		for (int i = 0; i < 4; i++) {
			open.push_back(i);
		}
	}
```

However, using your fix the appropriate behavior would be sort of obscured. As you said: 

> I honestly don't know why it happens but it does! :laughing:

And the only difference between my fix and your fix is that with mine it's more obvious whats going on (and since there is no need to optimize here this a priority)

> Yes your code is a safer and proper way of doing it but with push_back in the loop doesn't it goes back to the vector is always >=4 again even if you clear it before entering? Or maybe the check should be changed to >4 instead in that case? 

No, the vector's size is not always going to be >=4 since, if you check a few lines down:

```cpp
221  int next = open.front();                                                           
222  open.pop_front();     
```

`open` acts as a queue to define the order in which the outputs are used. I spent quite some time on the implementation since, even though it seems simple, it wasn't easy to implement this in a somewhat clean way. That's also why it is a bit tricky to see exactly whats going on.

> I could be wrong tho since I'm not the real coder here haha.

You certainly ask the right questions though :smile: . Thanks to this I found another bug :wink:

**Comment by bontric** [comment] 2017-12-23 08:58
@Uriel-A I have a small question regarding legato playing. From my understanding you don't want the gate to retrigger if notes are overlapping. Now what will work now is that if you play and hold 4 notes (in reassign mode) and play a 5th, the gate for the 5th note will not be retriggered. 

Now here is the tricky part. How should the module recognize a legato play for 2 notes? There is no way to differentiate between a _"new note on a new output"_ and _"play this note legato on one of active outputs"_.

It seems to me that a setting to limit the number of output modes (mono, 2, 3, 4) would solve this problem since you can define the number of notes you play and it will then behave like the module behaves now when you hold 4 notes and play a 5th.

(*Note*: I tried to look for polyphonic midi-to-cv modules which implement legato and I couldn't find a reference module that implements polyphonic legato. For example, Mutable Instruments' [Yarn](https://mutable-instruments.net/modules/yarns/manual/) only allows  the legato setting for monophonic layouts and another reference [here](https://ask.audio/articles/understanding-mono-legato-mode-in-synth-sample-vis) also describes legato modes more specific to monophonic play)

**Comment by Uriel-A** [comment] 2017-12-23 09:10
I'm assuming you're still talking about implementing it as a straight forward On/Off switch and your concern is when should the envelope actually retrigger in a polyphonic environment?

My idea is only retrigger on any next note on if all notes are off.

**Comment by Uriel-A** [comment] 2017-12-23 09:16
> @Uriel-A I have a small question regarding legato playing. From my understanding you don't want the gate to retrigger if notes are overlapping. What will already work now is that if you play and hold 4 notes (in reassign mode) and play a 5th, the gate for the 5th note will not be retriggered.

Actually I wouldn't say when overlapping since we are deciding on the On/Off switch, doesn't matter if the notes are spread far apart it should not retrigger if the switch is turned on.

**Comment by Uriel-A** [comment] 2017-12-23 09:32
Here's one implementation but it's time based.
https://www.youtube.com/watch?v=2gEhNzoW7yY

**Comment by Uriel-A** [comment] 2017-12-23 10:02
Here's a visual example of what I'm suggesting:
![legato](https://user-images.githubusercontent.com/34455276/34318794-4f8827ce-e80b-11e7-91ad-36d91af7cd80.PNG)
Do you think this is workable?

**Comment by bontric** [comment] 2017-12-23 15:02
> Here's one software implementation but it's time based.
https://www.youtube.com/watch?v=2gEhNzoW7yY

Thank  you, this actually helped. However: 

> Do you think this is workable?

I'm unsure whether I'm just misunderstanding your suggestion or this can't work. After the second RT (I assume that means retrigger) you only press one note. After that you want 2 more notes played legato while the first is still held. This means for the second and third notes no envelope is triggered. (I don't know what kind of patch you want to work with but from my understanding you'd have 4 individual envelopes). To me it seems like it is not possible to implement this with the Quad-Midi-Module since at the beginning you want to trigger 3 envelopes individually. It seems more like a problem which should be solved by a special quad-envelope module which handles polyphonic legato style playing

**Comment by Uriel-A** [comment] 2017-12-23 17:38
> To me it seems like it is not possible to implement this with the Quad-Midi-Module

I suggested that because I thought it would be more straight forward and easier to implement, but guess not.

> you'd have 4 individual envelopes

I thought that's how it is for the Quad MIDI to CV module? Each gate has to be connected to an individual ADSR module, hence individual envelopes? Or at least that's how I've been connecting them in VCV.

Do you think it is still possible to implement polyphonic legato in VCV? Like I said before, it could also be somewhat emulated by adjusting the ADSR settings. I mean, if I'm the only one you're really hearing talking about polyphonic legato then I don't want to take up your valuable time in trying to implement something that's of very little demand. I'm personally happy enough with what it is right now after the fixes, poly legato is more of an after thought.

Btw, I've also re-compiled and tested your final fixes and can confirm that they're working great. 👍

**Comment by bontric** [comment] 2017-12-24 10:13
> I thought that's how it is for the Quad MIDI to CV module? Each gate has to be connected to an individual ADSR module, hence individual envelopes? Or at least that's how I've been connecting them in VCV.

I meant you as in "in general" not you specifically :wink:  So yes that's the way to do it.

> Do you think it is still possible to implement polyphonic legato in VCV? Like I said before, it could also be somewhat emulated by adjusting the ADSR settings. I mean, if I'm the only one you're really hearing talking about polyphonic legato then I don't want to take up your valuable time in trying to implement something that's of very little demand. I'm personally happy enough with what it is right now after the fixes, poly legato is more of an after thought.

To me it doesn't matter whether it's only one person or a hundred. It's more about the complexity since I'm trying to keep these modules as simple as possible to avoid high maintenance affords.
However, the problem I see here is that this is actually not something I can implement as part of the Midi modules since this also requires special handling by the envelopes.

I tried now to get somewhere near your description and created a patch that uses 5 envelopes (4 for each individual note and a 5th that applies to all). Maybe you can make use of that :) (I love playing around with this kind of things and I'm learning something new, so don't worry about wasting my time!)

[polyLegato1.zip](https://github.com/VCVRack/Rack/files/1584748/polyLegato1.zip)


> Btw, I've also re-compiled and tested your final fixes and can confirm that they're working great. :+1:

Thank's for the feedback! I'm going to fix the pedal bug now as well. It shouldn't be a big deal :)

**Closed** 2017-12-28 14:22 UTC
