### ISSUE TITLE
Linux speex build fails

### ISSUE THREAD

**Issue by LOGUNIVPM** [VCVRack/Rack#1131] opened 2018-11-10 17:42 UTC
It sounds strange and maybe it is a fault of mine, but I can't compile modules that make use of resampling because of a build error of libspeex.

The build log shows:
```
g++ -Wsuggest-override -std=c++11 -DSLUG=ABC -fPIC -I../../include -I../../dep/include -DVERSION=0.6.2 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/ATrivialOsc.cpp.o src/ATrivialOsc.cpp
In file included from ../../dep/include/speex/speexdsp_types.h:122:0,
                 from ../../dep/include/speex/speex_resampler.h:87,
                 from ../../include/dsp/resampler.hpp:5,
                 from ../../include/dsp/decimator.hpp:2,
                 from src/ATrivialOsc.cpp:4:
../../dep/include/speex/speexdsp_config_types.h:12:9: error: ‘int16_t’ does not name a type
 typedef int16_t spx_int16_t;

```
And then a lot of related errors.

The makefile is just:
```
SOURCES = $(wildcard src/*.cpp)
DISTRIBUTABLES += $(wildcard LICENSE*) res

RACK_DIR ?= ../..

include $(RACK_DIR)/plugin.mk
```

Am I missing something?
Thanks guys

Operating system(s): Linux Mint, Rack 0.6.2b from github.

**Comment by cschol** [comment] 2019-02-07 03:49
Is this your own code? Do you have the source somewhere that someone can look at it?

**Comment by leopard86** [comment] 2019-02-07 12:43
Thank you cschol, it is my code but I don't have it online at the moment.
Anyway I just get the error if I have an empty .cpp file that declares a decimator:

`
#include "dsp/decimator.hpp"
#include "myPluginHeader.hpp"


Decimator<2,2> d2;
`

The problem is with speex that says:

`#ifndef __SPEEX_TYPES_H__
#define __SPEEX_TYPES_H__

#if defined HAVE_STDINT_H
#include <stdint.h>
#elif defined HAVE_INTTYPES_H
#include <inttypes.h>
#elif defined HAVE_SYS_TYPES_H
#include <sys/types.h>
#endif

typedef int16_t spx_int16_t;
typedef uint16_t spx_uint16_t;
typedef int32_t spx_int32_t;
typedef uint32_t spx_uint32_t;

#endif
`

Probably in my compile environment none of the HAVE_STDINT_H, HAVE_INTTYPES_H, HAVE_SYS_TYPES_H is defined.

**Comment by Coirt** [comment] 2019-02-07 15:50
I noticed there is no slug or version declared in the makefile might that be the issue?

**Comment by AndrewBelt** [comment] 2019-02-07 18:05
`HAVE_STDINT_H` should be defined by the `./configure` script. What's your compiler version?

**Comment by leopard86** [comment] 2019-02-07 18:15
My version:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 
So probably the speex configure script got something wrong about my system? I see there's a lot of heuristics to find out what system it is...

**Comment by modlfo** [comment] 2019-06-03 18:49
I'm closing this one since it's not a Rack issue per se. This needs to be fixed in the authors code.

**Closed by modlfo** 2019-06-03 18:49 UTC
