### ISSUE TITLE
MIDI input not working in 0.6dev

### ISSUE THREAD

**Issue by PawelHadrian** [VCVRack/Rack#767] opened 2018-03-02 19:34 UTC
## For bug reports:

Operating system, or "all" if known to exist on all three: Linux 4.14.21-1-MANJARO
Version if official Rack release, commit hash and/or branch if from source: master (0.6dev)

MIDI input core plugins are not working. They appear in rack, one is able to select MIDI in devices, MIDI data flow is shown in the terminal but there is no action in Rack.

**Comment by AndrewBelt** [comment] 2018-03-02 19:51
Duplicate of https://github.com/VCVRack/Rack/issues/759

**Closed by AndrewBelt** 2018-03-02 19:51 UTC
