### ISSUE TITLE
Some modules don't render properly

### ISSUE THREAD

**Issue by unfa** [VCVRack/Rack#772] opened 2018-03-04 11:10 UTC
As you can see the texture mapping for the VC Mixer module is wrong:

![selection_255](https://user-images.githubusercontent.com/491704/36944842-40b9cc18-1fa4-11e8-9396-ded08cb3967f.png)

This happens to multiple modules on my system. I haven't done anything special. I've just run `./Rack.sh`.  I wonder if anyone can reproduce this.

Operating system(s):
Linux Mint 18.3
VCV Rack 0.5.1

My GPU is Nvidia GTX 1060, using proprietary Nvidia drivers,
driver version: 384.111.

PS: After restarting Rack it looks fine now. I'll let know if this issue strikes again.

**Comment by AndrewBelt** [comment] 2018-03-04 11:15
duplicate of #461

**Closed by AndrewBelt** 2018-03-04 11:15 UTC
