### ISSUE TITLE
High GPU load on macbook pro (retina display)

### ISSUE THREAD

**Issue by phrolov** [VCVRack/Rack#864] opened 2018-03-29 21:22 UTC
There's so much video card load on my macbookpro (macOS 10.13, intel iris video, retina display, vcvrack 0.6.0) that the fan starts to make noise. It appears already in a blank window with no modules.

**Comment by AndrewBelt** [comment] 2018-03-30 05:09
Not really a concrete issue, and a duplicate of many issues.

**Closed by AndrewBelt** 2018-03-30 05:09 UTC
