### ISSUE TITLE
FR: Please implement a favorites system for the plugins

### ISSUE THREAD

**Issue by Thihi** [VCVRack/Rack#671] opened 2018-02-01 21:25 UTC
With close to 500 different released modules (yay!), that divide into tens of plugins, the module selection menu is becoming unwieldy to use. Since users probably don't end up using every module from every installed plugin, a system for pick'n'mixing all the modules you want to use as favorites would make sense.

A crude implementation could be achieved by for instance by middle or right clicking on a module in the selection menu to toggle favorite status, and showing all favorite modules in a folder at the very top of the plugin listing. This would make building a new patch a lot faster.

**Comment by AndrewBelt** [comment] 2018-02-01 21:28
Duplicate of #452

**Closed by AndrewBelt** 2018-02-01 21:28 UTC
