### ISSUE TITLE
Alpha listing in module browser not in order

### ISSUE THREAD

**Issue by BoscoRemus** [VCVRack/Rack#1413] opened 2019-06-27 17:13 UTC
### Details

Operating system: MAC
Rack version: v1.1.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): Stock graphics card, Behringer UMC1820 audio interface

### Steps to reproduce
Just opened Rack

![Screen Shot 2019-06-27 at 10 03 53 AM](https://user-images.githubusercontent.com/42082512/60285980-a40ef880-98c3-11e9-9f8f-0bfcc939c2e2.png)

**Comment by AndrewBelt** [comment] 2019-06-27 17:17
Duplicate of https://github.com/VCVRack/Rack/issues/1412

**Closed by AndrewBelt** 2019-06-27 17:17 UTC
