### ISSUE TITLE
fonts not working on fundamental modules

### ISSUE THREAD

**Issue by tombburnell** [VCVRack/Rack#689] opened 2018-02-08 11:01 UTC
OS (if applicable): OSX El Capitan
Version (or "dev" if compiling from source): 0.5.1

Hi, just installed and ran for first time and the modules from the fundamental folder have missing fonts. 

![image](https://user-images.githubusercontent.com/426754/35969613-59bf5f04-0cbf-11e8-9210-9fb92423f00f.png)

**Comment by AndrewBelt** [comment] 2018-02-08 11:04
Duplicate of https://github.com/VCVRack/Rack/issues/399

**Closed by AndrewBelt** 2018-02-08 11:04 UTC
