### ISSUE TITLE
Knobs look weird when loading an existing patch

### ISSUE THREAD

**Issue by g-elfling** [VCVRack/Rack#438] opened 2017-11-23 23:05 UTC
OS (if applicable): linux
Version (or "dev" if compiling from source): dev

Knobs and input/output jacks look weird when loading an existing patch. But if I start Rack by ./Rack then the knobs look all 
OK!!! But if I open patch from File->Open then the knobs etc look all weird.

Some knobs are too small and some knobs are too big. In Audible Instruments the knobs are too small. But in SEQ-3 (Fundamental) the knobs are way too big.
All the input/output jacks are too small everywhere.
Oh and I see input/output jacks are "misaligned" in multiples (Audible) for example.

I love VCV Rack and I overcome this problem by "cp bestpatch.vcv autosave.vcv" or open the patch from VCV Rack and wait until it autosaves itself and then restart the program. VCV Rack is the best software I've seen in a long time, thank you for making it!!!!!

I'll post a picture
https://i.imgur.com/HVXjQQy.png

**Comment by Strum** [comment] 2017-11-24 15:26
"VCV Rack is the best software I've seen in a long time, thank you for making it!!!!!"
This ^ several times

**Comment by AndrewBelt** [comment] 2017-11-24 15:46
Duplicate of many threads, too lazy to find.

**Closed by AndrewBelt** 2017-11-24 15:46 UTC

**Comment by g-elfling** [comment] 2017-11-24 18:06
Yes I too tried to find but couldn't find
