### ISSUE TITLE
Two Audio modules hangs Rack

### ISSUE THREAD

**Issue by andrewbernard** [VCVRack/Rack#1745] opened 2020-04-07 09:20 UTC
### Details

Operating system: Windows 10
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
MSI board audio
NVIDIA GeForce GTX 1060 3GB
No MIDI

### Summary
With more than one Audio-8/Audio-16 module, Rack hangs consistently.

### Steps to reproduce
Add two Audio-* modules. Try to delete one. App hangs.

**Comment by AndrewBelt** [comment] 2020-04-07 19:42
Duplicate of https://github.com/VCVRack/Rack/issues/132

**Closed by AndrewBelt** 2020-04-07 19:42 UTC
