### ISSUE TITLE
Re-opening saved patches

### ISSUE THREAD

**Issue by doobiescoo** [VCVRack/Rack#25] opened 2017-09-11 18:17 UTC
On re-opening a saved patch on Windows - all modules were blank but outlines were there, sound was playing although could not modulate anything.

**Comment by AndrewBelt** [comment] 2017-09-11 22:37
Duplicate of #21

**Comment by AndrewBelt** [comment] 2017-09-13 07:21
Fixed with df62f6fc80f72a818c809b0710f8c148e44b4402

**Closed by AndrewBelt** 2017-09-13 07:21 UTC
