### ISSUE TITLE
Windows: Tiny UI elements on High-DPI displays

### ISSUE THREAD

**Issue by cschol** [VCVRack/Rack#491] opened 2017-12-05 23:08 UTC
OS (if applicable): Windows w/High-DPI display (4K)
Version (or "dev" if compiling from source): Dev

The top UI elements are VERY small on high-DPI displays (e.g. 4K). The modules can be zoomed in to be able to work with them, but the rest of the UI elements, incl. dialog boxes are still tiny.

This was also reported on the MuffWiggler forum in this [post](https://www.muffwiggler.com/forum/viewtopic.php?t=186899&start=325).

@AndrewBelt I have a high-DPI display (4K), that I can use to test. If you either have a patch I can test or tell me where to start looking in the code, I am happy to check this out.

**Comment by AndrewBelt** [comment] 2017-12-05 23:40
Duplicate of #89

**Closed by AndrewBelt** 2017-12-05 23:40 UTC
