### ISSUE TITLE
Parameter values jump when moved with mouse

### ISSUE THREAD

**Issue by yobink** [VCVRack/Rack#1367] opened 2019-06-20 14:49 UTC
<--
To file a bug report, fill out the form below.
Use a descriptive title that best explains the bug in one sentence.
Attach screenshots if the bug is visual.
Attach your `<Rack user folder>/log.txt` file if something is crashing or not loading.
Surround terminal output with three tildes
```
like this.
```
-->

### Details

Operating system: Windows 10 Pro
Rack version: v1.0.0
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Lenovo W540 laptop, Windows HD Graphics 4600 graphics card, USB Headphones

### Expected behavior

Click a control to change a value and the value starts with where you click and you can change the value from that point

### Actual behavior

Click a control to change a value and the value immediately jumps to full value in one direction (up or down, not consistent)

**Comment by Coirt** [comment] 2019-06-20 15:28
Any particular module doing this? 

Might be helpful to record the behaviour with VCV-Recorder which is available on the Plugin Library:
https://vcvrack.com/plugins.html#rec
Or you could use LICECap to record a gif.
https://www.cockos.com/licecap/

You right click the recorder module to set it to video, it records inner window of VCV

**Comment by yobink** [comment] 2019-06-20 17:35
No specific modules, it’s all over the place and quite random. Seems it’s not just me re forum thread. I will try to screen cap it. Thanks

**Comment by ciwolsey** [comment] 2019-06-23 21:26
Having the same issue. It only happens when "View->Lock Cursor While Dragging" is enabled so it must be related to that?

**Comment by ciwolsey** [comment] 2019-06-23 21:32
I managed to get a video of it:
https://www.youtube.com/watch?v=xpXhcvdU67g&feature=youtu.be
I have the option turned off and it's fine, then I turn it on and make small movements but you see large changes in the knob. Throughout the video I'm only ever making small changes. You can also notice my cursor position being forced to other random locations.

**Comment by yobink** [comment] 2019-06-23 21:34
Nice find I will try that later. Thanks!

**Comment by Coirt** [comment] 2019-06-23 22:08
@ciwolsey do you have mouse acceleration turned on or off? In mouse settings Mouse > Pointer Options > Enhance pointer precision

**Comment by ciwolsey** [comment] 2019-06-23 22:25
@Coirt No, acceleration/ehanced precision is disabled.
It seems that the problem is worse the further the knob is from the center of the window. I've also noticed that sometimes the mouse is moved to the centre of the window when locking is on.

**Comment by Coirt** [comment] 2019-06-23 22:44
Can't reproduce that behaviour myself. 

Are you both using mice or touchpads.

**Comment by ciwolsey** [comment] 2019-06-23 22:57
Mouse.

**Comment by yobink** [comment] 2019-06-24 04:25
Turning off Lock cursor while dragging fixed the issue for me. Well done thanks

**Comment by gsynuh** [comment] 2019-06-24 07:15
Sharing a way to reproduce the issue as stated on the fb group by Kristo and summarized (https://www.facebook.com/groups/vcvrack/permalink/368009660525851/?comment_id=368111293849021&comment_tracking=%7B%22tn%22%3A%22R%22%7D)

Knobs :
1. place mouse out of a knob area - top right . mouse buttons not pressed
2. move mouse to the bottom left , over the knob area, until you go outside the area
3. during the movement, once somewhere over the knob, press the left mouse button to catch the knob
4. knob will be caught during the movement and its position will jump quickly to an unwanted position

Faders : 
1. same approach, try on big fader, a downwards movement was tried for this reproducible case
2. A modulation of the control seems to lessen the effect


Midi map jump : I don't know if this is related or if its just a case of value "takeover"

**Comment by Coirt** [comment] 2019-06-25 03:51
Can't reproduce with the above. I'm on Windows 7 though, so this could just be a Windows 10 thing.

If you's can reproduce it regular, there is a few things you might want to try to rule them out.

1. If you can Rollback the mouse driver do so.
2. Update to latest driver.
3. Reinstall the mouse driver, on different port.
4. End Realtek audio.exe if it is running and not being used with Rack.
5. Get the latest GPU updates.
6. Try another mouse if you have one.

**Comment by stoermelder** [comment] 2019-06-29 18:42
I have this behavior too, but haven’t yet identified any pattern.

**Comment by stoermelder** [comment] 2019-06-29 20:53
Ok, I notice these jumps often when moving more horizontically while clicking on a parameter. I started debugging using GDB and noticed huge values of `mouseDelta.y` (200-300) when it happens.
https://github.com/VCVRack/Rack/blob/266b63d5aa7a952ce17b2d6170d51549fcdbd6c9/src/window.cpp#L124

**Comment by AndrewBelt** [comment] 2019-06-29 21:38
Probably a result of GLFW warping the mouse when toggling between `glfwSetInputMode(win, GLFW_CURSOR, GLFW_CURSOR_DISABLED);` and `glfwSetInputMode(win, GLFW_CURSOR, GLFW_CURSOR_NORMAL);`.

**Comment by jonheal** [comment] 2019-07-18 16:45
> Probably a result of GLFW warping the mouse when toggling between `glfwSetInputMode(win, GLFW_CURSOR, GLFW_CURSOR_DISABLED);` and `glfwSetInputMode(win, GLFW_CURSOR, GLFW_CURSOR_NORMAL);`.

Any chance this is fixed in your next release? It's really crippling on Windows 10.

**Comment by AndrewBelt** [comment] 2019-07-18 17:28
I can't reproduce the issue. I can accept code patch suggestions though.

**Comment by jonheal** [comment] 2019-07-18 18:34
I am not a C++ programmer, so I would have no idea what to suggest. I can make a screen capture of it happening if that is helpful. It happens on both of my Windows 10 machines.

**Comment by jonheal** [comment] 2019-07-18 19:29
Here is a link to a video of this issue. It doesn't happen with every mouse action. It might happen two or three times in a row and then not occur for the next ten mouse actions. I can't detect a pattern. In the video, all mouse actions I took were to more knobs minimally, but you can see them jump from time to time.

https://1drv.ms/u/s!Asy9MQ3kIBNQgb057uVFpOlw7AW1_w

**Comment by AndrewBelt** [comment] 2019-08-07 20:27
Has no one reproduced and solved this yet?

**Comment by jonheal** [comment] 2019-08-07 20:39
I wish!

I think lots have folks have reproduced it. Benjamin Dill (PackOne/stoermelder) had offered his guess as a place to possibly look.

--
Jon Heal
Have a nice day!

**Comment by ciwolsey** [comment] 2019-08-07 21:51
And I've posted a video of the issue but don't have experience to
investigate it

**Comment by stoermelder** [comment] 2019-08-08 06:32
> Has no one reproduced and solved this yet?

I can force it happen quite often, but only if the widget is in the upper screen half, never if the widget is in the lower screen half. Important is to move the mouse while clicking on the parameter widget.

![1367](https://user-images.githubusercontent.com/47640667/62680215-ffe69a00-b9b6-11e9-8b06-d9e31bc65314.gif)

**Comment by ciwolsey** [comment] 2019-08-08 07:26
I happens anywhere on the screen for me but the further I'm zoomed in the more subtle the problem becomes. Try zooming out to see if it makes the problem worse.

**Comment by stoermelder** [comment] 2019-08-08 09:17
@AndrewBelt I think I was able to fix it:
If I ignore the first value of `mouseDelta` in `cursorPosCallback` 
https://github.com/VCVRack/Rack/blob/56e0ce0f79874c03f200b29f0859e75a0160c1d8/src/window.cpp#L124
after `Window::cursorLock` was executed https://github.com/VCVRack/Rack/blob/56e0ce0f79874c03f200b29f0859e75a0160c1d8/src/window.cpp#L468
I can't get the parameters jumping anymore.

**Comment by jonheal** [comment] 2019-08-08 13:40
BTW, Ben, I can get parameter values to jump on knobs int he lower half of the screen, but interestingly, within the top half of the screen, they seem to jump clockwise. Within the bottom half, counter-clockwise.

**Comment by jonheal** [comment] 2019-08-09 23:15
I think I can confirm with certainty that above the centerline of the monitor, knobs jump clockwise approximately 50% of their value. Below the centerline, they jump counterclockwise the same amount.

**Comment by AndrewBelt** [comment] 2019-08-10 16:48
@stoermelder If you debug in in `cursorPosCallback` with something like
```cpp
		DEBUG("%f %f", VEC_ARGS(mouseDelta));
```
can you post an example of the "huge jump" in the terminal?

**Comment by stoermelder** [comment] 2019-08-10 18:02
@AndrewBelt If you need more please let me know.
[cursorPosCallback.txt](https://github.com/VCVRack/Rack/files/3489184/cursorPosCallback.txt)

**Comment by AndrewBelt** [comment] 2019-08-10 18:11
Those negative coordinates are unusual. Do you have two monitors? Perhaps `cursorLock` is warping your cursor to the other screen.

**Comment by stoermelder** [comment] 2019-08-10 18:15
No, just one (laptop) screen, nothing special here. The module was in the top right corner of the screen while generating the output.

**Comment by AndrewBelt** [comment] 2019-08-10 18:23
Okay, the bug here is clearly "GLFW is warping to negative coordinates rather than the original mouse position." Let's try your workaround.
What is your OS?

**Comment by stoermelder** [comment] 2019-08-10 18:30
Windows 10, latest release 1903.

**Comment by AndrewBelt** [comment] 2019-08-10 18:32
Okay, try Okay, here's the contract to formalize the agreement. If everything looks fine, sign and return, or acknowledge over email that you agree, and you can send me your plugins.

Make sure you copy the EULA (https://vcvrack.com/eula.md) to your plugin package.

When a plugin is ready, I'll need:
- the plugin slug
- ZIP package for each architecture, using `make dist`
- price (USD), highly recommended to round to the nearest $5
- a small thumbnail screenshot for the checkout page. It doesn't need to be perfect, just something so people can make sure they've added the correct product to their cart.

The VCV Administrator Dashboard is at https://vcvrack.com/admin.html when your plugins have launched. Give me all the VCV account email addresses you wish to have access to this dashboard.

After I send this quarter's sales report, you can give me your desired payout method (TransferWire, Xoom, PayPal, etc).

**Comment by AndrewBelt** [comment] 2019-08-10 18:32
Okay, try 2bc7c82fc14c38cc21d3689a54ed013f0a202a43

**Comment by stoermelder** [comment] 2019-08-10 18:42
Works here flawlessly without any jumps. Your workaround is more or less how I it did it while testing.

**Comment by AndrewBelt** [comment] 2019-08-10 18:46
Thanks!

**Closed by AndrewBelt** 2019-08-10 18:46 UTC

**Comment by stoermelder** [comment] 2019-08-10 18:55
You're welcome!
Maybe you want to remove the debug output:
https://github.com/VCVRack/Rack/blob/2bc7c82fc14c38cc21d3689a54ed013f0a202a43/src/window.cpp#L133

**Comment by rubyglow** [comment] 2019-09-02 06:11
I'm sorry to say that on my Mac I'm still experiencing this bug after upgrading to Rack 1.1.4 :-(

**Comment by rubyglow** [comment] 2019-09-11 16:20
Hi @AndrewBelt 
Would you please reopen #1367 ? Unfortunately the bug is still present in MacOS 10.12.6 (Sierra) even after it was supposed to be fixed in Rack 1.1.4.
Thanks!

**Comment by AndrewBelt** [comment] 2019-09-11 16:51
@rubyglow Open a new issue. Since the problem was solved for some users, we need to filter the details to those having the problem with 1.1.4.

**Comment by jonheal** [comment] 2019-09-11 17:20
If Lars opens a new issue, I _may_ contribute to it. I don't know. Twice since 1.1.4, _I think_ a knob has jumped on me, but I'm not positive it wasn't the result of errant double-clicks.

**Comment by rubyglow** [comment] 2019-09-15 13:04
I've re-opened it on #1553
