### ISSUE TITLE
Rack is stopped from opening by OS on MacOS 10.14.6

### ISSUE THREAD

**Issue by maondoza** [VCVRack/Rack#1469] opened 2019-07-10 10:37 UTC
### Details

Operating system: MacOS 10.14.6 Beta (18G59b)
Rack version: v1.1.1
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device): n/a

### Summary
When I downloaded the newest version of Rack, I couldn't open the application, with the OS giving the error that ""Rack" can’t be opened because Apple cannot check it for malicious software." I can force the app to open by overriding the security settings (i.e. control-right clicking and selecting Open in the context menu), but this still seems like an issue that should be fixed. Since the application itself is prevented from launching by this issue, it creates no log.

**Comment by SmoothSailingMusic** [comment] 2019-07-11 00:18
10.14.6 user here. This only happens the first time its opened. I don't know if there is any way to circumvent that

**Comment by lnikj** [comment] 2019-07-16 06:11
https://github.com/VCVRack/Rack/issues/1369

**Comment by AndrewBelt** [comment] 2019-07-16 06:17
Yes, duplicate of many issues, and also solved in ef6e46731e3517737910feb41cb70eb18e1b3dfd

**Closed by AndrewBelt** 2019-07-16 06:17 UTC
