### ISSUE TITLE
Red Dot problem due to renamed plugins

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Rack#554] opened 2017-12-25 01:31 UTC
OS (if applicable): Win 7
Version (or "dev" if compiling from source): 0.5.1

Hi Andrew,

I tried to eliminate my "red-dot" plugins, and ended up with nothing but Console. Still having the red dot reappearing. I deleted autosave and settings and all files in the plugins directory, as well as unselecting all plugins in the plugin manager. Is there anything else I can do, or is this at a problem at your end?

(not expecting any response till after Xmas... You should take your deserved time off.)

Martin

**Comment by AndrewBelt** [comment] 2017-12-25 01:42
Can't reproduce. Is Console being redownloaded when you click Update Plugins? Are there any details in the log.txt file?

**Comment by martin-lueders** [comment] 2017-12-25 11:40
Hi Andrew,

Thanks for suggesting the log file. In fact, it showed that Console is NOT the problem. It simply was the last one,  I could not delete from my plugin manager.

The problem is related to the Autodafe plugins, and in particular that he changed the name of the manifests. I unselected the current ones:

Autodafe - REDs FREE (Autodafe - REDs FREE.json)
Autodafe Drum Kit (Autodafe-DrumKit.json)
Autodafe Module Pack (Autodafe.json)

However, my database entry on your server still has a link to the old versions. My log file shows:

[warning] Plugin sync error: AutodafeREDsFREE not found in community
[warning] Plugin sync error: AutodafeDrumKit not found in community
[warning] Plugin sync error: AutodafeModulePack not found in community

I don't think I can delete them from my account. This also might be the case for other users.

Cheers,
Martin

**Comment by martin-lueders** [comment] 2017-12-25 11:43
I just checked the command:

https://api.vcvrack.com/plugins?version=0.5.1&token=M0SbcMWHOYajafmXEcY1

and the result is:

{"plugins":["AutodafeREDsFREE","AutodafeDrumKit","AutodafeModulePack","mental","PvC","RODENTMODULES","VCV-Console"]}

However, in the plugin manager I have only Console selected. Maybe it would be useful to have a function to clean ones plugin selection, so one can solve these sort of problems.

**Comment by AndrewBelt** [comment] 2018-05-20 22:57
Closing since the Plugin Manager has been redesigned.

**Closed by AndrewBelt** 2018-05-20 22:57 UTC
