### ISSUE TITLE
Addition of Keystrokes

### ISSUE THREAD

**Issue by nstottlemyer** [VCVRack/Rack#453] opened 2017-11-25 03:00 UTC
OS (if applicable): macOS 10.12
Version (or "dev" if compiling from source):

To increase workflow, utilization of system keystrokes would be helpful.

**Comment by AndrewBelt** [comment] 2017-11-25 04:37
Closing, not a concrete feature request

**Closed by AndrewBelt** 2017-11-25 04:37 UTC

**Comment by nstottlemyer** [comment] 2017-11-30 19:13
Thanks, Andrew. Specifically, I'm asking for ctrl/cmd+z and shift+ctrl/cmd+z for undo and redo, respectively, allowing the user undo/redo last actions.

**Comment by AndrewBelt** [comment] 2017-11-30 19:13
Then, duplicate of #153

**Comment by nstottlemyer** [comment] 2017-11-30 19:16
Yes, thanks. Sorry for the repeat.
