### ISSUE TITLE
Rack doesn't open at all 

### ISSUE THREAD

**Issue by windkrieg** [VCVRack/Rack#593] opened 2018-01-06 00:22 UTC
OS (if applicable): Windows 10 pro 64bit
Version (or "dev" if compiling from source): 0.5.1 windows 

I just installed Rack, and it wont open.
nothing whatsoever.
no logs in the program directory, no errors, nothing.
any reason why?

**Comment by AndrewBelt** [comment] 2018-05-20 19:34
Cannot reproduce, closing. Is this fixed in Rack 0.6.0?

**Closed by AndrewBelt** 2018-05-20 19:34 UTC

**Comment by slaattnes** [comment] 2019-02-24 13:53
I have the same issue with Rack 0.6.2c on Windows 10 64-bit with Intel HD Graphics 4000
