### ISSUE TITLE
V1.1 save file window issues

### ISSUE THREAD

**Issue by Eurikon** [VCVRack/Rack#1418] opened 2019-06-28 09:38 UTC
Rack 1.1.0
Windows 10 / 64

the file save window show no files that were saved earlier.
also in the file extension dropdown there is some random weird characters, see screenshot.

![v1-1-filesaveerror](https://user-images.githubusercontent.com/40998416/60333396-30d7b600-9999-11e9-9625-d72344897632.jpg)

**Comment by mschack** [comment] 2019-06-28 16:29
Did you by chance have the latest temp build of mscHack installed?  I just started getting info that if you remove mscHack the problem goes away, though this hasn't been confirmed yet.

**Comment by ajbmorris** [comment] 2019-06-28 16:33
Having the same problem here while using the latest temp mscHack - windows10pro64 Rack 1.1.0

**Comment by ajbmorris** [comment] 2019-06-28 16:38
creating a new patch from the default template seems to make the patches appear again in the open file dialog

**Comment by Petervos2018** [comment] 2019-06-28 16:54
> creating a new patch from the default template seems to make the patches appear again in the open file dialog

This does not last ! patches disappear again after you saved a file closed rack and start it up again, it also has nothing to do with mschack AFAIK

**Comment by Eurikon** [comment] 2019-06-28 17:40
> 
> 
> Did you by chance have the latest temp build of mscHack installed? I just started getting info that if you remove mscHack the problem goes away, though this hasn't been confirmed yet.

@mschack 
Hi mate, yes i did have a latest temp that was linked in FB group (it is gone now that post).

I can not confirm that this issue is because of your plugin, however now that i have removed the plugin the save file windows appears to be working normal.

This issue here:
https://github.com/VCVRack/Rack/issues/1419
is linked to your plugin though.

**Comment by mschack** [comment] 2019-06-28 17:52
thanks for the info @Eurikon

**Comment by Eurikon** [comment] 2019-06-28 18:11
> not sure that it's mscHack related though - just removed folder from the plugins folder and still happens with no other mscHack modules present. <

this i can confirm.

but it happens erratically, sometimes on save (not save as) there are no files shown.
then only on "open file" the garbled text is in the file extension filter.
and then again all appears to look and function normal in the file window.

**Comment by Rcomian** [comment] 2019-06-28 18:20
Yep, I can reproduce this with a clean vcv rack v1.1, empty patch, logged out of the website and with no modules installed (apart from the bundled Fundamental and Core).

**Comment by AndrewBelt** [comment] 2019-06-28 19:14
Duplicate of https://github.com/VCVRack/Rack/issues/1407

**Closed by AndrewBelt** 2019-06-28 19:14 UTC
