### ISSUE TITLE
Macro's a-la Reaktor

### ISSUE THREAD

**Issue by marcoose777** [VCVRack/Rack#1201] opened 2019-02-15 18:35 UTC
Hi Andrew,
First off thanks for the terrific project that is VCV Rack. 
I have a feature request, while I understand you're very busy with version 1 release bug fixes, but if it hasn't already been suggested I 'd like to request a macro feature similar to that found in early Reaktor versions (version 3ish: all those years ago), whereby a group of modules that perform a common task can be placed inside a container, and edited as a distinct module with inputs/outputs to facilitate signal flow: cv, midi or audio. This could be a good way to hide complexity, and make complex networks easier to manage/reason.

**Comment by thealienthing** [comment] 2019-02-15 20:21
Sounds like an interesting idea. Seems like a feature that’s practical enough. I’ve never had a physical modular synth, so I wonder if those who do have them will sometimes combine modules into one “black box” model and hide all the details. Would you want to have macro knobs that could be routed to different controls hidden under the hood?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AndrewBelt** [comment] 2019-02-15 22:14
Duplicate of #655

**Comment by AndrewBelt** [comment] 2019-02-15 22:15
@thealienthing Please remove your signature from your git client so you are not advertising other companies on this issue tracker.

**Closed by AndrewBelt** 2019-02-15 22:14 UTC
