### ISSUE TITLE
Problems when using Expert Sleepers ES-8 as audio interface with second bank of channels

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [VCVRack/Rack#930] opened 2018-04-26 21:03 UTC
Operating system: macOS 10.13.4
Version: 0.6.0

Setup is: Expert Sleepers ES-8 linked via ADAT to ES-3.
<img width="657" alt="vcv expert" src="https://user-images.githubusercontent.com/15206/39331955-fff90cda-4973-11e8-9675-dcddbdecdc80.png">
<img width="703" alt="vcv es8 audio midi" src="https://user-images.githubusercontent.com/15206/39331976-0d92b08a-4974-11e8-908c-0e3074517fd0.png">

- second bank of Inputs not illuminated and won't send CV
- trying to delete or change device on second bank freezes VCV
- sometimes multiple ES-8 devices appear: 
<img width="855" alt="extra dev" src="https://user-images.githubusercontent.com/15206/39332195-bcb6d078-4974-11e8-90ae-2a0910c8920b.png">
- creating an audio module for the second bank of channels works - but then creating an audio module for the first exhibits same behavior.

Log:
```
[0.002 info] Rack 0.6.0
[0.002 info] Current working directory: /
[0.002 info] Global directory: /Applications/Rack.app/Contents/Resources/
[0.002 info] Local directory: /Users/jon/Documents/Rack/
[0.003 info] Loaded plugin /Users/jon/Documents/Rack/plugins/com-soundchasing-stochasm/plugin.dylib
[0.005 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Bogaudio/plugin.dylib
[0.006 info] Loaded plugin /Users/jon/Documents/Rack/plugins/SynthKit/plugin.dylib
[0.007 info] Loaded plugin /Users/jon/Documents/Rack/plugins/LOGinstruments/plugin.dylib
[0.009 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Valley/plugin.dylib
[0.009 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Grayscale/plugin.dylib
[0.010 info] Loaded plugin /Users/jon/Documents/Rack/plugins/modular80/plugin.dylib
[0.012 info] Loaded plugin /Users/jon/Documents/Rack/plugins/MrLumps/plugin.dylib
[0.014 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Befaco/plugin.dylib
[0.015 info] Loaded plugin /Users/jon/Documents/Rack/plugins/AmalgamatedHarmonics/plugin.dylib
[0.016 info] Loaded plugin /Users/jon/Documents/Rack/plugins/s-ol/plugin.dylib
[0.018 info] Loaded plugin /Users/jon/Documents/Rack/plugins/FrozenWasteland/plugin.dylib
[0.019 info] Loaded plugin /Users/jon/Documents/Rack/plugins/DrumKit/plugin.dylib
[0.021 info] Loaded plugin /Users/jon/Documents/Rack/plugins/dBiz/plugin.dylib
[0.023 info] Loaded plugin /Users/jon/Documents/Rack/plugins/moDllz/plugin.dylib
[0.025 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Gratrix/plugin.dylib
[0.026 info] Loaded plugin /Users/jon/Documents/Rack/plugins/luckyxxl/plugin.dylib
[0.028 info] Loaded plugin /Users/jon/Documents/Rack/plugins/DHE-Modules/plugin.dylib
[0.030 info] Loaded plugin /Users/jon/Documents/Rack/plugins/ImpromptuModular/plugin.dylib
[0.032 info] Loaded plugin /Users/jon/Documents/Rack/plugins/SonusModular/plugin.dylib
[0.034 info] Loaded plugin /Users/jon/Documents/Rack/plugins/mtsch-plugins/plugin.dylib
[0.036 info] Loaded plugin /Users/jon/Documents/Rack/plugins/ArableInstruments/plugin.dylib
[0.039 info] Loaded plugin /Users/jon/Documents/Rack/plugins/BaconMusic/plugin.dylib
[0.041 info] Loaded plugin /Users/jon/Documents/Rack/plugins/mental/plugin.dylib
[0.043 info] Loaded plugin /Users/jon/Documents/Rack/plugins/JW-Modules/plugin.dylib
[0.046 info] Loaded plugin /Users/jon/Documents/Rack/plugins/TheXOR/plugin.dylib
[0.049 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Fundamental/plugin.dylib
[0.051 info] Loaded plugin /Users/jon/Documents/Rack/plugins/ESeries/plugin.dylib
[0.053 info] Loaded plugin /Users/jon/Documents/Rack/plugins/AudibleInstruments/plugin.dylib
[0.056 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Ohmer/plugin.dylib
[0.058 info] Loaded plugin /Users/jon/Documents/Rack/plugins/RJModules/plugin.dylib
[0.062 info] Loaded plugin /Users/jon/Documents/Rack/plugins/trowaSoft/plugin.dylib
[0.065 info] Loaded plugin /Users/jon/Documents/Rack/plugins/LindenbergResearch/plugin.dylib
[0.068 info] Loaded plugin /Users/jon/Documents/Rack/plugins/PulsumQuadratum-shift/plugin.dylib
[0.072 info] Loaded plugin /Users/jon/Documents/Rack/plugins/ParableInstruments/plugin.dylib
[0.075 info] Loaded plugin /Users/jon/Documents/Rack/plugins/CharredDesert/plugin.dylib
[0.079 info] Loaded plugin /Users/jon/Documents/Rack/plugins/AS/plugin.dylib
[0.083 info] Loaded plugin /Users/jon/Documents/Rack/plugins/PvC/plugin.dylib
[0.086 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Alikins/plugin.dylib
[0.090 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Southpole/plugin.dylib
[0.094 info] Loaded plugin /Users/jon/Documents/Rack/plugins/Southpole-parasites/plugin.dylib
[0.097 info] Loaded plugin /Users/jon/Documents/Rack/plugins/NauModular/plugin.dylib
[0.101 info] Loaded plugin /Users/jon/Documents/Rack/plugins/wizardishungry-vcvrack/plugin.dylib
[0.106 info] Loaded plugin /Users/jon/Documents/Rack/plugins/NYSTHI/plugin.dylib
[0.111 info] Loaded plugin /Users/jon/Documents/Rack/plugins/HetrickCV/plugin.dylib
[0.115 info] Loaded plugin /Users/jon/Documents/Rack/plugins/ML_modules/plugin.dylib
[0.216 info] Bridge server started
[0.652 info] Loaded font /Applications/Rack.app/Contents/Resources/res/fonts/DejaVuSans.ttf
[0.652 info] Loading settings /Users/jon/Documents/Rack/settings.json
[0.653 info] Saving settings /Users/jon/Documents/Rack/settings.json
[0.653 info] Loading patch /Users/jon/Documents/Rack/autosave.vcv
[0.700 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/Core/AudioInterface.svg
[0.701 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/ScrewSilver.svg
[0.701 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/PJ301M.svg
[0.701 info] Loaded font /Applications/Rack.app/Contents/Resources/res/fonts/ShareTechMono-Regular.ttf
[0.705 info] Opening audio RtAudio device 3 with 8 in 8 out
[0.707 info] Starting RtAudio stream 3
[0.707 info] Loaded SVG /Users/jon/Documents/Rack/plugins/Fundamental/res/LFO-2.svg
[0.707 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/CKSS_0.svg
[0.708 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/CKSS_1.svg
[0.708 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/RoundHugeBlackKnob.svg
[0.708 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/RoundLargeBlackKnob.svg
[0.754 info] Opening audio RtAudio device 3 with 4 in 8 out
[0.757 info] Starting RtAudio stream 3
[0.757 info] Loaded SVG /Users/jon/Documents/Rack/plugins/Fundamental/res/Scope.svg
[0.758 info] Loaded font /Users/jon/Documents/Rack/plugins/Fundamental/res/fonts/Sudo.ttf
[0.758 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/RoundBlackKnob.svg
[0.758 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/CKD6_0.svg
[0.758 info] Loaded SVG /Applications/Rack.app/Contents/Resources/res/ComponentLibrary/CKD6_1.svg
[0.858 debug] Audio Interface IO underflow
[1.065 debug] Audio Interface IO underflow
[15.833 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[15.842 info] Saving settings /Users/jon/Documents/Rack/settings.json
[26.563 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[26.563 info] Saving settings /Users/jon/Documents/Rack/settings.json
[36.866 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[36.867 info] Saving settings /Users/jon/Documents/Rack/settings.json
[47.213 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[47.213 info] Saving settings /Users/jon/Documents/Rack/settings.json
[57.565 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[57.565 info] Saving settings /Users/jon/Documents/Rack/settings.json
[67.928 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[67.928 info] Saving settings /Users/jon/Documents/Rack/settings.json
[78.310 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[78.310 info] Saving settings /Users/jon/Documents/Rack/settings.json
[88.690 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[88.700 info] Saving settings /Users/jon/Documents/Rack/settings.json
[99.661 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[99.661 info] Saving settings /Users/jon/Documents/Rack/settings.json
[110.029 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[110.029 info] Saving settings /Users/jon/Documents/Rack/settings.json
[120.379 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[120.380 info] Saving settings /Users/jon/Documents/Rack/settings.json
[130.712 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[130.713 info] Saving settings /Users/jon/Documents/Rack/settings.json
[141.033 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[141.034 info] Saving settings /Users/jon/Documents/Rack/settings.json
[151.365 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[151.366 info] Saving settings /Users/jon/Documents/Rack/settings.json
[161.721 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[161.722 info] Saving settings /Users/jon/Documents/Rack/settings.json
[172.079 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[172.080 info] Saving settings /Users/jon/Documents/Rack/settings.json
[182.422 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[182.422 info] Saving settings /Users/jon/Documents/Rack/settings.json
[192.766 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[192.766 info] Saving settings /Users/jon/Documents/Rack/settings.json
[203.124 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[203.124 info] Saving settings /Users/jon/Documents/Rack/settings.json
[213.429 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[213.435 info] Saving settings /Users/jon/Documents/Rack/settings.json
[223.808 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[223.808 info] Saving settings /Users/jon/Documents/Rack/settings.json
[236.364 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[236.365 info] Saving settings /Users/jon/Documents/Rack/settings.json
[246.679 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[246.679 info] Saving settings /Users/jon/Documents/Rack/settings.json
[257.007 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[257.008 info] Saving settings /Users/jon/Documents/Rack/settings.json
[267.343 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[267.344 info] Saving settings /Users/jon/Documents/Rack/settings.json
[277.656 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[277.656 info] Saving settings /Users/jon/Documents/Rack/settings.json
[287.971 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[287.972 info] Saving settings /Users/jon/Documents/Rack/settings.json
[298.252 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[298.260 info] Saving settings /Users/jon/Documents/Rack/settings.json
[308.558 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[308.559 info] Saving settings /Users/jon/Documents/Rack/settings.json
[318.924 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[318.924 info] Saving settings /Users/jon/Documents/Rack/settings.json
[329.332 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[329.333 info] Saving settings /Users/jon/Documents/Rack/settings.json
[339.735 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[339.736 info] Saving settings /Users/jon/Documents/Rack/settings.json
[351.875 info] Saving patch /Users/jon/Documents/Rack/autosave.vcv
[351.876 info] Saving settings /Users/jon/Documents/Rack/settings.json
[353.580 info] Stopping RtAudio stream 3
[353.598 info] Closing RtAudio stream 3
[356.192 info] Stopping RtAudio stream 3

```

**Comment by thopa** [comment] 2018-04-29 00:42
I have the same problem, ended up using the es8 with reaktor and the es3-6-7 with vcv.
When changing to out 9-16 on second audio device vrack crashes

**Comment by dapead** [comment] 2018-05-09 20:01
Can be reproduced with  Soundflower in 64-channel mode if you don't have an ES-8 to hand  - only one Audio module at a time will work so you can't use more than 8 channels. Guessing this is a generic problem with any device with >8 ins or outs, and probably aggregate devices too.

The docs do warn about the flakiness of >1 Audio module. Real solution seems to be supporting >8 channels on the Audio module and/or some kind of mapping facility. I think there's already an issue about that.

NB: Even though the ES-8 is 4-in, 8-out it supports expansion modules so it "advertises" 12 in/16 out. My problem is that I want to aggregate it with the device driving my speakers, so they get bumped up to ports #17/18

**Comment by Torinbob** [comment] 2018-11-02 22:20
There is now an Audio 16 plugin module (16 channels of in/out) which should find its way to the plugin manager very soon.

**Comment by WIZARDISHUNGRY** [comment] 2018-11-11 15:49
https://github.com/Rcomian/rcm-modules

**Comment by modlfo** [comment] 2019-06-04 20:55
Closing as this issue since Rack v1 will include an Audio module with 16 I/O.

**Closed by modlfo** 2019-06-04 20:55 UTC
