### ISSUE TITLE
Move all cables connected to an output in one single operation

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Rack#1835] opened 2020-08-29 12:40 UTC
### Summary

The ability to move all cables connected to an output in one single movement. For example, output _A_ has 4 cables connected to it, and we want to move all 4 of them to output _B_ in a single UI operation.

### Motivation

There could be many different cases when this can be useful, but one in particular could be when sending an oscillator output, for example the triangle out, to many destinations, we could then want to change all cables to the square output to change the sound. Although this feature request may seem minor, it can be a nice shortcut for power users while also being invisible and not a burden on novice users.

### Proposed design

One possible implementation would be to allow SHIFT clicking of the output port to accomplish this. 
Currently, the following behaviors are oberved when clicking output ports:

* Normal click: move the top-most cable (or start a cable if none present)
* CTRL click: start a new cable on the port (whether port has existing cable(s) or not)
* SHIFT click: same as Normal click
* CTRL+SHIFT click: same as Normal click

Unless these last two modifiers are to be reserved for future use, there could be some room to get more advanced use here. SHIFT click of an output could then be a small variation on the normal click of an output, such that it becomes:

* SHIFT click: move all cables (or start a cable if none present)

I can't think of any cases where this might fail, and perhaps as an alternative shortcut, it could be the CTRL+SHIFT-click instead of just SHIFT-click, if ever SHIFT-click is to be reserved for something else.

**Comment by AndrewBelt** [comment] 2020-08-29 18:16
Can't comment on the proposal yet, but just want to say that this is an example of a great-quality feature request!

**Comment by anlexmatos** [comment] 2020-10-11 08:26
Duplicate of #1482 which is less detailed, but with more reactions.

**Comment by AndrewBelt** [comment] 2020-10-11 13:25
Duplicate of https://github.com/VCVRack/Rack/issues/1482

**Closed by AndrewBelt** 2020-10-11 13:25 UTC
