### ISSUE TITLE
VCV ''SAVE AS'' issue

### ISSUE THREAD

**Issue by Dimitispapadosa** [VCVRack/Rack#763] opened 2018-02-28 17:41 UTC
i have a saving issue. I use vcv 0.5.1 version. 
Firstly if i save a rack that contains fundamentals modules i cannot open the project. It appears an error and it says that ''Could not find a plugin ''Fundamental'' module...
Second problem is that if i save a rack with any other module i can open the project BUT after that it doesnt seem to work properly because screen not appear many info and also the list with the modules dont open 
![unsatitled](https://user-images.githubusercontent.com/36930540/36803024-26a5bc2a-1cbf-11e8-809e-23dae5d62031.png)

**Comment by Coirt** [comment] 2018-02-28 19:18
Are you opening a patch from an earlier version by any chance? Try add .vcv at the end of the patch name
e.g. YourPatch.vcv

**Comment by AndrewBelt** [comment] 2018-02-28 19:19
The cause of this is that the Save As dialog sets the current working directory on some Windows configurations. I cannot reproduce this on mine.

**Comment by Dimitispapadosa** [comment] 2018-02-28 19:47
Thanks for responding guys. 
I tried ''.vcv''  at the end of the rack name but it didnt work.
I just found though an other way to do that. If i am in a new rack project and click ''open''  i am choosing the project that i want and it opens it without any errors.

**Comment by AndrewBelt** [comment] 2018-05-20 19:31
Should be fixed in  2fa3db4

**Closed by AndrewBelt** 2018-05-20 19:31 UTC
