### ISSUE TITLE
Feature Request: recent file list in File menu

### ISSUE THREAD

**Issue by Chaircrusher** [VCVRack/Rack#1892] opened 2021-02-10 23:16 UTC
### Summary
Add an item to the 'File' menu to show a list of recent files.

This is commonplace on apps on all the supported platforms. It has an 'Open recent >' tab in the File menu that lets you choose from a LRU list of files that have been opened recently.
### Proposed design
Work just like Ableton Live or Microsoft Word.

When a file is opened or saved, store the file path in a list maintained in the Rack settings file.
When the file menu is selected add a tab 'Recent' in addition to 'Open' and 'New'  and populate with recently opened files.

**Comment by AndrewBelt** [comment] 2021-02-10 23:17
Duplicate of #969

**Closed by AndrewBelt** 2021-02-10 23:17 UTC
