### ISSUE TITLE
dragging window from external monitor to retina screen caused kernel panic

### ISSUE THREAD

**Issue by olilarkin** [VCVRack/Rack#460] opened 2017-11-26 14:58 UTC
OS (if applicable): mac sierra 10.12.6
Version (or "dev" if compiling from source): dev

**Comment by AndrewBelt** [comment] 2020-04-01 03:59
Cannot reproduce with given information. Also, issue is likely obsolete. Closing.

**Closed by AndrewBelt** 2020-04-01 03:59 UTC
