### ISSUE TITLE
Can't save or load a patch

### ISSUE THREAD

**Issue by GreGoomM** [VCVRack/Rack#1615] opened 2019-10-29 09:18 UTC
### Details

- Operating system: WIndows 10
- Rack version: v1.1.6
- Audio card : Behringer UMC 1820

### Summary
I can create a patch but when I try to load or save a patch it happens nothing. I have to click on a file(.vcv) in the windows explorer to open it and rename the autosave.vcv in documents\rack\ to save it ? I had the same problem in the previous versions except in the 1.0.

### Steps to reproduce
1 - Create a patch
2 - File > Save or Save as the file
3 - The name of the patch appears in the window bar next to VCV Rack v1.1.6 - Name of the patch.vcv
4 - The patch do not appears in the directory where I saved it.

----------------

1 - Open
2 - Click on a patch in the window
3 - The name of the patch appears in the windows bar next to VCV Rack v1.1.6 - Name of the patch.vcv
4 - Nothing appears in the rack.

---------------

**Comment by AndrewBelt** [comment] 2019-10-29 12:51
Please fill out the issue template by editing your post.

>can't load or save a patch

Can you elaborate? I don't need to know what workaround you use. I need to know what is happening when you attempt to load/save the patch.

**Comment by GreGoomM** [comment] 2019-12-15 10:39
### Details

- Operating system: WIndows 10
- Rack version: v1.1.6
- Audio card : Behringer UMC 1820
- GFX card : GeForce GTX 1050 Ti/PCIe/SSE2

### Summary
I can create a patch but when I try to load or save a patch it happens nothing. I have to click on a file(.vcv) in the windows explorer to open it and rename the autosave.vcv in documents\rack\ to save it ? I had the same problem in the previous versions except in the 1.0.


### Steps to reproduce
1 - Create a patch
2 - File > Save or Save as the file
3 - The name of the patch appears in the window bar next to VCV Rack v1.1.6 - Name of the patch.vcv
4 - The patch do not appears in the directory where I saved it.

----------------

1 - Open
2 - Click on a patch in the window
3 - The name of the patch appears in the windows bar next to VCV Rack v1.1.6 - Name of the patch.vcv
4 - Nothing appears in the rack.


---------------

**Comment by AndrewBelt** [comment] 2020-04-01 16:41
I'm not able to reproduce this issue with the given information. Closing. Comment with additional details if issue is still present.

**Closed by AndrewBelt** 2020-04-01 16:41 UTC
