### ISSUE TITLE
Panel graphics are squished vertically

### ISSUE THREAD

**Issue by antoniotuzzi** [VCVRack/Rack#461] opened 2017-11-26 17:00 UTC
OS (if applicable): FEDORA 26
Version (or "dev" if compiling from source): 0.5.0 (21 november commit)

when I put modules in RACK are presented in a very "compacted way (check the image)

![screen shot 2017-11-26 at 17 54 40](https://user-images.githubusercontent.com/62518/33242329-5e0b8112-d2d3-11e7-8133-9c6ea68d1f1b.png)

is happening for new Fundamental modules too (8 vert in the picture)?
is it something related to the change of SVG in "px" mode ?
anybody experiencing it ?

**Comment by antoniotuzzi** [comment] 2017-11-26 17:05
forgot to say
if I reopen the same patch, is everything  fine

it's happening only when placing modules

**Comment by mnb42** [comment] 2017-11-28 13:11
very similar here: on xubuntu 16.4. binary rack 0.4 and 0.5 it happens only if i run vcvrack as a less privileged user (my gaming account), or as any newly created user.
after loading a patch the graphics are distorted like in the image. added modules are distorted the same way, until the rack is closed. the next time, autosave patch is loaded fine, and adding modules works as it should, until another patch is loaded... (so basically i have to close/reopen vcvrack between loading patches)
when running in my usual (work) account, everything is fine though.

**Comment by spktkpkt** [comment] 2017-11-29 17:17
Same for me on Ubuntu 16.04.03 LTS, binary Rack version 0.5

**Comment by danpetry** [comment] 2018-08-18 15:28
Same for me. I just upgraded and now I can't use the program, and since I can't roll back the plugins (some are closed source) I'm faced with losing about 6 months of work. Happy to help find a solution.

**Comment by zezic** [comment] 2018-11-29 19:19
For me it happens **every time** after displaying OS dialog.
For example, it never occurs if I omit call of `osdialog_message()` here: https://github.com/VCVRack/Rack/blob/v0.6/src/app/RackWidget.cpp#L63
I'll continue searching and try to understand the root of the problem, but maybe this info can help someone.

**Comment by zezic** [comment] 2018-11-30 09:41
To be more specific, this problem appears if `gtk_init_check()` from osdialog was called.
It doesn't affect SVG's which are already loaded with modules into rack, only new files are broken.

You can do the next steps to reproduce it (it's only related to Linux, of course):

0. Start VCV Rack
1. Add VCO-1 module (appears normally)
2. Ctrl+N -> Cancel
3. Add VCO-2 module (background SVG is stretched, but all other elements are OK, because they are already were loaded with VCO-1)

I don't know yet how such side effect of `gtk_init()` or `gtk_init_check()` is possible, I will investigate a bit more, but if no one can fix it Zenity can work as replacement to provide OS dialogs functionality.

**Comment by zezic** [comment] 2018-11-30 13:42
**Found it:**
The root of the problem is Nano SVG parser dependence on locale.

Need to call `gtk_disable_setlocale()` before `gtk_init_check()` to stop it messing with locales.
Or fix locale every time before using `nsvgParseFromFile()`.

@AndrewBelt please, suggest the right place to make a workaround if you want me to make a PR.

**Comment by zezic** [comment] 2018-12-01 10:32
To all the affected users here: as the temporary solution you can change your `LC_NUMERIC` locale to `en_US.UTF-8`

**Comment by AndrewBelt** [comment] 2018-12-01 13:47
If a PR is merged into nanosvg, ping me and I'll update the submodule.

**Comment by AndrewBelt** [comment] 2018-12-20 14:11
Updated in adacc5e. Cannot test since 1) I can't reproduce the issue in the first place and 2) that branch is not yet able to add modules to your rack.

**Comment by codecollider** [comment] 2019-02-28 16:12
I get the same strange UI behavior with Debian Stretch / XFCE. Was this issue ever solved? 
I downloaded the latest zip file (0.6.2c) from the VCV rack website.

**Comment by zezic** [comment] 2019-02-28 16:20
@codecollider it's because of wrong NanoSVG behavior which depends on a system locale. It should be fixed with the release of 1.0 where the new NanoSVG version is used. Currently you can try to rebuild Rack yourself using the new NanoSVG version, or you can use a temporary workaround - change your LC_NUMERIC locale to `en_US.UTF-8`.

**Comment by codecollider** [comment] 2019-02-28 16:22
Thanks, that helps!

**Comment by AndrewBelt** [comment] 2020-04-01 03:54
I'm assuming this issue has been fixed with the string locale issue above. Comment if issue is still present.

**Closed by AndrewBelt** 2020-04-01 03:54 UTC
