### ISSUE TITLE
Feature Request: Rack in Rack

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Rack#579] opened 2018-01-03 14:04 UTC
OS (if applicable): All
Version (or "dev" if compiling from source): Future Versions

I'm coming from Reason and learned everything about music in Reason including modulation of its CV etc I'll be getting some hardware modules this year hopefully. What would be amazing in VCV would be a window or module like the Combinator in Reason to hold patches via different modules. With programmable knobs like the Vult modulation section. You select the mod source from a list of devices in the window. You could save different patches from this also so holding templates for a combination of modules like a starter for a kick or even your master section audio I/O.

I use a template that includes a Master clock and mixer/audio I/O. But there is some patches that would take a little bit of time to set up, one which I seen online recently is a trimmer for LFO's which uses the offset's of the Dual Atenuverter and the min/max summed to stop the LFO going past the set amount on offsets. This would be something that I would use regularly for a project.

Another function of a modulation module would be to save grouped devices like the way you would group devices in Ableton. It would help if such a device was collapsible or resizeable to the rack in terms of HP. The way spacing currently works you would need the space to make it bigger. It would be cool if such a module was another rack inside VCV so that too could be scrolled L/R+Up/Down.

Both saving and recalling patches is needed but also modulating those saves would be pretty great also. From there you could re-program the modulation add modules to a basic patch or remove to suite the project.

The modulation section I'm referring to is on Vult Trummor2 "move a control to assign it".

**Comment by AndrewBelt** [comment] 2019-07-19 17:38
Duplicate of https://github.com/VCVRack/Rack/issues/655

**Closed by AndrewBelt** 2019-07-19 17:38 UTC
