### ISSUE TITLE
Flickering/corrupted graphics using Jack on Linux

### ISSUE THREAD

**Issue by markHadman** [VCVRack/Rack#514] opened 2017-12-10 22:34 UTC
OS (if applicable): Arch Linux with kernels linux 4.13.12-1 & linux-rt 4.1.15_rt17-2
Version (or "dev" if compiling from source): dev
Machine: Lenovo X201 with Intel integrated graphics, i915 driver.

See screenshots. Using zoom with VCVRack connected to Jack causes rapid flickering display and corruption. 
Workarounds: use another audio driver, downgrade Mesa (17.2.6-1 -> 17.1.6-1)

Steps to reproduce:
- Start jack server
- Start VCVrack
- Add "Core/Audio Driver" module
- Select Jack under Audio Driver on Audio Driver module
- Select a valid device under Audio Device on Audio Driver module
- Zoom in /out 

UPDATE 14th Dec 2017: I can reproduce the issue without zooming. Just loading an already jack-enabled patch can cause the flickering, which doesn't go away until jack is disconnected and VCVRack is restarted.

![1](https://user-images.githubusercontent.com/34426238/33810124-20b2f148-ddf9-11e7-8c2c-4a6570dc3954.png)
![2](https://user-images.githubusercontent.com/34426238/33810126-21982b46-ddf9-11e7-84c3-3582bc79b330.png)
![3](https://user-images.githubusercontent.com/34426238/33810127-21d282f0-ddf9-11e7-87b1-5e7249f91421.png)
![4](https://user-images.githubusercontent.com/34426238/33810128-237af5f6-ddf9-11e7-922f-9518ed23ad20.png)

**Comment by bontric** [comment] 2017-12-11 13:54
I'm unable to reproduce this (also using Arch+Jack). Seeing your Hardware

>  Lenovo X201 with Intel integrated graphics, i915 driver.

is rather old, this might be a performance related issue. (Mostly due to the integrated graphics card) Weird that using other audio drivers works for you though. Maybe check the resources used by Rack+jack and Rack+alsa and see whether there is a significant difference.

**Comment by markHadman** [comment] 2017-12-14 16:54
UPDATE 14th Dec 2017: I can reproduce the issue without zooming. Just loading an already jack-enabled patch can cause the flickering, which doesn't go away until jack is disconnected and VCVRack is restarted.

**Comment by markHadman** [comment] 2017-12-14 18:38
UPDATE 14th Dec 2017: downgrading Mesa (17.2.6-1 -> 17.1.6-1) cures the problem

**Comment by markHadman** [comment] 2017-12-15 17:38
Possibly one of these commits to Mesa:
```
[mark@x201 mesa]$ git log --pretty=oneline mesa-17.1.8...mesa-17.2.0|grep i915
171b72542ccbf54097079f3ffe20440d3e2c4316 intel/isl: Add i915 to isl_tiling converter
d8521b9960e4f0202cc61feb5eab4b34c0cfde60 i965/miptree: Use isl_tiling_to_i915_tiling()
6ba3fd2d6d872d091d50aeb665125cd9d857f10a i915: remove local vblank_mode option
5b3363e3f17db887fedc58b8e15fa8b78a14e088 intel/isl: Add a helper to convert tilings from ISL to i915
165e704719b85cb43156f517803dd9a1f0187519 i965/i915: Add UYVY as the supported format
e8eb5e80f162dc40b48eb20b844a3190c5b2b86c i915: Fix wpos_tex vs. -1 comparison
a49cad48966f48be26ad0e8596922bda3e365711 i915: Fix gl_Fragcoord interpolation
3c50ebce259f63392122a6ace32d07055e0bff1a i915: use different CFLAGS/LIBS variables than i965/anv
f73c63a17558263eb0bc885bfbc61048c7b9d8eb i915: On Gen <= 3 there are no array textures
122e6dc45112e1627da11161b488d89e29730c81 i915: On Gen <= 3 there is no W-tiling
97d332ce0e9e47714da20f799e6f1a92fb1f53dd i915: Remove unused fields intel_mipmap_tree::logical_(width|height|depth)0
ca8e8d5520d322e28df2f5ecade0802965e3ebd8 i915: Remove unused field intel_mipmap_tree::array_spacing_lod0
e5a632a2564129c7e4a695155934893914723904 i915: On Gen <= 3 there is no multisampling
7b7a0ba04c93b0eec2f7b1777a08dbc8dbdc1e5e i915: Trivial code reformatting
b08981009d9bf127436be84aadb2e88b889e56c0 i915,i965: Don't condition use of GLSL clear on the current API
1c409fe4c144f11ce6c6a4548ac5c6ba37980058 i915: Fix gl_Fragcoord interpolation
0eef03a6f2f7fa7968accaa2ab2c3d7431e984b8 i915: Always emit W on gen3
c1eedb43f32f6a3733f26e7918eb028f68bd60a4 i915: Fix wpos_tex vs. -1 comparison
142536a0e32455a485d979d11188fd861882f437 i915g: Add blitter_context argument.
e1678159b162fcb28b6611dade44b75b528197a2 i915: Fix build break with empty unreachable()
d4342b1398a001af1192497ca4db3a304f98c309 i915: Fix build break with empty unreachable()
```

**Comment by AndrewBelt** [comment] 2019-12-06 09:52
Closing as obsolete issue.

**Closed by AndrewBelt** 2019-12-06 09:52 UTC
