### ISSUE TITLE
after fresh installation no menu bar win 10

### ISSUE THREAD

**Issue by marekdyjor** [VCVRack/Rack#1722] opened 2020-03-15 08:53 UTC
Operating system: Windows 10 Pro   fresh installation
Rack version: v1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
GTX 1070 Q max. no midi, notebook intel i7 7700HQ

### Summary
 download file and installed software. There is no menu bar.  I reinstalled VCV, no change.
### Steps to reproduce
it wold be hard to reproduce 'cos it would be some kind of computer configuration issue.

**Comment by AndrewBelt** [comment] 2020-03-15 18:38
This is a graphical issue so post a screenshot.

Make sure your graphics driver is updated, as some users have reported this has fixed it for them.

**Comment by marekdyjor** [comment] 2020-03-17 05:54
I post a screen shot
![Adnotacja 2020-03-17 065345](https://user-images.githubusercontent.com/43351460/76826187-180b7b00-681c-11ea-8c35-2bdc2a5d4891.png)

**Comment by AndrewBelt** [comment] 2020-03-17 06:32
What is your Nvidia driver version?

**Comment by marekdyjor** [comment] 2020-03-17 06:39
nvidia driver version  26.21.14.4259
intel HD Graphics 630    ver   21.20.16.4678

**Comment by AndrewBelt** [comment] 2020-03-17 06:45
I'm not sure where you're seeing that versioning scheme. The latest Nvidia driver is 442.59 at https://www.nvidia.com/Download/driverResults.aspx/158181/en-us

**Comment by marekdyjor** [comment] 2020-03-17 08:18
after upgrage there is no change

But whan I was moving near the place where the menu has to be and clicking mouse there shows a login dialog.

**Comment by marekdyjor** [comment] 2020-03-17 08:56
it looks like there is a menu bar, but positions are invisible.  When I click i right places the pull down menus appear

**Comment by Coirt** [comment] 2020-03-17 11:02
@marekdyjor Whats happens when you go full screen `F11`

**Comment by marekdyjor** [comment] 2020-03-17 13:51
in full screen...   menu items doesn't  show  when I click up the screen...

**Comment by Coirt** [comment] 2020-03-17 14:24
What about when you resize the window when it is in Restore mode (as apposed to a Maximised window) if you drag the window down so the bottom is off the desktop you make the window bigger horizontally.

**Comment by marekdyjor** [comment] 2020-03-18 05:05
no change...   any combination doesn't help.

**Comment by marekdyjor** [comment] 2020-03-29 10:44
time goes by and I see there is no solution...  :(

**Comment by AndrewBelt** [comment] 2020-03-29 15:10
Duplicate of https://github.com/VCVRack/Rack/issues/369

**Closed by AndrewBelt** 2020-03-29 15:10 UTC
