### ISSUE TITLE
Save/load groups of modules

### ISSUE THREAD

**Issue by maxp-hover** [VCVRack/Rack#1791] opened 2020-06-04 07:42 UTC
### Summary

There is really no way to share module groups between projects. If you make a really nice component for some purpose and want to re-use it, you have to either clone the previous project or do it all from scratch.

### Proposed design

- can select multiple modules to save them as an independent file. This would just need to include knob settings and cable layout.
- can load these files up to import the group of modules into a project

**Comment by AndrewBelt** [comment] 2020-06-04 08:09
Duplicate of #655

**Closed by AndrewBelt** 2020-06-04 08:09 UTC
