### ISSUE TITLE
v1: MacOS pinch zoom not working

### ISSUE THREAD

**Issue by jacoblast** [VCVRack/Rack#1352] opened 2019-06-18 16:36 UTC
Operating system: MacOS 10.14.5
Rack version: v1.dev.b4bd09a

Not sure if this is a bug or feature request, but would love to have pinch zoom work in v1!

**Comment by AndrewBelt** [comment] 2019-06-18 16:41
Duplicate of #362  and other issues

**Closed by AndrewBelt** 2019-06-18 16:41 UTC

**Comment by jacoblast** [comment] 2019-06-18 16:58
Sorry I wasn't clear, not sure if this is a duplicate of the touchscreen pinch issue because I'm talking about MacBook trackpad pinch zoom.

**Comment by AndrewBelt** [comment] 2019-06-18 17:01
Essentially the same reason: There is no multitouch support in GLFW yet.

**Comment by jacoblast** [comment] 2019-06-18 17:02
Gotcha, thanks
