### ISSUE TITLE
ALSA lib

### ISSUE THREAD

**Issue by khz-daw** [VCVRack/Rack#335] opened 2017-10-28 08:32 UTC
OS (if applicable): GNU/Linux Gentoo
Version (or "dev" if compiling from source): 0.4.0
Hello,

both with the Linux-64-bit version and with the sources built to https://github.com/VCVRack/Rack#building I get a very high CPU (~70 - 100%) utilization only with the rack.

Here the output with qjackctl:
```/Rack $ make run
LD_LIBRARY_PATH=dep/lib ./Rack
Current working directory is /home/daw/Musik/VCVRack/Rack
Loading plugins from ./plugins
Loading plugins from ./plugins
Loaded font ./res/DejaVuSans.ttf
Loading patch ./autosave.vcv
Requesting http://api.vcvrack.com/version
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
Loaded SVG ./res/ComponentLibrary/PJ3410.svg
Failed to open audio stream: Invalid sample rate
Loading settings ./settings.json
Saving patch ./autosave.vcv
Saving settings ./settings.json
Saving patch ./autosave.vcv
Saving settings ./settings.json
Saving settings ./settings.json
Saving patch ./autosave.vcv
```

and once only with ALSA:

```
/Rack $ make run
LD_LIBRARY_PATH=dep/lib ./Rack
Current working directory is /home/daw/Musik/VCVRack/Rack
Loading plugins from ./plugins
Loading plugins from ./plugins
Loaded font ./res/DejaVuSans.ttf
Loading patch ./autosave.vcv
Requesting http://api.vcvrack.com/version
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm_direct.c:1271:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm_dmix.c:1111:(snd_pcm_dmix_open) unable to initialize slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Loaded SVG ./res/ComponentLibrary/PJ3410.svg
Loading settings ./settings.json
Saving settings ./settings.json
Saving patch ./autosave.vcv
```

```
ALSA lib /tmp/portage/media-libs/alsa-lib-1.1.4.1/work/alsa-lib-1.1.4.1/src/pcm/pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.
```
<-- I haven't found anything on the web that tells me.
Can someone give me a clue what I can do?
Thanks.

**Comment by AndrewBelt** [comment] 2017-10-28 08:45
All the ALSA garbage is because portaudio and ALSA are very verbose by default. High CPU usage is normal on computers without a decent GPU, since the CPU software OpenGL renderer has to be used instead of GPU features. What's your CPU/GPU?

**Comment by khz-daw** [comment] 2017-10-28 08:58
Ah OK. BTW great tool!

Why does vcvrack need portaudio? Can't this be done directly via ALSA or Jack?
CPU:
`model name	: AMD Phenom(tm) II X6 1055T Processor`
GPU:
`07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV516 [Radeon X1300/X1550 Series]`

**Comment by AndrewBelt** [comment] 2017-10-28 09:06
Yeah, this would be expected behavior on your machine. The GPU is 11 years old and scores poorly on https://www.notebookcheck.net/ATI-Mobility-Radeon-X1300.2166.0.html

**Comment by khz-daw** [comment] 2017-10-28 09:09
Och :-( 
THX4feedback!

**Comment by khz-daw** [comment] 2017-10-29 20:52
Change the file src/gui.cpp
In the function guiRun():
Replace "glfwPollEvents();" with "glfwWaitEventsTimeout(0.1);"
and remove the line "glfwSetWindowTitle(gWindow, title.c_str());".

**Comment by AndrewBelt** [comment] 2017-10-30 00:31
What do both of these changes do in terms of performance? I can the second one being a problem, so I've pushed a change. 7490d1c

**Comment by khz-daw** [comment] 2017-10-30 08:30
That's what Drumfix suggested to me, see [https://www.sequencer.de/synthesizer/threads/vcvrack-soft-modular-fuer-macos-linux-windows.125550/page-5#post-1506401](url).
The CPU load decreased in full screen from ~100% (without changing the src/gui. cpp) to only ~30% CPU load (after changing the src/gui. cpp). If VCVRack does not run in full screen mode even only ~10% CPU load.
What/Why does this effect? I have no idea. I'll ask Drumfix. :-)

**Comment by AndrewBelt** [comment] 2017-10-30 08:39
It optimizes the graphics thread to about a sixth of the CPU, and here's why: It sets the framerate to 10Hz instead of locking to vsync (usually 60Hz), and it does it in the hackiest way possible. :laughing:
So no, it isn't a viable way of improving graphics performance because users need to see 60Hz by default.

**Comment by khz-daw** [comment] 2017-10-30 08:49
Buying newer hardware would be a good idea, I am more sustainable/ecological in such areas. ;-)
Thanks to this change, VCVRack can also be used with outdated hardware, which I am very happy with at the moment. \o/

**Comment by AndrewBelt** [comment] 2017-10-30 08:56
It's an interesting solution actually. But a more proper one would be to cache all UI elements in framebuffers and make it intelligently render framebuffers only when needed. 

Using `glfwWaitEventsTimeout(1.0/idleFrameRate)` only decreases CPU when the mouse is not moving, however. When you move the mouse, the framerate shoots up to 60Hz again. So if your goal is to decrease the *maximum attainable* CPU, this fix won't help you. It decreases the *average* CPU over the duration the program is running, but at the expense of it lagging when the mouse is not moving.

**Comment by AndrewBelt** [comment] 2017-11-03 19:19
Closing, as this isn't really a concrete issue. Reopen if something comes up.

**Closed by AndrewBelt** 2017-11-03 19:19 UTC
