### ISSUE TITLE
Feature request: accessibility preferences

### ISSUE THREAD

**Issue by david-c14** [VCVRack/Rack#1007] opened 2018-06-16 16:08 UTC
Feature request:
Please could we have a setting in VCVRack for users to express accessibility needs. High contrast, low contrast, large text, dark theme...
And an api call to get this current setting when a modules loads (perhaps a set of enum flags)
Developers wouldn't have to support these flags, but those that choose to could get a consistent view of the users needs, and the presence of the api might encourage more devs to think about it.

**Comment by milholen** [comment] 2018-07-27 05:00
On macOS (I haven't used Windows in several years) these settings already exist at the OS level:

<img width="668" alt="screen shot 2018-07-26 at 9 56 51 pm" src="https://user-images.githubusercontent.com/134360/43302394-23e5fb60-911f-11e8-9b02-e7044d2b742f.png">

Having the Zoom function in Rack handles the "large text" request.

Again, not sure what Windows offers but it seems that this sort of thing is better handled by the OS.

**Comment by david-c14** [comment] 2018-07-27 05:56
Yes, windows offers the same. But that's not very portable for plugin writers.

**Comment by AndrewBelt** [comment] 2018-07-27 10:18
What's the issue with @milholen's solution? You can invert the display and increase contrast. That solves this issue, correct?

**Comment by david-c14** [comment] 2018-07-27 10:41
I see what you mean. This request came about because of conversations on the Facebook page around the alternative skins that some developers provide, and how they relate to accessibility.  

The issue was that developers are using all kinds of mechanisms to allow the different skins to be used. They are not always used for accessibility. I was just suggesting that it might be possible to provide a centralised mechanism in the app itself to capture the users preferences, so that plugin developers could then tap into those preferences to make modules more responsive.

**Comment by AndrewBelt** [comment] 2018-07-27 10:46
Okay, I'm closing this, since it seems like the problem is solved with the OS.

**Closed by AndrewBelt** 2018-07-27 10:46 UTC
