### ISSUE TITLE
Compile/build error during "make dep"

### ISSUE THREAD

**Issue by DomiKamu** [VCVRack/Rack#999] opened 2018-06-12 10:25 UTC
Operating systems: Windows 7 Pro SP1 x64 (also under Windows 10 Pro Redstone 3 x64).
Compiling from source: commit 7f6745c (**_from scratch_**), default branch (**v0.6**).

Hi Andrew, I have this error during **make dep** phase:

```
...
make[4] : on entre dans le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
make[4] : on quitte le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
[ 64%] Built target playsaw
make[4] : on entre dans le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
make[4] : on quitte le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
[ 71%] Built target playraw
make[4] : on entre dans le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
make[4] : on quitte le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
[ 78%] Built target record
make[4] : on entre dans le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
make[4] : on quitte le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
[ 85%] Built target duplex
make[4] : on entre dans le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
make[4] : on quitte le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
[ 92%] Built target audioprobe
make[4] : on entre dans le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
make[4] : on quitte le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
[100%] Built target testall
make[3] : on quitte le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
Install the project...
-- Install configuration: ""
-- Installing: C:/Rack061dev/Rack/dep/lib/librtaudio.dll.a
-- Installing: C:/Rack061dev/Rack/dep/bin/librtaudio.dll
-- Installing: C:/Rack061dev/Rack/dep/include/RtAudio.h
-- Installing: C:/Rack061dev/Rack/dep/lib/pkgconfig/rtaudio.pc
make[2] : on quitte le répertoire « /C/Rack061dev/Rack/dep/rtaudio/build »
# For some reason, it doesn't install the static library
cp rtaudio/build/librtaudio_static.a lib/librtaudio.a
cp nanovg/src/nanovg.h nanovg/src/fontstash.h nanovg/src/nanovg_gl_utils.h nanovg/src/stb_image.h nanovg/src/stb_truetype.h nanovg/src/nanovg_gl.h include/
cp nanosvg/src/nanosvgrast.h nanosvg/src/nanosvg.h include/
cp  include/
cp: opérande de fichier cible manquant après 'include/'
Saisissez « cp --help » pour plus d'informations.
make[1]: *** [Makefile:156: include/blendish.h] Error 1
make[1] : on quitte le répertoire « /C/Rack061dev/Rack/dep »
make: *** [Makefile:55: dep] Error 2
```

Please apologize about some messages in French language reported by MSYS2 MinGW-64.

**Comment by MarcBoule** [comment] 2018-06-12 12:04
Win 10, commit 1466a8a
Getting a make error here as well. My console is in french so I'll spare the verbatim, but my make is hanging with no rule to make `build/dep/osdialog/osdialog.c.o`.

**Comment by alfonso73** [comment] 2018-06-12 12:17
yes. i can confirm.
https://github.com/VCVRack/Rack/issues/998

**Comment by alfonso73** [comment] 2018-06-12 12:34
@MarcBoule I just did a git pull..

**Comment by modlfo** [comment] 2018-06-12 14:15
I had the `build/dep/osdialog/osdialog.c.o` error which was solved by updating the submodules.

**Comment by MarcBoule** [comment] 2018-06-12 14:19
Awesome, thanks Leonardo, that worked for me. I should have thought about that one, I keep forgetting about it! 👍

**Comment by DomiKamu** [comment] 2018-06-12 14:37
@MarcBoule :+1 -> as usual, from scratch I'm following README.me, such

`cd /C/Rack061`
(this folder is existing and empty)
`git clone https://github.com/VCVRack/Rack.git`
`cd Rack`
(enters into my C:\Rack061\Rack, in fact)
`git submodule update --init --recursive`
`make dep` --> stucked at this step...
`make`

and of course `make run` to run VCV Rack ;)

**Comment by modlfo** [comment] 2018-06-12 15:05
In windows make sure that you have an up-to-date MSYS2 by running
```
$ pacman -Syu
$ pacman -Su
```

I had a problem building the dependencies some time ago and it was fixed with that.

**Comment by antoniotuzzi** [comment] 2018-06-12 16:33
I have the same problems
I have fully updated MSYS2
done all the necessary steps and I'm having the same problems as @DomiKamu @alfonso73  
(win10 64bit on parallels MAC)

(I'm having problems on FEDORA too )

**Comment by alfonso73** [comment] 2018-06-12 16:40
Hi,
i did 
pacman -Syu
pacman -Su
git submodule update --init --recursive
make clean
make

now everything works

**Comment by antoniotuzzi** [comment] 2018-06-12 16:46
trashed the directory, new fresh everything, 
making DEP...

**Comment by Cordoha** [comment] 2018-06-12 17:17
Compiling in Linux, make RELEASE=1 worked a few days ago in Ubuntu 18.04. It compiled JACK support. But it won't build now, even without JACK support. Not sure what's going on.
re: https://github.com/VCVRack/Rack/issues/982

**Comment by AndrewBelt** [comment] 2018-06-12 17:35
Should be fixed in 5428ad3.

**Closed by AndrewBelt** 2018-06-12 17:35 UTC

**Comment by AndrewBelt** [comment] 2018-06-12 17:40
Also, duplicate of #998.

**Comment by antoniotuzzi** [comment] 2018-06-12 17:44
confirmed
I traversed the "make dep" part

**Comment by hwpfeil** [comment] 2018-06-12 17:47
Re: dep/Makefile commit 4e41c353951d83fb934ebdf4edc6ca610666f9c8

'$^' works in Windows msys2, but not in Linux bash (GNU/Linux 3.2.0). Not a special $ shell variable;  maybe '$@' or '$*' ?

dep/Makefile:
-      cp nanovg/src/*.h include/
+	cp $^ include/
...

**Comment by AndrewBelt** [comment] 2018-06-12 17:55
@hwpfeil That's a Makefile, not a bash script. What's your make type and version? `make -v`

**Comment by hwpfeil** [comment] 2018-06-12 17:58
$^ on nanovg does a recursive substitution, then fails:

cp nanovg/src/nanovg_gl.h nanovg/src/stb_truetype.h nanovg/src/stb_image.h nanovg/src/nanovg_gl_utils.h nanovg/src/fontstash.h nanovg/src/nanovg.h include/
cp nanosvg/src/nanosvg.h nanosvg/src/nanosvgrast.h include/
cp  include/
cp: missing destination file operand after 'include/'

Makefile fails at this point

**Comment by AndrewBelt** [comment] 2018-06-12 18:01
@hwpfeil That's not an issue with `$^`. Have you pulled the latest source? I just mentioned that this has been fixed.

**Comment by hwpfeil** [comment] 2018-06-12 18:02
Just missed it 
blendish ==> oui-blendish
