### ISSUE TITLE
Blank grid on el Captain 10.11.6

### ISSUE THREAD

**Issue by antoniograzioli** [VCVRack/Rack#41] opened 2017-09-12 08:23 UTC
I tested it also on an old MacBook ruinning el Captain 10.11.6

Rack opens but the module grid is completely blank...no racks, no right click or ctrl-click.
Opening a patch created on my other mac (Sierra 10.12.11) , the modules have no knobs, no outs and so on, more or less the same problem I have when switching between mac/pc

**Comment by glemonmondon** [comment] 2017-09-13 18:53
Same problem. My Mac book pro is running Sierra 10.12.6, and modules have no knobs, no in/out...
Please fix it... I can't wait to test that sofware !

**Comment by AndrewBelt** [comment] 2017-09-13 19:11
Are you using v0.3.1? Does the right click menu still not work on this release?

**Comment by glemonmondon** [comment] 2017-09-13 19:52
Yes, i'm running Rack v0.3.1. On my macbook pro running sierra 10.12.6, the right click work, but knobs and jack connections are invisible.

**Comment by AndrewBelt** [comment] 2017-09-14 12:03
Duplicate of #17 

Except, that's in the case of "the modules have no knobs, no outs and so on". Could you post a screenshot of "module grid is completely blank...no racks"?

**Closed by AndrewBelt** 2017-09-14 12:03 UTC
