### ISSUE TITLE
Crash with Notes

### ISSUE THREAD

**Issue by Cordoha** [VCVRack/Rack#531] opened 2017-12-16 21:26 UTC
Ubuntu MATE 17.10
0.5.0 Dev

- Topograph
- Trummor x3
- Mental Mixer
- Interface
- Notes

The problem is when I type something in notes, Rack crashes. Has happened multiple times.  

>LD_LIBRARY_PATH=dep/lib gdb -ex run ./Rack
GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Rack...done.
Starting program: /home/justin/Rack3/Rack/Rack 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[info] Current working directory: /home/justin/Rack3/Rack
[info] Global directory: ./
[info] Local directory: ./
[info] Loading plugins from ./plugins
[info] Loaded plugin ./plugins/ML_modules/plugin.so
[info] Loaded plugin ./plugins/ValleyRackFree/plugin.so
[info] Loaded plugin ./plugins/s-ol/plugin.so
[info] Loaded plugin ./plugins/AudibleInstruments/plugin.so
[info] Loaded plugin ./plugins/Simple/plugin.so
[info] Loaded plugin ./plugins/sonusmodular/plugin.so
[info] Loaded plugin ./plugins/ArableInstruments/plugin.so
[info] Loaded plugin ./plugins/trowaSoft-VCV/plugin.so
[info] Loaded plugin ./plugins/Parable/plugin.so
[info] Loaded plugin ./plugins/nohmad/plugin.so
[info] Loaded plugin ./plugins/moDllz/plugin.so
[info] Loaded plugin ./plugins/monome-rack/plugin.so
[info] Loaded plugin ./plugins/Bidoo/plugin.so
[info] Loaded plugin ./plugins/MSM/plugin.so
[warning] Failed to load library ./plugins/NauModular/plugin.so: ./plugins/NauModular/plugin.so: cannot open shared object file: No such file or directory
[info] Loaded plugin ./plugins/Autodafe/plugin.so
[info] Loaded plugin ./plugins/NonLinearInstruments/plugin.so
[info] Loaded plugin ./plugins/LOGinstruments/plugin.so
[info] Loaded plugin ./plugins/Fundamental/plugin.so
[info] Loaded plugin ./plugins/Stellare-Modular/plugin.so
[info] Loaded plugin ./plugins/Gratrix/plugin.so
[info] Loaded plugin ./plugins/nysthi/plugin.so
[info] Loaded plugin ./plugins/VultModules/plugin.so
[info] Loaded plugin ./plugins/mscHack/plugin.so
[info] Loaded plugin ./plugins/JW-Modules/plugin.so
[info] Loaded plugin ./plugins/BogaudioModules/plugin.so
[info] Loaded plugin ./plugins/dekStop/plugin.so
[info] Loaded plugin ./plugins/ESeries/plugin.so
[info] Loaded plugin ./plugins/RJModules/plugin.so
[info] Loaded plugin ./plugins/MentalModules/plugin.so
[info] Loaded plugin ./plugins/KarateSnoopy/plugin.so
[info] Loaded plugin ./plugins/vcv-MrLumps/plugin.so
[warning] Failed to load library ./plugins/cf/plugin.so: ./plugins/cf/plugin.so: cannot open shared object file: No such file or directory
[info] Loaded plugin ./plugins/AmalgamatedHarmonics/plugin.so
[warning] Failed to load library ./plugins/Autodafe-Drums/plugin.so: ./plugins/Autodafe-Drums/plugin.so: cannot open shared object file: No such file or directory
[info] Loaded plugin ./plugins/Befaco/plugin.so
[info] Loaded plugin ./plugins/hetrickcv/plugin.so
[info] Loaded plugin ./plugins/qwelk/plugin.so
[info] Loaded font ./res/DejaVuSans.ttf
[info] Loading patch ./autosave.vcv
[New Thread 0x7fffe51a9700 (LWP 6742)]
[New Thread 0x7fffe5128700 (LWP 6743)]
[Thread 0x7fffe5128700 (LWP 6743) exited]
[Thread 0x7fffe51a9700 (LWP 6742) exited]
[info] Loaded SVG ./res/ComponentLibrary/PJ3410.svg
[New Thread 0x7fffe51a9700 (LWP 6744)]
[New Thread 0x7fffe5128700 (LWP 6745)]
[Thread 0x7fffe5128700 (LWP 6745) exited]
[Thread 0x7fffe51a9700 (LWP 6744) exited]
[debug] Opening audio stream 2
[New Thread 0x7fffe51a9700 (LWP 6746)]
[New Thread 0x7fffe5128700 (LWP 6747)]
[Thread 0x7fffe5128700 (LWP 6747) exited]
[Thread 0x7fffe51a9700 (LWP 6746) exited]
[New Thread 0x7fffe51a9700 (LWP 6748)]
[New Thread 0x7fffe5128700 (LWP 6749)]
[debug] Starting audio stream 2
[New Thread 0x7fffe5090700 (LWP 6750)]
[info] Loaded SVG ./plugins/ValleyRackFree/res/TopographPanel.svg
[info] Loaded SVG ./res/ComponentLibrary/ScrewBlack.svg
[info] Loaded SVG ./res/ComponentLibrary/LEDButton.svg
[info] Loaded SVG ./res/ComponentLibrary/Rogan1PSBlue.svg
[info] Loaded SVG ./res/ComponentLibrary/Rogan1PSWhite.svg
[info] Loaded SVG ./plugins/ValleyRackFree/res/Rogan1PSBrightRed.svg
[info] Loaded SVG ./plugins/ValleyRackFree/res/Rogan1PSOrange.svg
[info] Loaded SVG ./plugins/ValleyRackFree/res/Rogan1PSYellow.svg
[info] Loaded SVG ./res/ComponentLibrary/PJ301M.svg
[info] Loaded SVG ./plugins/VultModules/res/Trummor.svg
[info] Loaded SVG ./plugins/VultModules/res/Screw.svg
[info] Loaded SVG ./plugins/VultModules/res/Knob.svg
[info] Loaded SVG ./plugins/VultModules/res/KnobAlt.svg
[info] Loaded SVG ./plugins/VultModules/res/Select2_A.svg
[info] Loaded SVG ./plugins/VultModules/res/Select2_B.svg
[info] Loaded SVG ./plugins/VultModules/res/Jack.svg
[info] Loaded SVG ./plugins/VultModules/res/KnobSmall.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Tone.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Decimate.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Attack.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Hold.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Release.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Speed.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Source.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Level.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Tune.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Bend.svg
[info] Loaded SVG ./plugins/VultModules/res/LCD-Drive.svg
[info] Loaded SVG ./plugins/MentalModules/res/Mixer.svg
[info] Loaded SVG ./res/ComponentLibrary/SynthTechAlco.svg
[info] Loaded SVG ./res/ComponentLibrary/SynthTechAlco_cap.svg
[info] Loaded SVG ./plugins/MentalModules/res/components/OutPort.svg
[info] Loaded SVG ./res/ComponentLibrary/Trimpot.svg
[info] Loaded SVG ./plugins/MentalModules/res/components/InPort.svg
[info] Loaded SVG ./plugins/MentalModules/res/components/CVInPort.svg
[info] Loaded SVG ./plugins/MentalModules/res/components/GateInPort.svg
[info] Loaded SVG ./res/ComponentLibrary/ScrewSilver.svg
[info] Loading settings ./settings.json
[New Thread 0x7fffe500f700 (LWP 6751)]
[New Thread 0x7fffe480e700 (LWP 6752)]
[Thread 0x7fffe480e700 (LWP 6752) exited]

>Thread 1 "Rack" received signal SIGSEGV, Segmentation fault.
fonsTextIterNext (stash=0x555555ddb150, iter=iter@entry=0x7fffffffd8d0, 
    quad=0x7fffffffd8b0) at ext/nanovg/src/fontstash.h:1378
1378			if (fons__decutf8(&iter->utf8state, &iter->codepoint, *(const unsigned char*)str))

**Comment by AndrewBelt** [comment] 2017-12-17 00:18
I believe this is a duplicate of #373

**Closed by AndrewBelt** 2017-12-17 00:18 UTC
