### ISSUE TITLE
Feature Request: Recent Patches in the File menu

### ISSUE THREAD

**Issue by spectromas** [VCVRack/Rack#1852] opened 2020-10-06 17:37 UTC
### Summary

I don't think I need to add much about implementation as it is very simple feature request but I can do if it would be helpful.

**Comment by AndrewBelt** [comment] 2020-10-06 17:38
Duplicate of https://github.com/VCVRack/Rack/issues/969

**Closed by AndrewBelt** 2020-10-06 17:38 UTC

**Comment by spectromas** [comment] 2020-10-06 17:39
Apologies, I did search but didn't see that one.
