### ISSUE TITLE
Unable to view all modules available after installing 3rd party modules.

### ISSUE THREAD

**Issue by Mubali** [VCVRack/Rack#167] opened 2017-10-02 15:34 UTC
OS (10.10.5):
Version (0.3.2):

After installing new modules, I cannot access the full list of modules available in my system. In this screenshot you can see that I cannot access all of the Belfaco Modules as well as the Fundamental Modules. Currently no ability to scroll the list of modules.
![screen shot 2017-10-02 at 8 32 44 am](https://user-images.githubusercontent.com/16543417/31085588-73949148-a74c-11e7-9129-0d2ff55a1667.png)

**Comment by AndrewBelt** [comment] 2017-10-02 15:36
Duplicate of #68

**Closed by AndrewBelt** 2017-10-02 15:36 UTC
