### ISSUE TITLE
Cant access all modules in the "Add Module" menu

### ISSUE THREAD

**Issue by cyanit** [VCVRack/Rack#164] opened 2017-10-02 12:20 UTC
Hi,
Im completly new to Modular synthesizers and after getting used to VCV Racks Official Devices, I downloaded the listed third-party devices. Installing them is no problem, but accessing them. For me after the VC mixer is not readable/visible. Scope is clickable though.
So something really important are categories/groups or more rows.
Hope this will be fixed soon,
Leo

-----------------------------------------------------------
OS (if applicable): Windows 10
Version (or "dev" if compiling from source): 0.3.2 (.zip)

**Comment by AndrewBelt** [comment] 2017-10-02 12:23
Duplicate of #68

**Closed by AndrewBelt** 2017-10-02 12:23 UTC
