### ISSUE TITLE
Crash when deleting module

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#403] opened 2017-11-18 13:27 UTC
OS (if applicable):10.12 OSX
Version (or "dev" if compiling from source):dev

On a playing patch tried to delete module and it crashed. Crashlog attached.
[Rack_2017-11-18-142553_betas-MacBook-Pro.crash.zip](https://github.com/VCVRack/Rack/files/1484603/Rack_2017-11-18-142553_betas-MacBook-Pro.crash.zip)

**Comment by AndrewBelt** [comment] 2017-11-18 23:24
Duplicate of #378 
Thanks for the crash report, but I'm not able to figure this out yet, even when caught with gdb.
I can only reproduce it (randomly) on MacOS.

**Closed by AndrewBelt** 2017-11-18 23:24 UTC

**Comment by sanderbaan** [comment] 2017-11-19 06:59
will keep a eye on it if it happens again if i can see a pattern
