### ISSUE TITLE
Core Midi-CC module crashing when using the same device in another Midi-CC module

### ISSUE THREAD

**Issue by tenks** [VCVRack/Rack#863] opened 2018-03-29 17:44 UTC
Operating system(s): Windows 7
Rack Version: 0.6

I've been using an Akai APC40 to control my main mixer and modules through midi. Since the line faders on the APC40 are mapped to the same ID but a different channel for all 8 of them, I used 8 Midi-CC modules from Core and mapped them to different channel 1-8 and the same midi device. In version 0.5 of rack this worked like a charm but in 0.6 it crashes as soon as two Midi-CC modules are set to the same device, even when they're both set to all channels. After further testing I found out that this is true for all midi modules, even 3rd party ones.
As soon as there are more than two midi modules set to the same device, the following generic message appears and rack closes down.

![image](https://user-images.githubusercontent.com/4749190/38104372-313964a8-3389-11e8-874f-c9c25d02021b.png)

This was not the case in rack 0.5.

**Comment by AndrewBelt** [comment] 2018-03-29 17:45
Duplicate of https://github.com/VCVRack/Rack/issues/818

**Closed by AndrewBelt** 2018-03-29 17:45 UTC
