### ISSUE TITLE
VCV Rack is maxing out GPU usage out of nothing

### ISSUE THREAD

**Issue by SaturnXp** [VCVRack/Rack#1780] opened 2020-05-18 11:44 UTC
### Details

Operating system and version: Mac OS Mojave
Rack version (vX.Y.Z): 1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):
Macbook Pro 15 2017 256gb
### Summary
Seems like Rack uses too much GPU resourses while doing literally nothing, I thought its because im on 60fps mode but 30fps helps a little but not that much, it still uses about the same GPU resourses as GTA V, what the hell :) Btw GPU usage was tested by iStat Menus, Rack LITERALLY makes it 100% (at 60fps) right after start. GPU is kinda ok when Rack is on 15fps but its impossible to work with. Im on 70 degrees celsius, my butt kinda same. Maybe there is a way to limit GPU usage. I think it can be caused by high resolution rendering (2880 x 1800) or internal rendering resolution (seems like its variable already, am I wrong?). Pls do something, good luck
### Steps to reproduce
just start Rack and look at GPU usage with iStat or smth (btw I have a lot of module libraries and VCV HOST too).

**Comment by SaturnXp** [comment] 2020-05-18 11:51
also, maaayyybe fullscreen mode (f11 especially) helps a little but it has its own bug (I cant quit it and it doesnt have this menu up there (like file view etc). A regular fullscreen (with a green dot left corner mac os) aint got that bug. My english level sucks when im starting to say something close to smart, forgive me please ;)

**Comment by SaturnXp** [comment] 2020-05-18 13:10
also it can be caused by preview images of those modules, cause i don't think this is what it was before, i haven't noticed any problems couple weeks before. Ive been working in Rack for 4-5 hours, now its 30mins in a good case

**Comment by SaturnXp** [comment] 2020-05-18 13:12
so im absolutely sure its because of that modules manager (and maybe screen resolution)

**Comment by SaturnXp** [comment] 2020-05-18 13:15
so it seems logical that v0.blabla was ok and v1.0 is not so. Just a new modules manager. I think it can be solved by pre-rendering those preview pictures

**Comment by AndrewBelt** [comment] 2020-05-18 19:13
This is a duplicate of other issues.

**Closed by AndrewBelt** 2020-05-18 19:13 UTC
