### ISSUE TITLE
LoadLibrary failed with error 1114: Windows 10 error on a new install.

### ISSUE THREAD

**Issue by 31415pi** [VCVRack/Rack#702] opened 2018-02-11 00:37 UTC
OS (if applicable): Windows 10, 6gb ram, i7
Version (or "dev" if compiling from source) : ~~Current release as of 12/19/2017~~ 0.5.1

Full error:

LoadLibrary failed with error 1114: A dynamic link library (DLL) initialization routine failed. 

If I follow the directions in the link below, then upon boot it tries to select a monitor that is not attached thus preventing me from actually logging into windows. I have not been able to reconcile the larger error of why the instructions below do not work, but is there some way to force VCV Rack to run without using the graphics drivers it is trying to utilize?
![image](https://user-images.githubusercontent.com/31289154/36068047-a06ddf94-0e80-11e8-94b1-fcc0b630bcf7.png)

http://www.howto-connect.com/loadlibrary-failed-with-error-1114-windows-10/

**Comment by 31415pi** [comment] 2018-02-11 19:33
It is a fresh install. The link below mentions its part of switching graphics drivers. When I adjusted those for processing and pure data functionality, they ran, but restarting was a nightmare. Since then I don't mess with the graphics settings. It was an assumption on my part that the same error message was prevalent for my issue as well as the links authors issue. I haven't installed any plugins along with VCV rack, just the main install.

**Comment by AndrewBelt** [comment] 2018-02-11 19:45
Do you have an intact `log.txt` file in your `My Documents/Rack/` folder?

**Comment by 31415pi** [comment] 2018-02-11 19:50
[info] Rack v0.5.1
[info] Current working directory: C:\Program Files\VCV\Rack
[info] Global directory: ./
[info] Local directory: C:\Users\forexample\Documents/Rack/
[info] Loading plugins from ./plugins
[info] Loaded plugin ./plugins/Fundamental/plugin.dll
[info] Loading plugins from C:\Users\forexample\Documents/Rack/plugins

**Comment by 31415pi** [comment] 2018-02-11 19:56
Plugins folder is empty also.

**Comment by AndrewBelt** [comment] 2018-02-11 20:00
So it looks like it links to all the required DLLs in the distribution, including the Fundamental's plugin.dll. I don't see why it's complaining then, unless a dependency loads something when the first frame is rendered or something.

**Comment by 31415pi** [comment] 2018-02-11 22:15
Yeah I am not sure whats going on. It might be trying to force a graphics adapter that is not wanting to be used to display the first frame. I do not see any splash screen or anything just the error.

**Comment by multimulti** [comment] 2018-06-16 09:32
I had the same error just after first install of VCV Rack on Win10.

The problem appears to be caused by having "AMD Switchable Graphics". [This post here](https://eu.battle.net/forums/en/wow/topic/17610953802#post-6) fixed the problem!

> Can I get you guys to check the graphics cards you are using as this seems to be linked to java and some cards.
> What you will need to do is:
Open the Control Panel
Go into the Power Options
Edit Plan Settings
Change Advanced Settings
 -Switchable Dynamic Graphics
 -Global Settings
 -Change both settings to Maximise Performance
Then close the Window and try again.

**Comment by bihubihu** [comment] 2019-09-16 02:04
same error too and my computer is not using amd video card
and no Switchable Dynamic Graphics
how to fix it
Thanks!

**Comment by Deviantdrone** [comment] 2020-02-04 17:38
Hi there, 
For me I had to open AMD catalyst control center. And choose High performance for rack.exe on the switchable graphics application settings. And it works !

**Comment by AndrewBelt** [comment] 2020-04-01 03:49
This issue is old and likely obsolete, closing. Open a new issue if this bug is still present.

**Closed by AndrewBelt** 2020-04-01 03:49 UTC
