### ISSUE TITLE
LFO and Clock Divider

### ISSUE THREAD

**Issue by MaurizioDB** [VCVRack/Rack#79] opened 2017-09-14 13:52 UTC
If they are not already in the "to do" list, it would be awesome to add an LFO with multiple waveforms ad very slow rates, and a clock divider.

**Comment by AndrewBelt** [comment] 2017-09-14 14:20
Duplicate of #45 for the LFO. A clock divider will likely come in the next released plugin.

**Comment by MaurizioDB** [comment] 2017-09-14 14:24
Sorry fo the duplicate!
Good for the clock divider!

**Closed** 2017-09-14 14:27 UTC
