### ISSUE TITLE
stuck on over 100% usage cpu

### ISSUE THREAD

**Issue by milingosutera** [VCVRack/Rack#99] opened 2017-09-17 14:01 UTC
vcvrack on my macbook pro retina 13 inch stuck on activity monitor on over 100% cpu usage and more. from the first minute the fan start to get really crazy and seeing on activity monitoring app it goes often to 190% cpu

**Comment by AndrewBelt** [comment] 2017-09-17 14:03
Duplicate of #9

**Closed by AndrewBelt** 2017-09-17 14:03 UTC
