### ISSUE TITLE
Latency compensation for midiclock to cv

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Rack#278] opened 2017-10-20 18:56 UTC
Hi, could you guys please add the option to delay or advance the incoming midi signal like you can in Ableton so we can get use VCV also with standalone grooveboxes, its quite of a hassle to do it with the delay from Fundamental, it would be better if there is a offset control in the midi clock to cv module.

**Comment by bontric** [comment] 2017-10-20 22:34
I tested the midi clock with a novation circuiut and did not have a delay, but maybe I have to test more thoroughly. Adding an optional offset should be possible however so I'll look into that.

**Comment by AndrewBelt** [comment] 2017-10-20 22:36
I can understand delaying the signal but advancing seems physical impossible.

**Comment by sanderbaan** [comment] 2017-10-21 05:52
Most korg devices will have a delay and my octatrack also has a delay ;) only way to sync it steady is by using a audio sync.

**Comment by bontric** [comment] 2017-10-21 06:57
@AndrewBelt I think he means shifting it. Note that, at least on my device, the midi clock signal is always send even if the clock is stopped. So pressing play basically means "start with the next tick". Therefore you can shift the clock signal to have both ticks at the same time and resetting the clock should keep them in sync. 

@sanderbaan I'll have something done soon, would be great if you could test that then and tell me if that works for you

**Comment by sanderbaan** [comment] 2017-10-21 07:01
And I was referring to Ableton as there you can shift in both positive and negative in time ;) See screenshot
![screen shot 2017-10-21 at 09 00 26](https://user-images.githubusercontent.com/15910225/31849162-5e6fe6c2-b63e-11e7-8a96-9e7aecd84aeb.png)

**Comment by bontric** [comment] 2017-10-21 07:30
> @bontric sure just let me know when you have something i will check it. i was also trying to sync to maschine using the virtual maschine midi port and the midiclock module does not seem to receive a signal...though not sure if the problem is in maschine or vcv...

The clock waits to receive a midi clock start message before it starts "ticking". Probably obvious, but the only thing I can think of right now. Maybe play around a bit and check whether the Maschine actually sends the clock signal (try syncing with ableton e.g. as a reference) 

> And I was referring to Ableton as there you can shift in both positive and negative in time ;) See screenshot

Kind of weird that they still call it delay then.. The problem is that we need to precisely time (and predict) the clock signals. I have to see whether this is somehow possible with a reasonable amount of afford.

**Comment by sanderbaan** [comment] 2017-10-21 07:41
For now a delay would be great ;)

**Comment by bontric** [comment] 2017-10-21 08:53
Okay here is a very simplistic implementation of the delay : 
(Best to copy your Rack folder and do this in the copy)
```bash
git pull https://github.com/bontric/Rack-MIDICC-Fork 2017-10-bontric-midi-interface-revamp
```

Using this might be a bit unintuitive:
+ You must turn the knob either completely to the left, or completely to the right **before** starting your clock
+ If knob is turned to the left at the beginning, turning to the right delays the signal
+ If knob is turned to the right at the beginning, turning to the left advances the signal

**Comment by sanderbaan** [comment] 2017-10-21 09:16
I checked it,could you change the range of the knob perhaps...i get the best results in the first quarter left of the knob clockwise...would be nice to have a value display also to see what the value is

**Comment by bontric** [comment] 2017-10-21 10:00
Yeah.. It's obviously just a hacky "see if it works" prototype. But can you use this already? Does it help you? 

I'm looking into a more sophisticated implementation but it might take quite some time

**Comment by sanderbaan** [comment] 2017-10-21 10:10
It kinda works, still feels that I cannot get it tight enough but that could also be the range/curve of the knob...

**Comment by bontric** [comment] 2017-10-21 11:19
Okay, so there more I look into this I have to say, this is quite tricky to do properly. I think it will be significantly easier to just implement delay with a module that sends a midi out clock. 
I might still spend some time playing around with this, but I won't focus on finishing it. 

@AndrewBelt I think we can close this issue and add this as a feature request for midiOut Clock in #81 

> but that could also be the range/curve of the knob

As I said, the maximum delay you can set depends on the bpm. (The implementation heavily relies on the midi clock specification and is limited to some simple tricks so I can't simply scale the range for the knob properly)

**Comment by sanderbaan** [comment] 2017-10-21 11:21
Ok understood

**Comment by sanderbaan** [comment] 2017-10-21 11:23
We are lacking delay modules in Rack....its quite hard to use the one in Fundamantal, to be really precise... :/

**Comment by sanderbaan** [comment] 2017-10-21 11:25
https://www.schneidersladen.de/de/doepfer-a-162-dual-trigger-delay.html

thats what we need :)

**Comment by bontric** [comment] 2017-10-21 12:38
Yeah, that would be pretty cool. Maybe ask on reddit/facebook for that. Maybe one of the module guys will give it a shot :)

**Comment by bontric** [comment] 2017-10-21 12:44
> https://www.schneidersladen.de/de/doepfer-a-162-dual-trigger-delay.html

And thank's, this actually gives me another idea. I'll give it another shot in the next days and come back to you if I have something interesting

**Comment by sanderbaan** [comment] 2017-10-21 12:47
Yes also check this reaktor block if you have reaktor

https://www.native-instruments.com/de/reaktor-community/reaktor-user-library/entry/show/10301/

**Comment by AndrewBelt** [comment] 2017-10-21 15:23
Adding to #81

**Closed by AndrewBelt** 2017-10-21 15:23 UTC
