### ISSUE TITLE
BUG: Patch file mismatch on restart after crash

### ISSUE THREAD

**Issue by vuzhmusic** [VCVRack/Rack#1902] opened 2021-03-22 04:10 UTC
### Details

Operating system and version:  MAC OS 10.12.6
Rack version (vX.Y.Z): 1.1.6
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Summary

After a hard crash, when I re-start Rack, the program is good at recalling where I am with a patch, even if I haven't saved recently.   Unfortunately, however, sometimes there is a mismatch on the file name, so it brings up whatever patch I'm workign on, but the file name will instead be a different patch, one of the most recent prior patch files I had open.  If I don't notice that this has happened after a crash, and I continue to work on the file, then save, then I overwrite a prior patch!  This has now happened to me multiple times and it's very upsetting when I don't have a back up.  
I backed up my disk on the 19th, and just had a crash and then overwrote the patch I made yesterday with the one I was working on tonight when I didn't notice that this bug had occurred.

### Steps to reproduce

I can't predict what will cause a crash.  But they happen on random occasion when I'm patching.
Tonight's crash occurred when I was patching and added NYSTHI's Poly Seven Seas oscillator, and clicked the Swarm On-Off button.

This also doesn't happen every time I have a crash, but often enough to be a problem!

So I can't offer an easy step by step to reproduce.

[log.txt](https://github.com/VCVRack/Rack/files/6179409/log.txt)

**Comment by AndrewBelt** [comment] 2021-03-22 08:50
Duplicate of https://github.com/VCVRack/Rack/issues/1749

**Closed by AndrewBelt** 2021-03-22 08:50 UTC
