### ISSUE TITLE
MacOS 10.12.6 No knobs issue

### ISSUE THREAD

**Issue by glemonmondon** [VCVRack/Rack#67] opened 2017-09-13 19:37 UTC
Rack v0.3.1 isn't running good on my Macbook pro (MacOS 10.12.6). There are no knobs on modules, and no jack connections.

**Comment by joemcmahon** [comment] 2017-09-14 05:17
Confirmed here. Trying a local build to see if that's the issue.

**Comment by AndrewBelt** [comment] 2017-09-14 06:05
Duplicate of #17

**Closed by AndrewBelt** 2017-09-14 06:05 UTC
