### ISSUE TITLE
Mint 64 (Ubuntu 16) ALSA errors

### ISSUE THREAD

**Issue by asbaklm** [VCVRack/Rack#411] opened 2017-11-19 12:13 UTC
OS (if applicable):  
Version (or "dev" if compiling from source): current Master as of 19-Nov-2017

Can't get ALSA audio to work properly with current VCVRack.
As a test, ALSA & Jack works fine with Ardour and device hw:2.

**Seeing these messages when running Rack with "make run"**

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:2,0), Device or resource busy.
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:2,0), Device or resource busy.
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (default), Device or resource busy.
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:2,0), Device or resource busy.
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:2,0), Device or resource busy.
MidiInAlsa::openPort: ALSA error making port connection.

**Comment by AndrewBelt** [comment] 2017-11-19 12:41
Are you unable to use your desired ALSA device with all other programs closed, including your browser, Ardour, disable PulseAudio, etc?

**Comment by asbaklm** [comment] 2017-11-19 13:01
Yep hw:2 works fine w. Jack & ALSA with other apps such as Ardour, virtual synths, webbrowser etc.

hw:2 used to work with VCVRack (this was from a build made about a month ago) but things have changed and now it's acting strangely. 

In Rack I can see other loopback audio devices and the onboard audiocard but not hw:2. (hw:2 is a USB Edirol UA-25, which is well supported in ALSA / Linux)

Don't think hw:2 MIDI is working either.

Tried rebooting... no dice.

**Comment by AndrewBelt** [comment] 2017-11-19 13:27
Oh, I forgot that I made this https://github.com/AndrewBelt/rtaudio_test this morning. Run it and see if it works. If still no sound, we can rule out Rack and blame RtAudio.

**Comment by asbaklm** [comment] 2017-11-19 14:00
I cloned it to the rack folder, compiled and ran it. It generates a cacophony, lol. Still see these kinds of errors.

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:2,0), Device or resource busy

And of course, the original issue remains that Rack doesn't see the audio device. So do I need to revert to an older git branch?

**Comment by AndrewBelt** [comment] 2017-11-19 14:04
Okay, then this is a bug with RtAudio and not Rack.

Rack recently switched from portaudio to RtAudio.

**Comment by asbaklm** [comment] 2017-11-19 14:09
Ahh.... progress :dagger: 
Thanks for the update, I'll try using an older commit.

**Comment by asbaklm** [comment] 2017-11-19 15:14
I checked out a much older commit  a581412 and now I see my Jack & ALSA modules again.

**Comment by AndrewBelt** [comment] 2017-11-19 15:23
We've already confirmed that this is an RtAudio issue, and that is pre-RtAudio.

**Comment by modlfo** [comment] 2019-06-04 18:03
I'm closing this issue since it's an RtAudio problem.

**Closed by modlfo** 2019-06-04 18:03 UTC
